### ISSUE TITLE
Full backups threshold pair(s) for [number of backup files] / [database size]

### ISSUE THREAD

**Issue by ad-eternum** [olahallengren/sql-server-maintenance-solution#100]
Hi Ola,

Please consider adding ability for a user to specify threshold pair(s) for [number of backup files] / [database size]. We already have @NumberOfFiles parameter and I think it would be useful to be able to define two or more bins based on database size and specify number of backup files for each bin. 
For example: 1 file up to 500 GB, 2 files up to 1 TB, 4 files up to 10 TB, and 8 files after that.

**Comment by chadwestes** [comment]
ad-eternum,
Could you explain the requirement of binning your backup splits?  I'm curious if I have not thought out the solution I proposed to a similar issue. 
I created a parameter to split database files above a certain size such that you would get a given number of roughly equal sized files.  For instance if your threshold was 50 GB:
DB's <= 50 GB would be 1 file
DB's > 50 and <= 100 would be 2 files
DB's >100 and <= 150 would be 3 files
etc.
Would that solution work in your case?

**Comment by ad-eternum** [comment]
@chadwestes  Likely yes, this would work as an alternative solution.

**Comment by olahallengren** [comment]
I am working on a feature with a database size parameter to control if multiple - files should be used.

```
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@NumberOfFiles = 4,
@MinDatabaseSizeForMultipleFiles = 1024
```

MinDatabaseSizeForMultipleFiles is the size of the database in MB.

It is in the branch feature-MinDatabaseSizeForMultipleFiles.
https://github.com/olahallengren/sql-server-maintenance-solution/tree/feature-MinDatabaseSizeForMultipleFiles

It does not give the same flexibility as @ad-eternum's request, but it is easy to use, and provides a way to avoid backing up to multiple - files for small databases.

**Comment by olahallengren** [comment]
It is now in the branch feature_MinDatabaseSizeForMultipleFiles_MaxFileSize.
https://github.com/olahallengren/sql-server-maintenance-solution/tree/feature_MinDatabaseSizeForMultipleFiles_MaxFileSize

Please see more details on the issue #227.

**Comment by olahallengren** [comment]
The features that I have been working on in this area, have been released now.
https://ola.hallengren.com/versions.html

https://ola.hallengren.com/sql-server-backup.html#MinBackupSizeForMultipleFiles

https://ola.hallengren.com/sql-server-backup.html#MaxFileSize

**Comment by ad-eternum** [comment]
Please see more details on the issue #227.
