### ISSUE TITLE
Feature req: add prefix for jobname

### ISSUE THREAD

**Issue by olsonnn** [olahallengren/sql-server-maintenance-solution#102]
It would be nice if all jobs have a prefix in the name during installation.

For example: 
DatabaseBackup - SYSTEM_DATABASES - FULL
to
DBA - DatabaseBackup - SYSTEM_DATABASES - FULL

In this way it's much easier for devs to see regular jobs and APP related jobs.

Updating the maintenance solution would be easier  as well..

**Comment by olahallengren** [comment]
An issue for this feature already exists, #75.

Could you write a comment on the other issue, and close this one?

**Comment by olsonnn** [comment]
Whoops, i missed that one.. Sorry.

**Comment by olsonnn** [comment]
closed
