### ISSUE TITLE
SQL Agent Log Files written with Job/Step in the filename 

### ISSUE THREAD

**Issue by Rupp29** [olahallengren/sql-server-maintenance-solution#103]
Logging SQL Agent Job log files would be great if they would have the Job Name/Step instead of a GUID.
This will make them much more readable.

**Comment by olahallengren** [comment]
This was changed some years ago, after new SQL Server Agent tokens for JOBNAME and STEPNAME were added in SQL Server 2016.

For previous versions it is still using the JOBID and STEPID tokens.
