### ISSUE TITLE
Exclude tables from UPDATE_STATISTICS from all the databases on the instance

### ISSUE THREAD

**Issue by rajuvd** [olahallengren/sql-server-maintenance-solution#104]
I have few audit tables which takes 70% of my maintenance window.  Appreciate if we can have a feature to exclude tables from update statistics the way we have it for indexes.

**Comment by olahallengren** [comment]
You can use the Indexes parameter. That works also for statistics.

https://ola.hallengren.com/sql-server-index-and-statistics-maintenance.html#Indexes

**Comment by rajuvd** [comment]
Thanks Ola, I was trying without ALL_Indexes, after I mentioned this it seems to be working.
________________________________

**Comment by olahallengren** [comment]
It is good that you got it working.
