### ISSUE TITLE
Add better support for COPY_ONLY Log backups

### ISSUE THREAD

**Issue by MichaelWest22** [olahallengren/sql-server-maintenance-solution#107]
It is possible to improve the way Log backups work by using COPY_ONLY Log backups at very regular intervals but only keep these backups around for a very short duration.  These backups are like tail log backups and contain the complete tail of the log but don't truncate the log or effect the normal log backup sequence.  You can schedule these COPY_ONLY backups to happen every 5-10 minutes but set them to clean up after 1 hour for example.  You then schedule normal Log backups every hour or even less often and you will have less log files to maintain and restore in an emergency.  When restoring you apply the latest dated COPY_ONLY log after applying the normal Logs.

However your backup script does not handle the deleting of COPY_ONLY log backups well and forces you to keep around all logs back to the last full/differential backup date.  One simple way to fix this for COPY_ONLY log backups is to update the @CurrentLatestBackup to be the date of the last Log backup instead of looking at the last diff/full backup.  Below is one way to change this section of code.  Type is now filtered to D/I normally but L when CopyOnly is Y.  Also need to exclude is_copy_only=1 records.

      IF @CurrentBackupType = 'LOG'  AND (@CleanupTime IS NOT NULL OR @MirrorCleanupTime IS NOT NULL)
      BEGIN
        SELECT @CurrentLatestBackup = MAX(backup_finish_date)
        FROM msdb.dbo.backupset
        WHERE ((([type] IN('D','I') AND @CopyOnly = 'N') OR ([type]='L' AND @CopyOnly = 'Y'))
        OR database_backup_lsn < @CurrentDifferentialBaseLSN)
        AND is_damaged = 0
        AND is_copy_only = 0
        AND database_name = @CurrentDatabaseName
      END

With this change you can set @CleanupTime = 0 in your COPY_ONLY log backup task that runs every few minutes and it will just keep copies of these tail log backups back to the date of the last successful normal Log backup so you will always have a full restore chain.

There is the new smart backup setup where you can set it to only backup the log when it gets above a certain size or a certain time is exceeded.  If you use this feature you can greatly reduce the number of small backup logs you need to maintain but it has implications on your recovery as you may not have a recent Log backup in an emergency if the log use is small right now.  But combining this feature with very regular COPY_ONLY log backups overcomes this limitation and you minimize the number of backups you need to manage and have much more up to date recovery data in an emergency.

Another option I thought of which would be interesting is to change the smart backup checking to change the Log backup into a COPY_ONLY_LOG backup type (and lower CleanupTime maybe?) when the LogSizeSinceLastLogBackup was below the threshold set.  Currently it just skips the log backups but instead it could perform one of these temporary log backups.  This is sort of similar to the @ChangeBackupType option in some ways.  With this setup you could have just one Log backup schedule running every few minutes but only a few Large log backups will get created along with these short term backups.  The other advantage of this setup is that if you have very high DB Log changes happening it will not create additional load generating lots large duplicated COPY_ONLY log files until the next full log backup runs which is a potential downside of my initial idea.

**Comment by olahallengren** [comment]
I think that the downside of doing COPY_ONLY log backups is that you back up the same log records many times.
