### ISSUE TITLE
Exclude statistics table

### ISSUE THREAD

**Issue by clambrechts** [olahallengren/sql-server-maintenance-solution#110]
Hi Ola,

I split maintenance plan : Indexes and stats with your solution. I use filter object with @indexes. No problem with indexes, but, Stats don't respect my exclusion.

For exemple
 @Indexes = 'ALL_INDEXES, -%.neolane.grp%,%.neolane.wkDlv_%,%.neolane.wkf%,%.neolane.Xtk%',

in

execute lbnadmindb.fnacdba.IndexOptimize
 @Databases = 'USER_DATABASES, -BE_DTM_RCU',
 @FragmentationLow = NULL,
 @FragmentationMedium = NULL,
 @FragmentationHigh = NULL,
 @LogToTable = 'Y',
 @MaxDop = 8,
-- @TimeLimit = 7200,
 @Indexes = 'ALL_INDEXES, -%.neolane.grp%,%.neolane.wkDlv_%,%.neolane.wkf%,%.neolane.Xtk%',
 @DatabasesInParallel = 'Y',
 @PartitionLevel = 'Y',
 @UpdateStatistics = 'ALL',
 @StatisticsSample = 100,
 @OnlyModifiedStatistics = 'Y'	

Logtable : 

![image](https://user-images.githubusercontent.com/40592330/43077255-42aaf752-8e87-11e8-9635-529ecd13785c.png)

Regards

**Comment by olahallengren** [comment]
If you are excluding multiple tables, you need to put a minus (-) for each exclusion.

```
@Indexes = 'ALL_INDEXES, -Db1.Schema1.Tbl1, -Db1.Schema1.Tbl2'
```

**Comment by clambrechts** [comment]
Thanks

**Comment by erezhren** [comment]
Hello Ola,
Is it possible to exclude tables using NOT LIKE %%?
@Indexes = 'ALL_INDEXES, -NOT LIKE %Db1.Schema1.Tbl1%' - something like that?

Thanks


Erez

**Comment by ahmetsngr** [comment]
> Hello Ola, Is it possible to exclude tables using NOT LIKE %%? @indexes = 'ALL_INDEXES, -NOT LIKE %Db1.Schema1.Tbl1%' - something like that?
> 
> Thanks
> 
> Erez

Hi @erezhren, 
Did you find the solution? So @indexes = 'ALL_INDEXES, -NOT LIKE %Db1.Schema1.Tbl1%'  this code is working?

**Comment by olahallengren** [comment]
@erezhren and @ahmetsngr, you can use it like this:

`@Indexes = 'ALL_INDEXES, -%Db1.Schema1.Tbl1%'`
