### ISSUE TITLE
IndexOptimize:  @Index parameter and Schemas

### ISSUE THREAD

**Issue by SQLPadre** [olahallengren/sql-server-maintenance-solution#116]
I have noticed that if the schema name includes a period, the IndexOptimze will not work correctly.

i.e.  [Database].[SchemaPart1.SchemaPart2].[Table]

I even have 3 part schema names all divided by periods :(
I know this is not usual naming convention, but it is the naming convention of one of my servers. 

unless I am missing something...

**Comment by olahallengren** [comment]
This should work fine if you are using brackets. Try this:

```@Indexes = '[Database].[SchemaPart1.SchemaPart2].[Table]'```

**Comment by SQLPadre** [comment]
OK, but I guess it won't work using the parameter @Databases='DBNAME'?

with a database that has 760 tables and 1592 indexes, that makes way more work then necessary to script out all of those indexes
