### ISSUE TITLE
automatically purge the databaseIntegrity*.txt and index*.txt file after x days 

### ISSUE THREAD

**Issue by red8rain** [olahallengren/sql-server-maintenance-solution#118]
Ola,

Can you please enable the ability to automatically prune the log files after x days?  I just had to clean up over 600 files (300 per process) on one of my server.  I'm in the process of putting together a powershell script that will purge it for it me automatically but if it was an option by default, that would be great!

**Comment by olahallengren** [comment]
There is a job called [Output File Cleanup] that is deleting old output - files. The job is created by MaintenanceSolution.sql.
