### ISSUE TITLE
Support CleanupTime in Linux server

### ISSUE THREAD

**Issue by denovellis** [olahallengren/sql-server-maintenance-solution#119]
Hi,

Do you plan backup retention in linux os ? 

Regards,

Fab

**Comment by JoshKeegan** [comment]
I believe `xp_delete_file` has now been added to SQL Server for Linux. 
To check if anything else would stop this, I've just tried removing the checks that prevented this from running within `DatabaseBackup`, run it with `@CleanupTime = 168` & it seems to have worked correctly.

I am not sure when exactly `xp_delete_file` was added though, but I suppose the checks should be changed to instead check whether you are on Linux and on a version before it got added (if we can find when that was).

**Comment by olahallengren** [comment]
Thank you @JoshKeegan.

I have added support for cleanup on Linux.
https://ola.hallengren.com/versions.html
