### ISSUE TITLE
Block Blob instead of Page Blob

### ISSUE THREAD

**Issue by michaelseto** [olahallengren/sql-server-maintenance-solution#120]
We are leveraging the database backup solution and trying to convert our backups in Azure to the 'Archive' access tier. However, it appears we cannot do that as the backups were uploaded as a 'Page Blob' type, when they should be 'Block Blob'.

Where would this be fixed?

Thank you

**Comment by olahallengren** [comment]
I am not sure that I understand this. Is there an issue with the DatabaseBackup stored procedure, when backing up to Azure Blob Storage?

**Comment by michaelseto** [comment]
I see the backups uploaded as page blobs and I want them uploaded as block blobs. That’s as straight forward as I can explain it.

**Comment by olahallengren** [comment]
How are you executing DatabaseBackup? Could you post the command with all parameters.

**Comment by michaelseto** [comment]
Yes let me get that for you, just a moment please

**Comment by michaelseto** [comment]
EXECUTE DBA.dbo.DatabaseBackup @AvailabilityGroups = 'AG_Name',
@URL = 'https://mybackups.blob.core.windows.net/full/',
@Credential = 'blob_credentials',
@BackupType = 'FULL',
@Compress = 'Y',
@Encrypt = 'Y',
@EncryptionAlgorithm = 'AES_256',
@ServerCertificate = 'Backup_Certificate'

**Comment by olahallengren** [comment]
Thank you. Which version of SQL Server are you running on?

**Comment by michaelseto** [comment]
2016 (13.0)

**Comment by olahallengren** [comment]
You need to create a Shared Access Signature (and create a credential for that), in order to back up to block blobs

You should not use the ```@Credential``` parameter in DatabaseBackup then.

https://blogs.msdn.microsoft.com/sqlcat/2017/03/10/backing-up-a-vldb-to-azure-blob-storage/

**Comment by michaelseto** [comment]
Thank you, I will update you on our progress.

**Comment by olahallengren** [comment]
Microsoft has also improved the documentation here:

"Backup to block blob vs. page blob"
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2017
