### ISSUE TITLE
Integrity Check on Basic Availability Group fails on secondary

### ISSUE THREAD

**Issue by cfradenburg** [olahallengren/sql-server-maintenance-solution#122]
> Date and time: 2018-08-01 14:55:33
>  
> Date and time: 2018-08-01 14:55:33
> Database: [KS_Archive]
> Status: ONLINE
> Standby: No
> Updateability: READ_WRITE
> User access: MULTI_USER
> Is accessible: Yes
> Recovery model: FULL
> Availability group: m7uvmgtwprdag_Archive
> Availability group role: SECONDARY
>  
> Date and time: 2018-08-01 14:55:33
> Command: DBCC CHECKDB ([database1]) WITH NO_INFOMSGS, ALL_ERRORMSGS, DATA_PURITY
> Msg 976, Level 14, State 1, Line 1
> The target database, 'database1', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

This is a [documented limitation](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-2017).  The database status is returned as ONLINE so it passes that check.

**Comment by cfradenburg** [comment]
Pull request [#123](https://github.com/olahallengren/sql-server-maintenance-solution/pull/123) submitted.

**Comment by olahallengren** [comment]
I believe that this issue has been fixed some months ago. Could you try updating to the latest version.

**Comment by cfradenburg** [comment]
I just did and it works.  I had looked in the GitHub issues for documentation but not the version history on your site.  Thank you.
