### ISSUE TITLE
IndexOptimize @Databases parameter do not exist: [tempdb].

### ISSUE THREAD

**Issue by PeterSkoglund** [olahallengren/sql-server-maintenance-solution#130]
You get the  @Databases parameter do not exist: [tempdb] when running IndexOptimize.

Code to reproduce
-------------

EXECUTE dbo.IndexOptimize 
    @Databases = @DbCheckDatabases, 
    @FragmentationLow = NULL, 
    @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', 
    @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', 
    @FragmentationLevel1 = 10, 
    @FragmentationLevel2 = 30, 
    @TimeLimit = 7200,
    @UpdateStatistics = 'ALL',
    @OnlyModifiedStatistics = 'Y',
    @WaitAtLowPriorityMaxDuration=20,
    @WaitAtLowPriorityAbortAfterWait='SELF',
    @Resumable = 'Y'

Parameters: @Databases = 'master,model,msdb,PackagingRule,PackagingRule_TestBed,ProductLog,ProductLog_TestBed,tempdb,Testdata,TripPackageRules,TripPackageRules_TestBed', @FragmentationLow = NULL, @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationLevel1 = 10, @FragmentationLevel2 = 30, @MinNumberOfPages = 1000, @MaxNumberOfPages = NULL, @SortInTempdb = 'N', @MaxDOP = NULL, @FillFactor = NULL, @PadIndex = NULL, @LOBCompaction = 'Y', @UpdateStatistics = 'ALL', @OnlyModifiedStatistics = 'Y', @StatisticsModificationLevel = NULL, @StatisticsSample = NULL, @StatisticsResample = 'N', @PartitionLevel = 'Y', @MSShippedObjects = 'N', @Indexes = NULL, @TimeLimit = 7200, @Delay = NULL, @WaitAtLowPriorityMaxDuration = 20, @WaitAtLowPriorityAbortAfterWait = 'SELF', @Resumable = 'Y', @AvailabilityGroups = NULL, @LockTimeout = NULL, @LockMessageSeverity = 16, @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'N', @Execute = 'Y'
Version: 2018-07-16 18:32:21
Source: https://ola.hallengren.com
 
-->

Msg 50000, Level 16, State 1, Procedure dbo.IndexOptimize, Line 1012 [Batch Start Line 0]
The following databases in the @Databases parameter do not exist: [tempdb].

**Comment by OliverUweHahn** [comment]
Hi Peter,
how did you define @DbCheckDatabases?
I do not get the error. 
Could it be that you set the variable to the value 'tempdb'.
If you set the parameter explicitly to tempdb, this error is not prevented.
Are you executing the script in a loop?
Then you should definitely exclude tempdb.
Best regards,
Oliver

**Comment by olahallengren** [comment]
Could you try removing tempdb from the ```@Databases``` parameter.

**Comment by olahallengren** [comment]
IndexOptimize does not support doing index maintenance or update statistics in tempdb.

So you should get an error. That said, the error message could be better.
