### ISSUE TITLE
Distribution database not included in 'SYSTEM_DATABASES' maintenance jobs

### ISSUE THREAD

**Issue by SQLcyclopedia** [olahallengren/sql-server-maintenance-solution#133]
I wrongly assumed that distribution database would be included in 'SYSTEM_DATABASES' database backups and integrity check jobs. This isn't the case as defined here:

![sysdatabasedef](https://user-images.githubusercontent.com/37111394/44660309-1f332400-a9ff-11e8-9fc6-fc7a4577cd3c.png)

If not running such jobs for all 'USER_DATABASES' , this could easily be missed.

From the documentation, I'm not entirely sure how distribution database should be handled.

**Comment by olahallengren** [comment]
I guess that I should look at is_distributor in sys.databases to determine if it is a Distribution database.
https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql

From what I understand the name doesn't have to be Distribution.
https://docs.microsoft.com/en-us/sql/relational-databases/replication/distribution-database

**Comment by olahallengren** [comment]
I have changed this now so that the Distribution database is considered a system database.
https://ola.hallengren.com/versions.html

I am using is_distributor in sys.databases.
