### ISSUE TITLE
Upgrading older script with new script

### ISSUE THREAD

**Issue by cblaze22** [olahallengren/sql-server-maintenance-solution#135]
I have been using this script for about 5+ years now.  I would like to upgrade to the newest version.  Is there a best practice on this, or do I just download and run the newest script?  Any direction would be great.

**Comment by olahallengren** [comment]
You can just follow the step-by-step guide in the Frequently Asked Questions.

"I’m using an old version of the SQL Server Maintenance Solution. How do I upgrade to the most recent version?"

https://ola.hallengren.com/frequently-asked-questions.html
