### ISSUE TITLE
IndexOptimize @PageCountLevel

### ISSUE THREAD

**Issue by Brianc-DBA** [olahallengren/sql-server-maintenance-solution#136]
With the latest version of the solution, the @PageCountLevel parameter seems to be encountering failures.  We have a custom job that rebuilds indexes based on these thresholds in a certain database, in addition to a normal weekly job.

-- Version: 2018-07-16 18:32:21
-- Database version: SQL 2008 R2

-- Job step command:
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d DBA -Q "EXECUTE [dbo].[IndexOptimize] @Databases = 'xxxxxxxxxxxx', @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @PageCountLevel=25, @FragmentationLevel2 = 30, @UpdateStatistics = 'ALL', @OnlyModifiedStatistics = 'Y', @LogToTable = 'Y'" -b

-- Error:
HResult 0x1FD1, Level 16, State 1
@PageCountLevel is not a parameter for procedure IndexOptimize.

**Comment by BlitzErik** [comment]
Dumb question, did you mean `@MinNumberOfPages`?

![image](https://user-images.githubusercontent.com/11590415/44922063-4dbc4200-ad12-11e8-813a-3e1171e5aae3.png)

https://ola.hallengren.com/sql-server-index-and-statistics-maintenance.html

**Comment by Brianc-DBA** [comment]
No, I'm not certain if the parameter is changed in the new version.  I had updated to the latest version in our non-prod systems and am getting this failure.  Our prod systems are still running solution version 20180420 and the same command succeeds.

**Comment by BlitzErik** [comment]
Yep, the version history page is your friend here:

https://ola.hallengren.com/versions.html

> 1 Jun 2018
> Added support for setting the maximum number of pages in IndexOptimize. Use the parameter @MaxNumberOfPages.
> 
> Changed the name of the parameter @PageCountLevel to @MinNumberOfPages. This is a breaking change. If you are using @PageCountLevel in your jobs you need to change to @MinNumberOfPages.
> 
> Added the directory and file name token {Description}.

**Comment by Brianc-DBA** [comment]
Ah OK, thank you.
