### ISSUE TITLE
@PageCountLevel is not a parameter for procedure IndexOptimize. > make new code backward compatible?

### ISSUE THREAD

**Issue by jerryhung** [olahallengren/sql-server-maintenance-solution#140]
**Old SQL Job Step**
```sql
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d master -Q "EXECUTE monitor.dbo.IndexOptimize @Databases  = 'ALL_DATABASES',@FragmentationLow = NULL, @FragmentationMedium = 'INDEX_REBUILD_ONLINE,INDEX_REORGANIZE', @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REORGANIZE', @FragmentationLevel1 = 30, @FragmentationLevel2 = 50, **@PageCountLevel = 1000** ......................... " -b
```

But I deployed NEW IndexOptimize code yesterday and above job step broke with this error **"@PageCountLevel is not a parameter for procedure IndexOptimize."**

As new code only uses these 2 new parameters below
@MinNumberOfPages int = 1000,
@MaxNumberOfPages int = NULL,

**Fix**
- Deploy new IndexOptimize code (obviously, duh)
- Suggestion, to be backward compatible, maybe add a check for @PageCountLevel input and set it to @MinNumberOfPages

Thanks

**Comment by olahallengren** [comment]
I am sorry for this breaking change. I decided to change the name of the parameter @PageCountLevel to @MinNumberOfPages, when I added the parameter @MaxNumberOfPages in the 1 Jun 2018 release.
https://ola.hallengren.com/versions.html

**Comment by olahallengren** [comment]
Thank you for the suggestion, but I opted for not making the script backward compatible in this case.
