### ISSUE TITLE
DatabaseOrder not respected when used in conjunction with DatabasesInParallel

### ISSUE THREAD

**Issue by igx2** [olahallengren/sql-server-maintenance-solution#152]
When using @DatabasesInParallel = 'Y', databases to be processed are stored in the QueueDatabase table, along with the database order. If there are multiple jobs configured to use different orders, the database order for all queues, including active queues, will be updated to whichever queue was updated last. In my case, the frequent log backup order (random), is overriding the order of longer duration jobs: full/diff backup (size desc), and integrity (date asc).

This issue is present in stored procs: DatabaseBackup, DatabaseIntegrityCheck, and IndexOptimize. I believe the query responsible for this is the following:
```
UPDATE QueueDatabase
SET DatabaseOrder = tmpDatabases.[Order]
FROM dbo.QueueDatabase QueueDatabase
INNER JOIN @tmpDatabases tmpDatabases ON QueueDatabase.DatabaseName = tmpDatabases.DatabaseName
```
This lacks a predicate to limit the queues that are updated, resulting in all queues being updated with the same database ordering.

**Comment by olahallengren** [comment]
This issue has been fixed.
https://ola.hallengren.com/versions.html

Thank you for reporting it.
