### ISSUE TITLE
Update stats fails on memory optimized tables

### ISSUE THREAD

**Issue by alonsoh** [olahallengren/sql-server-maintenance-solution#154]
UPDATE STATISTICS <table> [PK__AppRestr__36AF893001E337BD] WITH FULLSCAN

Comment: ObjectType: Table, IndexType: Index, IndexType: NonClustered, Incremental: N, RowCount: 24, ModificationCounter: 0
Msg 50000, Level 16, State 1, Procedure dbo.CommandExecute, Line 194 [Batch Start Line 2]
Msg 41317, A user transaction that accesses memory optimized tables or natively compiled modules cannot access more than one user database or databases model and msdb, and it cannot write to master.
Outcome: Failed
Duration: 00:00:00

**Comment by olahallengren** [comment]
It looks like there is a bug in SQL Server that has been fixed.
https://support.microsoft.com/en-ca/help/4459327/fix-error-41317-when-you-enable-server-audit-and-you-use-in-memory-tra

Could you try updating to the latest CU, and also the latest version of my script.

**Comment by lmarkum** [comment]
I am now seeing this same error after updating from SQL Server 2019 to 2022. Is there any fix for this coming in a version of the IndexOptimize script?

**Comment by olahallengren** [comment]
I am not able to reproduce this issue.

Does anyone have a repro with the latest version of IndexOptimize and the latest Service Pack and Cumulative Update Package?

**Comment by krzysiek250780** [comment]
> I am not able to reproduce this issue.
> 
> Does anyone have a repro with the latest version of IndexOptimize and the latest Service Pack and Cumulative Update Package?

Hi, on my servers it is happening after enabling advanced options ‘tempdb metadata memory-optimized’.

**Comment by CommanderBond** [comment]
Yes, it's occurring when "tempdb metadata memory-optimized" since the IndexOptimize procedure is typically in another database like the user objects to be stats-updated. Then TempDB is involved.
SQL Server version and CU doesn't matter, it's also occurring on SQL Server 2002 with latest CU.

**Comment by olahallengren** [comment]
@CommanderBond, I am still not able to reproduce the issue.

Do you have a repro script that includes enabling features, creating a database and tables, populating with data, and executing the stored procedure?

**Comment by CommanderBond** [comment]
We have the same problem in a custom script for checking table stats while joining sys.stats, sys.objects, sys.stats_columns, sys.schemas with `CROSS APPLY sys.dm_db_stats_properties`: This does not work if our query will return data from in-memory tables (e.g. without a tables filter on a whole database with in-memory tables and disk-based tables in this database or filtered on an in-memory table).
However, such a query _will_ work, if no in-memory table is touched by the query.

I think I will have to re-write our query not to return everything in a single SELECT, but first insert the first part of the data from sys.stats, sys.objects, sys.stats_columns, sys.schemas into a temp table, then do an UPDATE on this temp table cross applying it with  sys.dm_db_stats_properties. This is working in all cases whether in-memory objects are touched or not.

**Comment by olahallengren** [comment]
I have created a fix in https://github.com/olahallengren/sql-server-maintenance-solution/pull/880.
Please do some testing before I merge it.

**Comment by CommanderBond** [comment]
See my confirmation there: https://github.com/olahallengren/sql-server-maintenance-solution/pull/880#issuecomment-2615081291
