### ISSUE TITLE
Checking existence of excluded dbs

### ISSUE THREAD

**Issue by TeamKinetic** [olahallengren/sql-server-maintenance-solution#155]
Hi there,

Firstly..thank you, great set of scripts!

I use the exclusion parameter to ensure that any new databases are backed up by default.

However last week I removed an old legacy DB that was in the exclusion list and this caused the backup jobs to fail =(

Could you check for the existence of these tables before executing the commands..?

Thanks again
Rolf

**Comment by olahallengren** [comment]
Thank you for the feedback. There are of course pros and cons of this check. In the current design, the stored procedure will raise an error, but then continue working on the databases.

I got a lot of feedback before from users that had been doing some small typo, and the job just ran successfully. That can be bad even if you exclude a database.

Please also see my comment here: https://github.com/olahallengren/sql-server-maintenance-solution/issues/61#issuecomment-395225688.

**Comment by olahallengren** [comment]
I have now changed the severity for this check from 16 to 10. You will still get the message in the output file, but the job will not fail.

**Comment by SQLNerd** [comment]
Fantastic! Thank you for all the work you put into this.

**Comment by TeamKinetic** [comment]
Thank you =)
