### ISSUE TITLE
Index recommendations on View (parsing JSON Data)

### ISSUE THREAD

**Issue by nm-a** [olahallengren/sql-server-maintenance-solution#157]
Hi,
While working on one dynamic system, I have got the requirement to create dynamic screens & stored data in database.

As these are dynamic screens, we can't pre-define structure for the screens / tables. I am storing data in JSON format to address this issue.

I see performance issues while accessing data, can we find out required indexes on the Views.

**Scenario:**
1. Table is storing data in JSON Format
2. Parsing data in SQL View into multiple columns 
3. Accessing Views from other SQL Objects.

Can we identify the required indexes on views & create them automatically.

thank you

**Comment by olahallengren** [comment]
This is good idea, but a bit outside the scope for the maintenance solution.
