### ISSUE TITLE
DirectoryStructure - option for DbVersion

### ISSUE THREAD

**Issue by dalekerr** [olahallengren/sql-server-maintenance-solution#163]
I append the SQL version to my @Directory parameter, but that means for different servers I have to manually add 2012 or 2014 or 2016 etc. So I was thinking it would be easier to have a DbVersion value for the DirectoryStructure and AvailabilityGroupDirectoryStructure parameters. That way, you could specify something like 
@DirectoryStructure = {DbVersion}{DirectorySeparator}{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}

Would this be do-able?

**Comment by olahallengren** [comment]
This could be done. The question is which version numbers that I should use:

1. 14
   SERVERPROPERTY('ProductMajorVersion')

2. 2017
   I could extract it from ```@@VERSION```, or do some mapping based on SERVERPROPERTY('ProductMajorVersion')

What would you prefer?

**Comment by dalekerr** [comment]
Personally I would prefer 2017, 2016, 2014 etc as I keep my backups in \2016\, \2014\, \2012\ etc subdirectories.

SERVERPROPERTY('ProductMajorVersion') may not be ideal as it was only introduced with 2008 SP4-GDR, 2008 R2 SP3-GDR, 2012 SP2-CU9, 2014 RTM-CU10 and 2014 SP1-CU3.

You could perhaps work with SERVERPROPERTY('ProductVersion') or SERVERPROPERTY('ResourceVersion') which have been around a lot longer. I can confirm that ProductVersion was in SQL 2000, hence I would go with that. The respective versions are 8.00.x, 9.00.x, 10.00.x, 10.50.x, 11.0.x, 12.0.x etc. NB. SQL 2012 went from 2 decimal places to 1.

**Comment by olahallengren** [comment]
Thank you for the input.

It is strange that there is no SERVERPROPERTY that returns the official product version (e.g. 2017).

I could do a case based on SERVERPROPERTY('ProductVersion'). The downside with that is just that it would not work for new versions of SQL Server (without modifications to the code).

**Comment by srutzky** [comment]
You could do the following, which works for all versions starting at SQL Server 2000 (not sure about prior versions):

```sql
SELECT CONVERT(INT,
               CONVERT(DECIMAL(5, 2),
                       SUBSTRING(CONVERT(NVARCHAR(50),
                                         SERVERPROPERTY('ProductVersion')),
                                 1,
                                 4)
                      ) * 10
              ) AS [FullVersion];
```

That will return the `INT` version number that is used by Microsoft in certain directory/folder names (e.g. `C:\Program Files\Microsoft SQL Server\120` ), compatibility levels, and some other places. The version numbers are:

* 80 = 2000
* 90 = 2005
* 100 = 2008
* 105 = 2008 R2
* 110 = 2012
* 120 = 2014
* 130 = 2016
* 140 = 2017
* 150 = 2019

This works across all of these versions thanks to `SUBSTRING` and then converting those first 4 characters into a numeric type. The first 5 characters of "ProductVersion" are as follows:

```none
8.00.
9.00.
10.00
10.50
11.0.
12.0.
13.0.
14.0.
15.0.
```

But we don't need the 2nd zero in "10.00" and "10.50", so chopping off the first 4 characters leaves us with:

```none
8.00
9.00
10.0
10.5
11.0
12.0
13.0
14.0
15.0
```

A more direct route is potentially doing:

```sql
SELECT [compatibility_level] FROM sys.databases WHERE [database_id] = 1;
```
BUT, that is not *guaranteed* to be accurate since it is possible to set any/all of the system DBs to a lower compatibility level (I just tried on 2019 and it did allow me to set `master`, `model`, `msdb`, and `tempdb` to a level of 100).

**Comment by dalekerr** [comment]
scroll down for Method 4 (CASE statement):
https://www.mssqltips.com/sqlservertip/1140/how-to-tell-what-sql-server-version-you-are-running/

**Comment by srutzky** [comment]
@dalekerr That CASE statement (in Method 4) is exactly what @olahallengren was referring to when he said:

> I could do a case based on SERVERPROPERTY('ProductVersion'). The downside with that is just that it would not work for new versions of SQL Server (without modifications to the code).

It would require updating this code / applying said update per each new version (well, at least one would need to make sure that all versions of SQL Server being backed up are covered, which won't require updates if newer versions are being used). I think using the INT value "90" through the current "150" (same as the compatibility level, and same as MS uses in the directory folder name of the shared portion of the install) is more durable choice as it is quite likely to continue working, without modification, across  newer versions.

On the other hand, using a CASE statement to translate any version identifier into the common name (e.g. "2017") is guaranteed to _not_ work for _any_ new version.

That being said, seeing the consistency of the first part of the string returned by `@@VERSION` (as shown in the mssqltips.com link in the comment directly above), it should be fairly reliable to use the following to get the "2005" / "2008" / "2008 R2" / etc version numbers:

```sql
SELECT SUBSTRING(@@VERSION, 22, PATINDEX(N'% [-(]%', @@VERSION) - 22);
```

And that will continue to get the correct value across future versions, so long as Microsoft remains consistent with that formatting (which it has been for 9 versions so far -- I just tested on 2019 CTP 2.1 and it works as expected).

**Comment by dalekerr** [comment]
Would rather 2008, or 2008R2 or 2008-R2 than 2008 R2. Don't want spaces in my paths.

`SELECT REPLACE(SUBSTRING(@@VERSION, 22, PATINDEX(N'% [-(]%', @@VERSION) - 22),' ','');`

**Comment by olahallengren** [comment]
Could I ask about the background for having the version number in the directory path?

**Comment by dalekerr** [comment]
Ideally the version parameter would be generated, hence generic reusable code:
>@directory          = N'\\backups\sqlserver',
>@directoryStructure = '{DatabaseVersion}{DirectorySeparator}{ServerName}${InstanceName}_{DatabaseName}_{BackupType}',

But what I actually have to do currently is hardcode for each version:
>@directory                = N'\\backups\sqlserver',
>@directoryStructure = '2012{DirectorySeparator}{ServerName}${InstanceName}_{DatabaseName}_{BackupType}',

>@directory                = N'\\backups\sqlserver',
>@directoryStructure = '2014{DirectorySeparator}{ServerName}${InstanceName}_{DatabaseName}_{BackupType}',

>@directory                = N'\\backups\sqlserver',
>@directoryStructure = '2016{DirectorySeparator}{ServerName}${InstanceName}_{DatabaseName}_{BackupType}',

>@directory                = N'\\backups\sqlserver',
>@directoryStructure = '2017{DirectorySeparator}{ServerName}${InstanceName}_{DatabaseName}_{BackupType}',

**Comment by olahallengren** [comment]
@srutzky, I think that SQL Server 2008 R2, uses 100, not 105.

On my computer the directory is "C:\Program Files\Microsoft SQL Server\100".

The compatibility level is 100.

**Comment by olahallengren** [comment]
@dalekerr, some more questions:

1. If we take a step back, why is it that you have have the requirement to have the version in the directory path? What is the benefit in your environment?

2. Would you use it, if I added a token for MajorVersion (e.g. 14)?

**Comment by dalekerr** [comment]
As mentioned, there is no 105 compatibility level, SQL 2008 and SQL 2008 R2 are both 100, although 2008 R2 is version 10.5.

1. We do disk backups to one large array and have hundreds of servers and databases, the version number helps to keep the backups in a logical order, be it by directory or subdirectory name. We tend to think of servers not merely by name, but by version and name.

2. I could make do with 14, 140 or 2017, preference for 2017 though. Be careful with MajorVersion as it was only introduced in or after Oct/Nov 2015 [2008 SP4-GDR, 2008 R2 SP3-GDR, 2012 SP2-CU9, 2014 RTM-CU10, 2014 SP1-CU3].

**Comment by olahallengren** [comment]
I am working on tokens for {MajorVersion} and {MinorVersion}.

You will be able to use them in directory names and file names, and combine them in different ways.

{MajorVersion}_{MinorVersion}
{MajorVersion}.{MinorVersion}
{MajorVersion}{MinorVersion}

I will be using SERVERPROPERTY('ProductMajorVersion') and SERVERPROPERTY('ProductMinorVersion'). I will extract it from SERVERPROPERTY('ProductVersion'), when the new properties are not available.

I will let you know when I have a test version ready.

So why no 2014, 2016, 2017 and so on? I want be sure that it is working in future versions of SQL Server. Then I prefer not to use ```@@VERSION```.

**Comment by olahallengren** [comment]
I have implemented this now in the branch [feature_version_tokens]. Please try it out.

**Comment by olahallengren** [comment]
This has now been released.

**Comment by dalekerr** [comment]
Thanks, appears to work without any problem so far. I now have my @DirectoryStructure set as

`{MajorVersion}{MinorVersion}{DirectorySeparator}{ServerName}${InstanceName}_{DatabaseName}_{BackupType}`

which now allows me to backup different sql versions to separate directories without having to hardcode a version string.
