### ISSUE TITLE
Option to prevent cleanup of latest backup

### ISSUE THREAD

**Issue by philcart** [olahallengren/sql-server-maintenance-solution#165]
Hi

Can an option be introduced to not remove a backup file if it's the latest backup?

We have a number of "Monthly" client extracts that are essentially data transferred from the main production database to client specific databases. The client specific databases are backed up and sent to clients for their own use. We keep the backup file so we can easily re-transmit to client if needed.

eg: 
msdb backup history has a latest backup at 1st Nov, 
Backup folder has 1st Nov file
Clean up option on Database Backup set to 48 hours
It's 26th Nov, but we still don't delete the file.

Cheers
Phil

**Comment by olahallengren** [comment]
By default DatabaseBackup will only do cleanup after a successful backup. This means that it will always keep the last good backup.
