### ISSUE TITLE
Index Maintenance Parameters not added to REBUILD scripts 

### ISSUE THREAD

**Issue by yusufbogatepe** [olahallengren/sql-server-maintenance-solution#168]
The procedure IndexMaintenance he execute with many parameters only executing with the "RESUMABLE = OFF" parameter. There are no other parameters added to the rebuild query. So i debugged and found out what the problem is. The script that you combine all the clauses is bugged. I changed the script with adding the COALESCE function and the problem is gone.

Thats the older query:

```
SELECT @CurrentAlterIndexWithClause = @CurrentAlterIndexWithClause + Argument + ', '
          FROM @CurrentAlterIndexWithClauseArguments
          ORDER BY ID ASC
          SET @CurrentAlterIndexWithClause = LEFT(@CurrentAlterIndexWithClause,LEN(@CurrentAlterIndexWithClause) - 1)
          IF EXISTS (SELECT * FROM @CurrentAlterIndexWithClauseArguments)
          BEGIN
            SET @CurrentAlterIndexWithClause = @CurrentAlterIndexWithClause + ')'
          END
		  
```
		  
		  
This is the new one:

```
SELECT@CurrentAlterIndexWithClause = COALESCE(@CurrentAlterIndexWithClause + ', ', '') + stringvalue
FROM @CurrentAlterIndexWithClauseArguments
ORDER BY ID ASC
SET @CurrentAlterIndexWithClause = LEFT(@CurrentAlterIndexWithClause,LEN(@CurrentAlterIndexWithClause) )
          IF EXISTS (SELECT * FROM @CurrentAlterIndexWithClauseArguments)
          BEGIN
            SET @CurrentAlterIndexWithClause = @CurrentAlterIndexWithClause + ')'
          END
 SET @CurrentAlterIndexWithClause = REPLACE( @CurrentAlterIndexWithClause,'(,','(') 
```

**Comment by yusufbogatepe** [comment]
> Today my colleague Ali was mentioned about a problem with your SQL Server Index Maintenance script.
> The procedure IndexMaintenance he execute with many parameters only executing with the "RESUMABLE = OFF" parameter. There are no other parameters added to the rebuild query. So i debugged and found out what the problem is. The script that you combine all the clauses is bugged. We changed the script with adding the COALESCE function and the problem is gone.
> 
> Thats the older query:
> 
> ```
> SELECT @CurrentAlterIndexWithClause = @CurrentAlterIndexWithClause + Argument + ', '
>           FROM @CurrentAlterIndexWithClauseArguments
>           ORDER BY ID ASC
>           SET @CurrentAlterIndexWithClause = LEFT(@CurrentAlterIndexWithClause,LEN(@CurrentAlterIndexWithClause) - 1)
>           IF EXISTS (SELECT * FROM @CurrentAlterIndexWithClauseArguments)
>           BEGIN
>             SET @CurrentAlterIndexWithClause = @CurrentAlterIndexWithClause + ')'
>           END
> 		  
> ```
> This is the new one:
> 
> ```
> SELECT@CurrentAlterIndexWithClause = COALESCE(@CurrentAlterIndexWithClause + ', ', '') + stringvalue
> FROM @CurrentAlterIndexWithClauseArguments
> ORDER BY ID ASC
> SET @CurrentAlterIndexWithClause = LEFT(@CurrentAlterIndexWithClause,LEN(@CurrentAlterIndexWithClause) )
>           IF EXISTS (SELECT * FROM @CurrentAlterIndexWithClauseArguments)
>           BEGIN
>             SET @CurrentAlterIndexWithClause = @CurrentAlterIndexWithClause + ')'
>           END
>  SET @CurrentAlterIndexWithClause = REPLACE( @CurrentAlterIndexWithClause,'(,','(') 
> ```

**Comment by olahallengren** [comment]
Could you share the command (with all the parameters) that you are executing to reproduce this issue, and also the output that you are getting.

**Comment by olahallengren** [comment]
Which version and edition is this? Could you please do a ```SELECT @@VERSION```

**Comment by olahallengren** [comment]
This issue has been fixed now.

**Comment by yusufbogatepe** [comment]
It works after the fix. 

Thanks for your quick response.
