### ISSUE TITLE
DBs with % in their name fail on RAISERROR stmt

### ISSUE THREAD

**Issue by MsMillerJane** [olahallengren/sql-server-maintenance-solution#169]
Hi Ola, 
Can you please add the middle line back into both IndexOptimize.sql and DatabaseIntegrityChaeck.sql:
    SET @DatabaseMessage = 'Database: ' + QUOTENAME(@CurrentDatabaseName)
    **SET @DatabaseMessage = REPLACE(@DatabaseMessage,'%','%%') + ' '**
    RAISERROR(@DatabaseMessage,10,1) WITH NOWAIT

Databases that contain % in the name will fail on RAISSERROR.
Older scripts from couple of years ago had it, adding back in solves the issue.
Thanks, 
Inga

**Comment by ConstantineK** [comment]
It looks like a find/replace for the following would probably do it, I will submit a quick PR but its pretty trivial to do - 
RAISERROR\((.*),(.*),(.*)\) WITH NOWAIT
RAISERROR('%s',$2,$3,$1) WITH NOWAIT

**Comment by olahallengren** [comment]
>Older scripts from couple of years ago had it, adding back in solves the issue.

This is an oversight from when I have been doing some refactoring. Thank you for catching this.

>Switching around all of these is probably going to be a pain, may I suggest instead using the optional argument parameter for this, then there doesnt even need to be any management of the error message output as far as I can tell

This looks like a very nice solution. Thank you.

**Comment by olahallengren** [comment]
This issue has been fixed now.
