### ISSUE TITLE
Index optimize SQL 2005 Failed Version: 2018-10-28 14:45:02

### ISSUE THREAD

**Issue by lmcoelho** [olahallengren/sql-server-maintenance-solution#175]
Hi the Index maintenance for sql server 2005, failed with the error

Error Number: 102
Error Message: Incorrect syntax near ')'.

The script produce this:

ALTER INDEX [IX1] ON [bdsql2005].[dbo].[TestTableSize] REBUILD WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON, MAXDOP = 1,)

And should produce

ALTER INDEX [IX1] ON [bdsql2005].[dbo].[TestTableSize] REBUILD WITH (SORT_IN_TEMPDB = OFF, ONLINE = ON, MAXDOP = 1)

**Comment by olahallengren** [comment]
This issue has been fixed. Thank you for reporting it.
