### ISSUE TITLE
Bug Report - Backup to URL doesn't work with case sensitive collation

### ISSUE THREAD

**Issue by OmegaMadLab** [olahallengren/sql-server-maintenance-solution#183]
While executing backup to URL on an instance with case sensitive collation, I receive the error:

_Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 1179 [Batch Start Line 0]
The value for the parameter @Credential is not supported._ 

I checked the parameter check at line 1184, and it fails becuase looks for a credential_identity = 'SHARED ACCESS SIGNATURE', while on my instance the credential is present with identity = 'Shared Access Signature'.

The starting statement is:
_EXECUTE dbo.DatabaseBackup
@Databases = 'ALL_DATABASES',
@URL = 'containerUrl',
@BlockSize = 65536,
@MaxTransferSize=4194304,
@BackupType = 'FULL',
@Compress = 'Y',
@Verify = 'Y',
@CleanupTime = NULL,
@CheckSum = 'Y',
@LogToTable = 'Y'_

Same statement on a case-insensitive instance is working fine; once credential_identity was corrected on the case-sensitive instance, the statement was executed correctly.

Created PR #182 to address this issue.

**Comment by olahallengren** [comment]
I have fixed this issue now. Thank you for reporting it.

**Comment by OmegaMadLab** [comment]
Many thanks to you, Ola. Your Maintenance Solution is a must for me :).
