### ISSUE TITLE
Backup to AWS S3 storage

### ISSUE THREAD

**Issue by navjyotnishant** [olahallengren/sql-server-maintenance-solution#184]
AWS S3 is being considered as a cost effective backup solution for databases in cloud.  We are looking for a way to take the MSSQL backup directly to S3. There are several third party applications available which gives you the functionality to mount S3 storage as a windows Drive thus existing Mintenance Backup script and job would work in that case. MSSQL yet doesnt support taking backup directly to S3 like it does with Azure blob storage. 
With current limitation between AWS & MSSQL is there a possibility that you integrate the functionality to copy the backup to S3 using default AWS CLI toolkit?
1. Take the backup to local/network path.
2. Once backup is completed copy them using AWS CLI S3 toolkit to S3 and clean them up upon successful copy?
[https://docs.aws.amazon.com/cli/latest/reference/s3/](https://docs.aws.amazon.com/cli/latest/reference/s3/)

**Comment by SQLHorizons** [comment]
@navjyotnishant, Are your SQL Servers on AWS EC2, if so using the servers IAM role you can use the AWS api to copy the local backups into your S3 bucket.  This is the approach we have adopted.

**Comment by alexsinkevich** [comment]
In SQL Server 2022 Microsoft finally created a way to backup directly to S3 bucket in AWS. 

Below is the document describing the steps: 
https://aws.amazon.com/blogs/modernizing-with-aws/backup-sql-server-to-amazon-s3/

The backup command syntax is similar, but slightly different from backup to URL, like so:
BACKUP DATABASE db1
TO URL = 's3://sql-backups-2022.s3.us-east-1.amazonaws.com/backups/db1.bak'
WITH FORMAT, COMPRESSION, MAXTRANSFERSIZE = 20971520;   

Is there a way to include this functionality into the solution? That would be a life changing modification, allowing AWS/SQL customers to save a ton of money by not keeping the volumes for the backups and not paying for them.

Please, Ola?

**Comment by Farshid1723** [comment]
For having ola hallengren backup solution work for s3 compatible storages like minio, a quick solution is to comment lines between 962 to 966 and 982 to 986. This will prevent URL format checking executed and then the SP would work for URLs beginning with "S3://" like amazon s3 storage buckets and/or any S3 compatible storage solutions like minio. below is the portion of backupdatabase SP that should be changed:

`
  ----------------------------------------------------------------------------------------------------
  --// Check URLs                                                                          //--
  ----------------------------------------------------------------------------------------------------

  --IF EXISTS(SELECT * FROM @URLs WHERE Mirror = 0 AND DirectoryPath NOT LIKE 'https://%/%')
  --BEGIN
  --  INSERT INTO @Errors ([Message], Severity, [State])
  --  SELECT 'The value for the parameter @URL is not supported.', 16, 1
  --END

  IF EXISTS (SELECT * FROM @URLs GROUP BY DirectoryPath HAVING COUNT(*) <> 1)
  BEGIN
    INSERT INTO @Errors ([Message], Severity, [State])
    SELECT 'The value for the parameter @URL is not supported.', 16, 2
  END

  IF (SELECT COUNT(*) FROM @URLs WHERE Mirror = 0) <> (SELECT COUNT(*) FROM @URLs WHERE Mirror = 1) AND (SELECT COUNT(*) FROM @URLs WHERE Mirror = 1) > 0
  BEGIN
    INSERT INTO @Errors ([Message], Severity, [State])
    SELECT 'The value for the parameter @URL is not supported.', 16, 3
  END

  ----------------------------------------------------------------------------------------------------

  --IF EXISTS(SELECT * FROM @URLs WHERE Mirror = 1 AND DirectoryPath NOT LIKE 'https://%/%')
  --BEGIN
  --  INSERT INTO @Errors ([Message], Severity, [State])
  --  SELECT 'The value for the parameter @MirrorURL is not supported.', 16, 1
  --END

  IF EXISTS (SELECT * FROM @URLs GROUP BY DirectoryPath HAVING COUNT(*) <> 1)
  BEGIN
    INSERT INTO @Errors ([Message], Severity, [State])
    SELECT 'The value for the parameter @MirrorURL is not supported.', 16, 2
  END

  IF (SELECT COUNT(*) FROM @URLs WHERE Mirror = 0) <> (SELECT COUNT(*) FROM @URLs WHERE Mirror = 1) AND (SELECT COUNT(*) FROM @URLs WHERE Mirror = 1) > 0
  BEGIN
    INSERT INTO @Errors ([Message], Severity, [State])
    SELECT 'The value for the parameter @MirrorURL is not supported.', 16, 3
  END
`
![2023-11-06_124811](https://github.com/olahallengren/sql-server-maintenance-solution/assets/9797194/75a9af49-9819-439c-8752-c55af2d5a911)

**Comment by olahallengren** [comment]
I am finally working on this.
I have created a pull request: https://github.com/olahallengren/sql-server-maintenance-solution/pull/822
Branch: https://github.com/olahallengren/sql-server-maintenance-solution/tree/feature-backup-aws-s3
Please do some testing.

**Comment by olahallengren** [comment]
This has been released to main now.
https://ola.hallengren.com/versions.html
