### ISSUE TITLE
The backup cannot be performed because 'ENCRYPTION' was requested...

### ISSUE THREAD

**Issue by mikepetrak** [olahallengren/sql-server-maintenance-solution#186]
**Description of the issue**
We are using the DatabaseBackup stored procedure version 2018-07-16 and sometimes we get the following error:
 
“The backup cannot be performed because 'ENCRYPTION' was requested after the media was formatted with an incompatible structure. To append to this media set, either omit 'ENCRYPTION' or create a new media set by using WITH FORMAT in your BACKUP statement. If you use WITH FORMAT on an existing media set, all its backup sets will be overwritten. BACKUP DATABASE is terminating abnormally.”
 
We read explanations about this error like the one at https://sqlperformance.com/2013/10/io-subsystem/native-backup-encryption , but we don’t think an initial backup is being created, and if it is, it would have to be within one second because you datetime stamp the backup files.
            “A Caveat One important note: you can't append encrypted backups. If you generate an encrypted backup file using WITH INIT, and then try to append another encrypted backup to the same file, you will receive this error”

This shouldn't be happening since the stored procedure is adding the timestamp (with seconds) in the file name.

We couldn’t find a FORMAT parameter at https://ola.hallengren.com/sql-server-backup.html , although I know Microsoft has one for the BACKUP command.
 
Do you have any plans on adding the Format parameter to DatabaseBackup?
 
**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor)

**Version of the script**
2018-07-16

**What command are you executing?**
[AdminDB].[dbo].[DatabaseBackup]
Parameters: @Databases = 'MyDatabase', @Directory = '\\MyServer\MyShare\', @BackupType = 'FULL', @Verify = 'N', @CleanupTime = NULL, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'N', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'N', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'Y', @EncryptionAlgorithm = 'AES_256', @ServerCertificate = 'FoundationBackupsCert', @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = NULL, @Credential = NULL, @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @AvailabilityGroupDirectoryStructure = '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'Y', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'N', @Execute = 'Y'
Version: 2018-07-16 18:32:21

**What output are you getting?**
Occasionally we are getting this: “The backup cannot be performed because 'ENCRYPTION' was requested after the media was formatted with an incompatible structure. To append to this media set, either omit 'ENCRYPTION' or create a new media set by using WITH FORMAT in your BACKUP statement. If you use WITH FORMAT on an existing media set, all its backup sets will be overwritten. BACKUP DATABASE is terminating abnormally.”

Thanks for your help!
Mike Petrak

**Comment by mikepetrak** [comment]
This error is only occurring from a custom web application that is calling the DatabaseBackup stored procedure, and not from our regular Ola SQL Server Agent backup jobs. We are working on troubleshooting it by adding @LogToTable = 'Y' in the custom web application.

**Comment by drstonephd** [comment]
Perhaps you can run a trace to insure it is run only once with the parameters expected?  Do you have error handling that would do a retry with the same file name?

**Comment by olahallengren** [comment]
I think that the only way that this could happen is if DatabaseBackup would get executed multiple times in the same second (as the second is part of the file name).

By adding @LogToTable = 'Y' we will be able to see all backup commands (including file names) that are executed.

Tracing the extended events module_start and module_end with a filter on the object_name would also be interesting.

**Comment by mikepetrak** [comment]
Thanks, @drstonephd . Yeah, @olahallengren and I have discussed tracing as well. Unfortunately in our situation, this occurs 0-4 times per day across about 100 servers and it's not consistent on the server where it errors, so I would have to run traces on all of them in hopes of catching the error. The application developer should put in LogToTable = 'Y' soon and I suspect that Ola is right with the execution of this procedure multiple times in the same second.

**Comment by drstonephd** [comment]
Is there any chance that two separate backups that start at the time would end up colliding on the share?  For example, two identical servers (e.g., a test copy of production), but in different domains?  Running both primary and secondary backups at the same time?

**Comment by olahallengren** [comment]
>The application developer should put in LogToTable = 'Y' soon and I suspect that Ola is right with the execution of this procedure multiple times in the same second.

One workaround could be to add a token for Millisecond to the file names (new feature in the latest version). However before doing that let's verify that this is what is happening.

**Comment by mikepetrak** [comment]
Thanks, @drstonephd . That's an interesting thought that could generate this error, but in our case I don't think it is very likely since it is only with production databases and we are following the default Ola Mainteanance Solution directory structure of \\Share\Cluster\Database. I should be able to get more details with LogToTable = 'Y' next week. Thanks.

**Comment by mikepetrak** [comment]
Hi @olahallengren,
[ResultsCommandLog.xlsx](https://github.com/olahallengren/sql-server-maintenance-solution/files/2809454/ResultsCommandLog.xlsx)
 

Our error hasn’t occurred since 1/14/19 but it just happened today.

Now that we added LogToTable = ‘Y’, we see that the second backup attempt within the same second causes the error, which is what we suspected. See the attached results. I anonymized the database, cluster, AG, and backup device names.

There are two sequential calls to DatabaseBackup in the application, but we believe they are blocking calls that wait until the procedure is done before continuing so it’s still sort of a mystery.

Let me know your thoughts.

Thank you!

**Comment by drstonephd** [comment]
Hi.  Perhaps you need a slower disk?  :)  The backup takes about .6 seconds.  I would expect two sequential backups of the same database to be in the same second perhaps 60% of the time, assuming that it was always this fast and starts at a random time.  I don't think Ola considered backing up the same database several times a second as a business requirement.  Is something you must do?  A quick workaround could be a sleep of .5 seconds between backups, assuming no repeated backup is faster than .5 seconds.  But I would seriously fixing the application to not allow the same backup too often.

**Comment by mikepetrak** [comment]
Thanks, @drstonephd . Yeah, for now we just added a 6 second delay between backups which should resolve the issue for 99% of the cases.

**Comment by olahallengren** [comment]
I was looking at the code.

The stored procedure is going through the databases in a while loop.

When it is starting working on a database, something of the first thing is does is to run this:

```SET @CurrentDate = GETDATE()```

The ```@CurrentDate``` variable is then used in the file name in the backup command.

So if you have two executions of the stored procedure, setting the variable for the same database, in the same second, then you have a problem.

**Comment by olahallengren** [comment]
I have a Millisecond token that you can use in the FileName.
https://ola.hallengren.com/sql-server-backup.html#FileName

If you add that you would reduce the risk of this happening by a factor 300 (as I am using GETDATE that has a 3 millisecond resolution).

**Comment by drstonephd** [comment]
My fastest backup (model in a loop) is 97 ms.  I can't get close getting two backups in a 3 ms window without going parallel.
