### ISSUE TITLE
DATA_DOMAIN_BOOST with no default File Extension?

### ISSUE THREAD

**Issue by samot1** [olahallengren/sql-server-maintenance-solution#198]
Is it correct, that there is neither an entry nor an ELSE condition for DATA_DOMAIN_BOOST in the " Get file extension" block, so that @FileExtensionFull / @FileExtensionDiff / @FileExtensionLog have always to be specified (otherwise NULL / no extension would be used)?

**Comment by olahallengren** [comment]
When you are backing up to DATA_DOMAIN_BOOST there are no files and thereby no file extensions.

You should not specify @FileExtensionFull, @FileExtensionDiff or @FileExtensionLog.
