### ISSUE TITLE
Issue with DatabaseBackup, parallel jobs with different backup locations

### ISSUE THREAD

**Issue by tbroady** [olahallengren/sql-server-maintenance-solution#202]
We were running out of space on our normal backup volume, so I changed one job out of 4 to use another drive. All 4 jobs have DatabaseInParallel = y, all parameters remained same , save for location. I have them starting on a 2 min stagger. (1800/1802/1804

When the jobs ran, the first job (the one changed location on)  proceeded to backup all databases to the new location, and was not operating in parallel with the other 3 jobs.

**Comment by olahallengren** [comment]
This is how the DatabaseInParallel feature works. All the jobs need to have identical parameters.

I understand your scenario, but I don't support that at the moment.

**Comment by olahallengren** [comment]
One solution could be to stripe all the backups across two drives.

**Comment by tbroady** [comment]
Ok. that's cool. if that's how it works that is good to know. It's a temp situation until we add space. Thanks for the reply :)
