### ISSUE TITLE
Ability to provide Backup Set Name

### ISSUE THREAD

**Issue by garyhampson** [olahallengren/sql-server-maintenance-solution#203]
**Description of the feature**
In DatabaseBackup, could you please provide the ability to give a database backup set name? 

BACKUP DATABASE [TestDB] TO  DISK = N'Z:\Backups\TestDB.bak' WITH NOFORMAT, NOINIT,  **NAME = N'TestDB-Full Database Backup - YYYY-MM-DD hh:mm:ss.mmm',** SKIP, NOREWIND, NOUNLOAD,  STATS = 10

**Comment by olahallengren** [comment]
Currently DatabaseBackup supports DESCRIPTION, but not NAME.

Could you describe how you would use it?

Should the name parameter support tokens (like the ```@FileName``` parameter)?
