### ISSUE TITLE
Backup Folder registry entry cannot handle multiple folders

### ISSUE THREAD

**Issue by RickyLively** [olahallengren/sql-server-maintenance-solution#205]
Trying to split our backups to different disks in different folders.

The thought was to change the BackupFolder registry value and have the backups stripe... unfortunately the multiple folders in the registry do not get split into individual paths.

**Comment by olahallengren** [comment]
You are right. The script does currently not have support for splitting the default backup directory.

**Comment by olahallengren** [comment]
The default backup directory is also used in SQL Server.

For example you can do a backup like this:
```BACKUP DATABASE model to disk = 'model.bak'```
It will go the default backup directory.

However SQL Server does not support a default backup directory that consists of multiple directories.

Msg 3201, Level 16, State 1, Line 3
Cannot open backup device 'C:\Backup,D:\Backup\model.bak'. Operating system error 123(The filename, directory name, or volume label syntax is incorrect.).
Msg 3013, Level 16, State 1, Line 3
BACKUP DATABASE is terminating abnormally.

Now given that SQL Server does not support this, I am not planning to support it in my script.
