### ISSUE TITLE
Simultaneously Backing up Databases with Data Domain 

### ISSUE THREAD

**Issue by TreyHawes** [olahallengren/sql-server-maintenance-solution#207]
I would like if sometime in one of your next releases you could allow the Data Domain process to use the new "DatabasesInParallel" option. Data Domain can backup multiple databases in parallel with out issues and would cut server backup times in half.

**Comment by umbio** [comment]
Hi TreyHawes, how do you realize multiple backups in parallel with DD? Is there an option in DDBoost plugin?

Regards,

**Comment by TreyHawes** [comment]
Hi Umbio, unfortunately, there is no option to do parallel backups with DD automatically that I am aware of, however, this can be done manually. 
Just grab the T-SQLs from the GUI or create your own for each database and run scripts simultaneously inside SSMS. I do this all the time with restores when I'm refreshing a Dev server. 
 
I'm sure this can be done with Ola's script as well, you would need to create two backup jobs, but each job would have a list of different databases to backup in the @Databases parameter, but I think this would make for a maintenance nightmare if you have allot of servers because if a new database is added to a server, the script would need to be changed as well. Or perhaps you could backup each database based upon their database IDs, then one job could handle all of the odd databases and the other all the even ones, but I think this is only good if the all the database are about the same size.

It seems with Ola's Queue tables, the backup jobs pick the next available database to backup which in my opinion is a better solution, so I'm hoping for that one. :)

**Comment by olahallengren** [comment]
Could you try creating two identical jobs with ```@BackupSoftware = 'DATA_DOMAIN_BOOST'``` and ```@DatabasesInParallel = 'Y'```.

**Comment by TreyHawes** [comment]
Hi, it works perfectly! Thank you for doing this.

**Comment by olahallengren** [comment]
I am happy that you got it working.
