### ISSUE TITLE
BackupDirectory is ignored

### ISSUE THREAD

**Issue by pven** [olahallengren/sql-server-maintenance-solution#214]
I justed started (again, new customer) with those beautiful scripts. Thanks for that!

In the big bang script I filled in this:
```
SET @BackupDirectory     = '\\backup003\sqlbackup003\databases\INSTANCE01\pven_ola_test'
```

But when I run this:
```
EXECUTE dbo.DatabaseBackup
@Databases = 'pven',
@BackupType = 'FULL',
@Verify = 'Y'
```
It looks like that backupdirectory is ignored, since the backups are written to the default backup-directory (in new sub-directories).

Did I miss some configuration?

Btw: I am using this version:
```
  ----------------------------------------------------------------------------------------------------
  --// Source:  https://ola.hallengren.com                                                        //--
  --// License: https://ola.hallengren.com/license.html                                           //--
  --// GitHub:  https://github.com/olahallengren/sql-server-maintenance-solution                  //--
  --// Version: 2019-02-10 10:40:47                                                               //--
  ----------------------------------------------------------------------------------------------------
```

**Comment by olahallengren** [comment]
When you run MaintenanceSolution.sql and set the ```@BackupDirectory``` in the top of the script, what happens is that the directory is added as a parameter in the jobs.

When you are executing dbo.DatabaseBackup in SSMS, without specifying the ```@Directory``` parameter, then then default backup directory is used.

**Comment by pven** [comment]
Clear, thanks!
