### ISSUE TITLE
fn_hadr_backup_is_preferred_replica issue

### ISSUE THREAD

**Issue by Cedric-Diau** [olahallengren/sql-server-maintenance-solution#216]
Backup on AlwaysON without WSFC:
We are testing AlwaysOn without Windows Server Failover Clustering.
The backup return an error because the function fn_hadr_backup_is_preferred_replica is not yet compatible with this mode.
https://feedback.azure.com/forums/908035-sql-server/suggestions/32899291-fn-hadr-backup-is-preferred-replica-fails-for-clus

Issue:
SELECT sys.fn_hadr_backup_is_preferred_replica('XXXXXXXX')
Msg 35222, Level 16, State 0, Line 45
Could not process the operation. Always On Availability Groups does not have permissions to access the Windows Server Failover Clustering (WSFC) cluster.  Disable and re-enable Always On Availability Groups by using the SQL Server Configuration Manager. Then, restart the SQL Server service, and retry the currently operation. For information about how to enable and disable Always On Availability Groups, see SQL Server Books Online.

To avoid this issue I changed the procedure DatabaseBackup (version 2018-07-16 ) as follow:
135: DECLARE @CurrentIsPreferredBackupReplica bit 
--->  DECLARE @CurrentIsPreferredBackupReplica nvarchar(max)

1726: SELECT @CurrentIsPreferredBackupReplica = sys.fn_hadr_backup_is_preferred_replica(@CurrentDatabaseName)
--->    SELECT @CurrentIsPreferredBackupReplica = @CurrentAvailabilityGroupBackupPreference

1852: SET @DatabaseMessage = 'Is preferred backup replica: ' + CASE WHEN @CurrentIsPreferredBackupReplica = 1 THEN 'Yes' WHEN @CurrentIsPreferredBackupReplica = 0  THEN 'No' ELSE 'N/A' END
--->    SET @DatabaseMessage = 'Is preferred backup replica: ' + CASE WHEN @CurrentIsPreferredBackupReplica IS NOT NULL THEN 'Yes' WHEN @CurrentIsPreferredBackupReplica IS NULL  THEN 'No' ELSE 'N/A' END

1906: AND NOT (@CurrentAvailabilityGroup IS NOT NULL AND @CurrentBackupType = 'LOG' AND @CopyOnly = 'N' AND (@CurrentIsPreferredBackupReplica <> 1 OR @CurrentIsPreferredBackupReplica IS NULL) AND @OverrideBackupPreference = 'N')
--->    AND NOT (@CurrentAvailabilityGroup IS NOT NULL AND @CurrentBackupType = 'LOG' AND @CopyOnly = 'N' AND (@CurrentIsPreferredBackupReplica IS NULL) AND @OverrideBackupPreference = 'N')

I opened a Feature instead of Bug because this issue seem to come from Microsoft side but it has been going on for a long time.
So is it possible to have a workaround?

**Comment by olahallengren** [comment]
Is this still an issue in the latest CU for SQL Server 2017?

Do you have an open support case with Microsoft?

**Comment by NickCraver** [comment]
Heads up: another break related to `sys.fn_hadr_backup_is_preferred_replica` is in SQL 2017 CU 15. It's now documented in [KB4498951](https://support.microsoft.com/en-us/help/4498951/cumulative-update-15-for-sql-server-2017#avail):


## Availability Group preferred replica backups
**IMPORTANT**

Consider the following scenario:

-   You are running an Availability Group on a Windows Server failover cluster.
-   You are using the  **sys.fn_hadr_backup_is_preferred_replica**  function within your backup jobs to determine whether to run a backup on the current replica.

In this scenario, the function call fails and generates the following error message:

Msg 41070, Level 16, State 1, Line 1  
> Configuration data for the availability group with Windows Server Failover Clustering (WSFC) resource ID `'<resource ID>'` is not found in the WSFC data store. The availability group may have been dropped, or a previous CREATE AVAILABILITY GROUP or DROP AVAILABILITY GROUP operation has failed. Please use DROP AVAILABILITY GROUP command to clean up previously failed operations before retrying the current operation.

  
This issue does not affect the backup itself. Therefore, you can work around this issue by removing the call to  **sys.fn_hadr_backup_is_preferred_replica**.

If you have to back up only on the preferred replica, we recommended that you do not apply Cumulative Update 15. This issue will be fixed in a future release.

**Comment by Cedric-Diau** [comment]
Thanks for the news.
I tested the 4 options of the Availability Group Backup preferences (without underline cluster):
**Primary
Secondary only
Prefer Secondary
Any Replica**

--------------------------------------------------------------------------------------------------------------

- [ ] Primary Node

- Primary

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 0                           primary

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

-----
1

(1 row affected)
```

- Secondary only

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 1                           secondary_only

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

Msg 35222, Level 16, State 0, Line 45
Could not process the operation. Always On Availability Groups does not have permissions to access the Windows Server Failover Clustering (WSFC) cluster.  Disable and re-enable Always On Availability Groups by using the SQL Server Configuration Manager. Then, restart the SQL Server service, and retry the currently operation. For information about how to enable and disable Always On Availability Groups, see SQL Server Books Online.
```

- Prefer Secondary

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 2                           secondary

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

Msg 35222, Level 16, State 0, Line 45
Could not process the operation. Always On Availability Groups does not have permissions to access the Windows Server Failover Clustering (WSFC) cluster.  Disable and re-enable Always On Availability Groups by using the SQL Server Configuration Manager. Then, restart the SQL Server service, and retry the currently operation. For information about how to enable and disable Always On Availability Groups, see SQL Server Books Online.
```

- Any Replica

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 3                           none

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

-----
1

(1 row affected)
```
--------------------------------------------------------------------------------------------------------------

- [ ] Secondary Node

- Primary

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 0                           primary

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

-----
0

(1 row affected)
```

- Secondary only

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 1                           secondary_only

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

Msg 35222, Level 16, State 0, Line 45
Could not process the operation. Always On Availability Groups does not have permissions to access the Windows Server Failover Clustering (WSFC) cluster.  Disable and re-enable Always On Availability Groups by using the SQL Server Configuration Manager. Then, restart the SQL Server service, and retry the currently operation. For information about how to enable and disable Always On Availability Groups, see SQL Server Books Online.
```

- Prefer Secondary

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 2                           secondary

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

Msg 35222, Level 16, State 0, Line 45
Could not process the operation. Always On Availability Groups does not have permissions to access the Windows Server Failover Clustering (WSFC) cluster.  Disable and re-enable Always On Availability Groups by using the SQL Server Configuration Manager. Then, restart the SQL Server service, and retry the currently operation. For information about how to enable and disable Always On Availability Groups, see SQL Server Books Online.
```

- Any Replica

```
SELECT Name AS AGname,
       cluster_type,
       cluster_type_desc,
       automated_backup_preference,
       automated_backup_preference_desc
FROM sys.availability_groups
go

AGname           cluster_type cluster_type_desc    automated_backup_preference automated_backup_preference_desc
---------------- ------------ -------------------- --------------------------- ------------------------------------------------------------
PPRADBAG01       1            none                 3                           none

(1 row affected)

SELECT sys.fn_hadr_backup_is_preferred_replica('TESTADB05')
go

-----
0

(1 row affected)
```

--------------------------------------------------------------------------------------------------------------

It works “fine” on both nodes only for the Primary option.  For the Any Replica choice it seems not allowed to back up on secondary node?

**Comment by olahallengren** [comment]
Microsoft is working on a fix for the issue in CU15.
https://support.microsoft.com/en-us/help/4498951/cumulative-update-15-for-sql-server-2017#avail

When it comes to the issue with sys.fn_hadr_backup_is_preferred_replica on clusterless availability groups, is that still an issue in the latest CU?

**Comment by Cedric-Diau** [comment]
I installed the CU15 and it works fine, no more error.

**Comment by olahallengren** [comment]
@Cedric-Diau, thank you for confirming.

Then we are just waiting for Microsoft to fix the latest issue. Hopefully that will be fixed in the next CU.

**Comment by olahallengren** [comment]
@Cedric-Diau, could you also write a comment on the User Voice item.

**Comment by Cedric-Diau** [comment]
@olahallengren, Sorry but where is the User Voice item ?

**Comment by olahallengren** [comment]
I mean this one:
https://feedback.azure.com/forums/908035-sql-server/suggestions/32899291-fn-hadr-backup-is-preferred-replica-fails-for-clus

**Comment by olahallengren** [comment]
The fix in CU15 had a regression and got rolled back in CU16. In CU17 it finally got fixed.
https://support.microsoft.com/en-us/help/4502442/fix-sys-fn-hadr-backup-is-preferred-replica-causes-error-41005-in-sql
