### ISSUE TITLE
AvailabilityGroup awareness with IndexMaintenance if databases explicitly listed?

### ISSUE THREAD

**Issue by MasterChiefmas** [olahallengren/sql-server-maintenance-solution#218]
I've seen somewhere notes that say the IndexMaintenance is aware of Availability Groups and won't touch secondary replicas when specifying the AVAILABILITY_GROUP_DATABASES as the target. 

If I specify a single or list of databases that are in an AG, will the script still figure that out and skip the secondaries?

Thank you!

**Comment by olahallengren** [comment]
IndexOptimize will always skip secondary replicas (regardless of how you are selecting them).
