### ISSUE TITLE
Database integrity check - optional parameter to skip data_purity

### ISSUE THREAD

**Issue by jean-pierre-de-jong** [olahallengren/sql-server-maintenance-solution#219]
Hi,

Can you please add a parameter to Database Integrity Check to skip data_purity so it performs a regular DBCC CHECKDB. Currently I can choose between 'physical only' or 'data_purity'. 

Thank you!

**Comment by olahallengren** [comment]
Paul Randal has some good information about this.

"For databases created on SQL 2005 onwards, these checks are always performed by DBCC CHECKDB and cannot be turned off."

"Well, for an upgraded database, if the WITH DATA_PURITY option is used and no problems are found, a bit is irrevocably flipped in the boot page and from that point onwards the data purity checks will be performed on the database whenever DBCC CHECKDB runs."

https://www.sqlskills.com/blogs/paul/checkdb-from-every-angle-how-to-tell-if-data-purity-checks-will-be-run/

"For databases upgraded from earlier versions of SQL Server, column-value checks are not enabled by default until DBCC CHECKDB WITH DATA_PURITY has been run error free on the database. After this, DBCC CHECKDB checks column-value integrity by default."
https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-checkdb-transact-sql

Here is a summary:

- The database was created on SQL Server 2005 or later: Data purity is always checked when you do a regular DBCC CHECKDB

- The database was created on SQL Server 2000 or earlier and you have performed one successful DBCC CHECKDB WITH DATA_PURITY: Data purity is always checked when you do a regular DBCC CHECKDB

- The database was created on SQL Server 2000 or earlier and you have never performed a successful DBCC CHECKDB WITH DATA_PURITY: Data purity is not checked when you do a regular DBCC CHECKDB

When I implemented this, I was thinking that in the first two cases it does not cost anything to specify WITH DATA_PURITY. In the third case, it is good to get to know about it, if you have "value is out of range for data type" - issues.

Could you describe your scenario and give some background for this request?
