### ISSUE TITLE
Integrity Check - Job Failures due to Deadlocks

### ISSUE THREAD

**Issue by CubsRep** [olahallengren/sql-server-maintenance-solution#220]
**Description of the issue**
On occasional basis, we are encountering Integrity check job failures due to deadlocks when running in parallel. There are 3 USER DB jobs created with below parameters scheduled at same time
```sql
Parameters: @Databases = 'USER_DATABASES,-DBA', @CheckCommands = 'CHECKDB', @PhysicalOnly = 'Y', @NoIndex = 'N', @ExtendedLogicalChecks = 'N', @TabLock = 'N', @FileGroups = NULL, @Objects = NULL, @MaxDOP = NULL, @AvailabilityGroups = NULL, @AvailabilityGroupReplicas = 'PREFERRED_BACKUP_REPLICA', @Updateability = 'ALL', @TimeLimit = NULL, @LockTimeout = 900, @LockMessageSeverity = 16, @DatabaseOrder = 'DATABASE_SIZE_DESC', @DatabasesInParallel = 'Y', @LogToTable = 'Y', @Execute = 'Y'
```

Pulled deadlock report from **system_health** event session and embedded. The resource it is waiting and failing is "[dbo].[Queue]"

**SQL Server version and edition**
Microsoft SQL Server 2008 R2 (SP3-OD) (KB3144114) - 10.50.6542.0 (X64)   Feb 22 2016 18:07:23   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

**Version of the script**

  --// Source:  https://ola.hallengren.com                                                        //--
  --// License: https://ola.hallengren.com/license.html                                           //--
  --// GitHub:  https://github.com/olahallengren/sql-server-maintenance-solution                  //--
  --// Version: 2019-02-10 10:40:47                                                               //--

**What command are you executing?**
[dbo].[DatabaseIntegrityCheck]

**What output are you getting?**
*** [DatabaseIntegrityCheck], Line 1164. Errno 50000: Msg 1205, Transaction (Process ID 106) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
```xml
<event name="xml_deadlock_report" package="sqlserver" id="123" version="1" timestamp="2019-04-28T10:59:52.165Z">
  <data name="xml_report">
    <type name="unicode_string" package="package0" />
    <value><deadlock>;
 <victim-list>;
  <victimProcess id="process2deca3b88"/>;
 </victim-list>;
  
 <resource-list>;
  <objectlock lockPartition="0" objid="834102012" subresource="FULL" dbid="5" objectname="" id="lock1b392d700" mode="S" associatedObjectId="834102012">;
   <owner-list>;
    <owner id="process12ced4508" mode="S"/>;
   </owner-list>;
   <waiter-list>;
    <waiter id="process2deca3b88" mode="X" requestType="convert"/>;
   </waiter-list>;
  </objectlock>;
  <objectlock lockPartition="0" objid="834102012" subresource="FULL" dbid="5" objectname="" id="lock1b392d700" mode="S" associatedObjectId="834102012">;
   <owner-list>;
    <owner id="process2deca3b88" mode="S"/>;
   </owner-list>;
   <waiter-list>;
    <waiter id="process12ced4508" mode="X" requestType="convert"/>;
   </waiter-list>;
  </objectlock>;
 </resource-list>;
</deadlock>;
</value>
    <text />
  </data>
</event>
```

**Comment by CubsRep** [comment]
Now I see deadlocks causing failures even with `@LockMessageSeverity = 10` for both **IndexOptimize** and **IntegrityCheck** jobs. It's happening only on **SQL2008/2008R2** version instances for now at least.

**Comment by olahallengren** [comment]
Thank you for reporting this. The locking around the databases in parallel feature is rather complicated.
There should not be any deadlocks, one database should only be worked on by one job, no databases should be missed and so on. I did a lot of testing on this, and I thought that I got it right, but apparently I have missed something. I will try to reproduce it and fix it.

It is by design that ```@LockMessageSeverity = 10``` does not work at this place in the code.

**Comment by CubsRep** [comment]
I see a pattern - whenever we update the Procedure parameters, at the first run, deadlocks are more often due to implicit conversion. Subsequent runs are smooth I'd say they are gone. We haven't seen any deadlock errors in last 3 days as there are no parameter updates happened in the period. it makes sense as there isn't nothing to `INSERT` and using last `QueueId`

Wondering - Table `Queue` column datatypes, especially `SYSNAME` are causing implict conversion. May be changing to `NVARCHAR` would be a permanent resolve

**Comment by srutzky** [comment]
Hi @CubsRep :

> ... deadlocks are more often due to implicit conversion. ...   
>  ...   
> Testing - `Queue` table column datatypes, convert `sysname` to `nvarchar` to avoid implict conversion   

I'm pretty sure that implicit conversions do not cause deadlocks. I don't see how they could since they don't take out locks. If you are basing this on the `requestType="convert"` in the deadlock XML, then I am again pretty sure that is referring to converting the shared lock (`S`) into an exclusive lock (`X`), which is what each session is attempting to do. Now, the `INSERT` operation you mentioned _would_ require an exclusive lock, so perhaps two sessions are attempting to insert at the same time.

Also, `sysname` is merely an alias for `NVARCHAR(128)`, so there is no implicit conversion happening there.

**Comment by olahallengren** [comment]
I am not able to reproduce this issue.

@CubsRep, if you can reproduce it, could you try changing from
```FROM dbo.[Queue] WITH (UPDLOCK, TABLOCK)```
to
```FROM dbo.[Queue] WITH (UPDLOCK, HOLDLOCK, TABLOCK)```

**Comment by olahallengren** [comment]
I have reproduced this issue and released a fix.
https://ola.hallengren.com/versions.html

**Comment by CubsRep** [comment]
Awesome. Thanks Ola !
