### ISSUE TITLE
Error Message column in CommandLog table shows Null at failures

### ISSUE THREAD

**Issue by CubsRep** [olahallengren/sql-server-maintenance-solution#222]
**Description of the issue**
ErrorMessage and ErrorNumber columns in the dbo.CommandLog table are not populating with right Error # and message at failures. **IndexOptimize** job failing on particular database with error:
>Could not allocate space for object 'sys.sysobjvalues'.'clst' in database '' because the 'PRIMARY' filegroup is full. Create disk space by deleting unneeded files, dropping objects in the filegroup,

This message is not being logged in the table. Showings as NULL

**SQL Server version and edition**
```Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64)   Jul 21 2018 07:47:45   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Home 10.0 <X64> (Build 17763: ) ```

**Version of the script**
--// Source: https://ola.hallengren.com //--
--// License: https://ola.hallengren.com/license.html //--
--// GitHub: https://github.com/olahallengren/sql-server-maintenance-solution //--
--// Version: 2019-02-10 10:40:47 //--

**What command are you executing?**
```[dbo].[IndexOptimize]```
```sql
@Databases = 'USER_DATABASES,-DBA', @FragmentationLow = NULL, @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationLevel1 = 25, @FragmentationLevel2 = 75, @MinNumberOfPages = 1000, @MaxNumberOfPages = NULL, @SortInTempdb = 'N', @MaxDOP = NULL, @FillFactor = NULL, @PadIndex = NULL, @LOBCompaction = 'Y', @UpdateStatistics = 'INDEX', @OnlyModifiedStatistics = 'Y', @StatisticsModificationLevel = NULL, @StatisticsSample = 95, @StatisticsResample = 'N', @PartitionLevel = 'Y', @MSShippedObjects = 'N', @Indexes = 'ALL_INDEXES', @TimeLimit = NULL, @Delay = NULL, @WaitAtLowPriorityMaxDuration = NULL, @WaitAtLowPriorityAbortAfterWait = NULL, @Resumable = 'N', @AvailabilityGroups = NULL, @LockTimeout = 900, @LockMessageSeverity = 16, @DatabaseOrder = 'DATABASE_SIZE_DESC', @DatabasesInParallel = 'Y', @LogToTable = 'Y', @Execute = 'Y'
```

**What output are you getting?**
At failures, I'm going to job output file (.log) rather than querying the command log table to check for error details.

**Comment by olahallengren** [comment]
Could you copy the rows from CommandExecute into Excel (with headers) and attach it to the issue (or send it to me by e-mail if you prefer that).

**Comment by CubsRep** [comment]
@olahallengren - Sent you in an email

**Comment by CubsRep** [comment]
Also it's worth mentioning, actual procedures are being called from a wrapper procedure (different schema) within a TRY/CATCH. Check the gist [Wrapper Logic](https://gist.github.com/CubsRep/83e2a32517134a59070f6ed23b35ee93)

**Comment by olahallengren** [comment]
I have reproduced this issue. It happens when you execute the stored procedure in a TRY block.

It will then not do the completing logging after an error (output to text or to the log - table). It will also abort the execution after an error (not proceeding to the next index).

**Comment by CubsRep** [comment]
Ok. Let me modify the wrapper proc by removing TRY CATCH and see

**Comment by CubsRep** [comment]
@olahallengren - No I haven't got chance to test this yet. Will update as soon as I rolled to systems
