### ISSUE TITLE
Check catalogue failures on external table references

### ISSUE THREAD

**Issue by haymansfield** [olahallengren/sql-server-maintenance-solution#224]
We are currently running the following command against a database with external table references:

[dbo].[DatabaseIntegrityCheck] @Databases = 'xxxxx', @CheckCommands = 'CHECKDB', @LogToTable = 'Y'

We receive entries for the external table references such as:

Check Catalog Msg 3854, State 1: Attribute (objid=xxxxxxx) of row (class=0,objid=xxxxxxxx,indexid=0,rowsetnum=1) in sys.sysrowsetrefs (type=ET) has a matching row (object_id=xxxxxxxx) in sys.objects that is invalid.

As I understand it these errors are expected.

Is there a way of suppressing these errors or running an integrity check which will not inspect the external references?

Thanks

**Comment by olahallengren** [comment]
Which version of SQL Server is this?

**Comment by haymansfield** [comment]
This is an Azure SQL database.

**Comment by olahallengren** [comment]
I don't have a way to suppress this in DatabaseIntegrityCheck.

Maybe you could suggest that SQL Server only do this check as a part of EXTENDED_LOGICAL_CHECKS?
