### ISSUE TITLE
DatabaseBackup: Directory parameter, MinorVersion token

### ISSUE THREAD

**Issue by dalekerr** [olahallengren/sql-server-maintenance-solution#225]
Could you make the MinorVersion always one decimal place only (either 0 or 5 rather than 00 or 50)? 

{MajorVersion}{MinorVersion} returns 900 for SQL 2005 rather than 90 and 1050 for SQL 2008 R2 rather than 105. Thus older versions appear last in a directory structure when they should appear first (see image).

![ola-backup](https://user-images.githubusercontent.com/16471882/57212293-986f2600-7026-11e9-9526-74a31571d70b.JPG)

**Comment by olahallengren** [comment]
In SQL Server 2008 R2 a version number looks like this: 10.50.6560.0
In SQL Server 2017 a version number looks like this: 14.0.3076.1

Therefore I am using 50 as the MinorVersion for SQL Server 2008 R2.
