### ISSUE TITLE
Permissions issue with CHECKTABLE on Azure Sql database

### ISSUE THREAD

**Issue by haymansfield** [olahallengren/sql-server-maintenance-solution#226]
Attempting to run an integrity check check is running into permissions issues unless I use @TabLock = 'Y'. With TabLock it works fine. My user is a member of the fixed db_owner role.

My naive assumption on looking at the DBCC documentation is that the user is unable to create a snapshot it requires to run it's checks.

**SQL Server version and edition**
Microsoft SQL Azure (RTM) - 12.0.2000.8   Apr  3 2019 13:27:00   Copyright (C) 2019 Microsoft Corporation 

**Version of the script**
2019-02-10 10:40:47 

**What command are you executing?**
[dbo].[DatabaseIntegrityCheck] @Databases = '<db>', @CheckCommands = 'CHECKTABLE', @TimeLimit = 28800, @LockTimeout = 60, @LogToTable = 'Y'

**What output are you getting?**
Command failed: The server principal "<user>" is not able to access the database "<db>" under the current security context. (Msg 916, Level 14, State 2, Line 1).

**Comment by olahallengren** [comment]
Thank you for reporting this. Could I ask you to try to execute the DBCC CHECKTABLE command outside of my stored procedure?

**Comment by olahallengren** [comment]
I have been doing some testing on this, and for me it works fine.

```
EXECUTE [dbo].[DatabaseIntegrityCheck] @databases = 'USER_DATABASES', @CheckCommands = 'CHECKTABLE', @Timelimit = 28800, @LockTimeout = 60, @LogToTable = 'Y'

EXECUTE [dbo].[DatabaseIntegrityCheck] @databases = 'USER_DATABASES', @CheckCommands = 'CHECKTABLE', @Timelimit = 28800, @LockTimeout = 60, @TabLock = 'Y', @LogToTable = 'Y'
```

Could you test again?
