### ISSUE TITLE
Calculate the number of files dynamically based on the database size

### ISSUE THREAD

**Issue by chadwestes** [olahallengren/sql-server-maintenance-solution#227]
Add feature to enable a dynamic number of files based upon database size.

Many companies are moving database backups to AWS S3 storage, but are running into issues with larger databases; namely a max file size limitation imposed by AWS.  This can be sidestepped if you supply a value for the @NumberOfFiles parameter, but unless you want to create multiple jobs for each database and constantly adjust the number, you will end up with lots of files that are very small.  I suggest a parameter that would serve as a threshold for when to split a database backup into multiple files.  
Say you had a 75 GB, 100 GB, and 300 GB database on a server along with several databases less than 5 GB.  You could supply a value of 50 GB to this new parameter and the backup script would then backup each of the < 5GB databases into 1 file each, break the 75 GB and 100 GB files into 2 files each and the 300 GB database into 6 files.

**Comment by Lfremondiere** [comment]
Congratulations! We waited for this new and you did it.
However, the NumberOfFiles and FileNumber tokens disappear when there is only one file. This is very annoying in a production system with automatic database restore on the dev based on a template.

**Comment by chadwestes** [comment]
Lfemondiere, check the latest commit I just made.  I added an extra parameter, @DropTokensWhenNA, to indicate whether you want to retain ('N') or drop ('Y') the {FileNumber} and {NumberOfFiles} tokens from the filename when only one file is required.  This should address your concern.  Also the default value is set to 'N' so no additional action other than updating your copy of the SP are needed.

**Comment by Lfremondiere** [comment]
Greats! Thanks chadwestes !

**Comment by olahallengren** [comment]
Is it the 5 TB limitation that you are running into?
https://www.amazonaws.cn/en/s3/faqs/

**Comment by olahallengren** [comment]
I was thinking about a few scenarios:

1. What if you specify both @NumberOfFiles and @DatabaseSizeSplit at the same time?

2. What if you specify a @DatabaseSizeSplit that results in that you reach the maximum number of files (e.g. 64 for native backups)?

**Comment by chadwestes** [comment]
@olahallengren both of the above referenced scenarios are already accounted for.  For #1 see line 2009 in my code which acts as a flow control mechanism.  If the NumberOfFiles is already set it does not undertake the action of calculating the number of files needed according to the split size.  As for #2, please reference line 2015 in my code which throws an error if the number of files exceeds 64.  I suppose this could just as easily set the number of files to 64, but that would increase the file size past the value specified by the splitsize variable.  My thought was if they are using this parameter they most likely want files of that specified size and should be notified via error message that it is not possible.

**Comment by olahallengren** [comment]
>As for item 2 above, please reference line 2015 in my code which throws an error if the number of files exceeds 64. I suppose this could just as easily set the number of files to 64, but that would increase the file size past the value specified by the splitsize variable. My thought was if they are using this parameter they most likely want files of that specified size and should be notified via error message that it is not possible.

@chadwestes, one thing to consider is that most users are using backup compression. This means that when you specify a file size using @DatabaseSizeSplit, the actual file size is likely to be smaller. So from this point of view it could make sense to set the number of files to 64 in this case.

**Comment by chadwestes** [comment]
@olahallengren good suggestion.  I have implemented that change.

**Comment by olahallengren** [comment]
@chadwestes, could you elaborate on what the size limits are in AWS S3?

**Comment by chadwestes** [comment]
@olahallengren,
At the time that I wrote this issue, we were experiencing failures for any files over 5GB in size. I believe we have since worked around this issue, by configuring something differently, but that is out of my realm of expertise.  As shown on AWS's FAQ:

`Q:     How much data can I store in Amazon S3?

The total volume of data and number of objects you can store are unlimited. Individual Amazon S3 objects can range in size from a minimum of 0 bytes to a maximum of 5 terabytes. **The largest object that can be uploaded in a single PUT is 5 gigabytes.** For objects larger than 100 megabytes, customers should consider using the Multipart Upload capability.`

It would seem we did not have Multipart Upload capability turned on/configured correctly.  But I still see some utility in having this feature available.

**Comment by olahallengren** [comment]
Thank you, @chadwestes.

This feature is is very interesting. There is another issue that is a bit similar.
https://github.com/olahallengren/sql-server-maintenance-solution/issues/100

**Comment by stoycqs** [comment]
@olahallengren This feature is very useful.
Is it possible to be added to the main branch?

**Comment by chadwestes** [comment]
> Thank you, @chadwestes.
> 
> This feature is very interesting. There is another issue that is a bit similar.
> #100

I saw this issue and I can follow what they want, but I'm curious as to the why behind their approach.  Why binning over a more uniform method of splitting the files like I have here.  I will follow up with them.

**Comment by chadwestes** [comment]
> @olahallengren This feature is very useful.
> Is it possible to be added to the main branch?

I would very much like to see Ola add this to the main branch, as we still have some issues with our larger databases reporting backup failures due to "The operating system returned the error '59(An unexpected network error occurred.)' while attempting 'SetEndOfFile' on *.bak" even though the backup succeeds.  We spend a considerable amount of time double checking backups that have no issues.  This fix would allow us to use smaller files to circumvent these errors, but I am hesitant to be running my own fork on our production systems.  I would much prefer to be running the main branch so that future updates would not necessitate rewriting the code each time.

**Comment by olahallengren** [comment]
> I would very much like to see Ola add this to the main branch, as we still have some issues with our larger databases reporting backup failures due to "The operating system returned the error '59(An unexpected network error occurred.)' while attempting 'SetEndOfFile' on *.bak" even though the backup succeeds. We spend a considerable amount of time double checking backups that have no issues. This fix would allow us to use smaller files to circumvent these errors, but I am hesitant to be running my own fork on our production systems. I would much prefer to be running the main branch so that future updates would not necessitate rewriting the code each time.

@chadwestes, is this issue when you are backing up to AWS S3 storage? Have you tested that striping the backups will reduce the risk of getting this error?

**Comment by chadwestes** [comment]
Yes, this only occurs while backing up to AWS S3. It has only been tested
on a few of our servers; the lower environment ones that were giving us
this error most frequently, and striping has stopped it from occurring on
those servers. Sadly, it's still occurring in our production boxes, since
it's not a main branch feature, although making all of our database backups
striped across two files fixed the issue, but was a mess when we had a
bunch of 800 MB databases striped acrose two files.

**Comment by olahallengren** [comment]
I am working on a feature with a database size parameter to control if multiple files should be used.

```
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@NumberOfFiles = 4,
@MinDatabaseSizeForMultipleFiles = 1024
```

MinDatabaseSizeForMultipleFiles is the size of the database in MB.

It is in the branch feature-MinDatabaseSizeForMultipleFiles.
https://github.com/olahallengren/sql-server-maintenance-solution/tree/feature-MinDatabaseSizeForMultipleFiles

It does not work the same as @chadwestes's request, but it provides a way to back up large databases to multiple files, and small databases to only one file.

**Comment by chadwestes** [comment]
How is this different than the branch I put out there?

**Comment by olahallengren** [comment]
In your request you are introducing a DatabaseSizeSplit parameter, to dynamically calculate the number of files. So you will get more files, the large the database is.

In my branch you will get one file up to MinDatabaseSizeForMultipleFiles, and the number of files in NumberOfFiles for databases that are larger than that.

**Comment by chadwestes** [comment]
Any way you could incorporate both options;
say if the NumberOfFiles parameter was null to calculate a dynamic number
of files?

**Comment by olahallengren** [comment]
@chadwestes, I will do some testing with this.

**Comment by olahallengren** [comment]
I have a version that works like this now.

```
-- Back up to 4 files
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@Compress = 'Y',
@CheckSum = 'Y',
@NumberOfFiles = 4
```

```
-- Back up databases, with a size of 10240 MB or larger, to 4 files
-- Back up smaller databases to one file
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'D:\Backup',
@BackupType = 'FULL',
@Compress = 'Y',
@CheckSum = 'Y',
@NumberOfFiles = 4,
@MinDatabaseSizeForMultipleFiles = 10240
```

```
-- Calculate the number of backup files so that each file is getting at maximum 10240 MB
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'D:\Backup',
@BackupType = 'FULL',
@Compress = 'Y',
@CheckSum = 'Y',
@MaxFileSize = 10240
```

MinDatabaseSizeForMultipleFiles and MaxFileSize are in MB.

- When you are using ```@MaxFileSize``` the number of files are adjusted up, so that the files will be evenly distributed between the directories (when you specify multiple directories).

- I am getting the size of the database by summarizing the size of the data files (type_desc = 'ROWS'), in sys.master_files. I am aware of that this means that unallocated pages are included. However sys.master_files is the only view that is available on the secondary.

- Backup compression is not taken into account.

It is in the branch feature_MinDatabaseSizeForMultipleFiles_MaxFileSize.
https://github.com/olahallengren/sql-server-maintenance-solution/tree/feature_MinDatabaseSizeForMultipleFiles_MaxFileSize

**Comment by chadwestes** [comment]
Good job! I think that covers all the bases.
When do you think You'll incorporate it into the main branch?

**Comment by olahallengren** [comment]
There are a few more things that I need to handle.

- I need to make sure that I am not going over the maximum number of files, when ```MaxFileSize``` is used.

- I think that I will make a check that the new parameters are only used for full backups.

Then I need to do some more testing.

I can't commit to a date, but I am working on it.

**Comment by chadwestes** [comment]
Understood.
Let me know if there is anything I can do to help, whether it be testing,
code review, or writing code.
Always happy to contribute.

Chad

**Comment by olahallengren** [comment]
I have implemented the two things that I mentioned.

It is ready for testing and code review. (The interesting code starts with ```SELECT @CurrentNumberOfFiles = CASE WHEN @NumberOfFiles```.)

**Comment by olahallengren** [comment]
I am thinking about if it is useful to do differential backups to multiple files. One possibility would be to use sys.dm_db_file_space_usage.modified_extent_page_count.

I am also not sure about performing transaction log backups to multiple files. Is there a benefit? One possibility here would be to use sys.dm_db_log_stats.log_since_last_log_backup_mb (only works on primary in availability group scenarios).

Feedback is greatly appreciated.

**Comment by olahallengren** [comment]
I have been doing some changes.

- Changed the name of the parameter ```@MinDatabaseSizeForMultipleFiles``` to ```@MinBackupSizeForMultipleFiles```

- Changed to use sys.dm_db_file_space_usage.allocated_extent_page_count for full backups, when that is available. Using sys.master_files.size as fallback.

- Added support for differential backups. It is then using sys.dm_db_file_space_usage.modified_extent_page_count.

- Added support for transaction log backups. It is then using sys.dm_db_log_stats.log_since_last_log_backup_mb.

It is now in the branch feature_MinBackupSizeForMultipleFiles_MaxFileSize.

**Comment by olahallengren** [comment]
I am getting closer to releasing this.

I have done another update to the branch feature_MinBackupSizeForMultipleFiles_MaxFileSize.

```
-- Back up to 4 files
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@Compress = 'Y',
@CheckSum = 'Y',
@NumberOfFiles = 4
```

```
-- Back up databases, with a size of 10240 MB or larger, to 4 files
-- Back up smaller databases to one file
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@Compress = 'Y',
@CheckSum = 'Y',
@NumberOfFiles = 4,
@MinBackupSizeForMultipleFiles = 10240
```

```
-- Calculate the number of backup files so that each file is getting at maximum 10240 MB
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@Compress = 'Y',
@CheckSum = 'Y',
@MaxFileSize = 10240
```

**Comment by olahallengren** [comment]
This has been released now. Please try it out.

**Comment by stoycqs** [comment]
Is it possible to add the total number of files ex:
test123_FULL_20200113_152316_1.bak
test123_FULL_20200113_152316_2.bak
......
to become
test123_FULL_20200113_152316_1_of_10.bak
test123_FULL_20200113_152316_2_of_10.bak
.....

**Comment by olahallengren** [comment]
@stoycqs, there is a token for {NumberOfFiles} that you can use.
https://ola.hallengren.com/sql-server-backup.html#FileName

```
 @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}_of_{NumberOfFiles}.{FileExtension}'
```

However it looks like it is not working as you would think, when there is only one file. I will look into this a bit later.

**Comment by stoycqs** [comment]
> @stoycqs, there is a token for {NumberOfFiles} that you can use.
> https://ola.hallengren.com/sql-server-backup.html#FileName
> 
> ```
>  @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}_of_{NumberOfFiles}.{FileExtension}'
> ```
> 
> However it looks like it is not working as you would think, when there is only one file. I will look into this a bit later.

It works perfectly!
Thank you very much!

**Comment by olahallengren** [comment]
I am not considering compression. (Different databases have different compression ratio.)

Could that be the reason?

**Comment by olahallengren** [comment]
Sorry, I misunderstood.

>It works if there are multiple files but if the backup size for some DBs (@MinBackupSizeForMultipleFiles) is below the threshold it creates a single file like:
tes222_full_20200113_160812_of.bak

This is an issue in the script. I will look into that.

**Comment by olahallengren** [comment]
@stoycqs, could you please create a new issue for this.

It is not related to the new features that I have been added. It is some special logic in the code for naming of files.

**Comment by olahallengren** [comment]
I have released a new version with a minor change to this. It does not fully solve the issue, but it improves the code a bit.

This issue is related to logic that the tokens for file number and number of files, should only be included in the file name, when there are multiple - files.

This makes sense when you always back up to one file, but when the number of files is dynamic, it is good to have the file number and number of files.

Please create a new issue, and then we can discuss the options there.

**Comment by stoycqs** [comment]
Hi @olahallengren ,

I've created a feature request [Issue 330](https://github.com/olahallengren/sql-server-maintenance-solution/issues/330)

**Comment by snjvsnh89** [comment]
> Add feature to enable a dynamic number of files based upon database size.
> 
> Many companies are moving database backups to AWS S3 storage, but are running into issues with larger databases; namely a max file size limitation imposed by AWS. This can be sidestepped if you supply a value for the @NumberOfFiles parameter, but unless you want to create multiple jobs for each database and constantly adjust the number, you will end up with lots of files that are very small. I suggest a parameter that would serve as a threshold for when to split a database backup into multiple files.
> Say you had a 75 GB, 100 GB, and 300 GB database on a server along with several databases less than 5 GB. You could supply a value of 50 GB to this new parameter and the backup script would then backup each of the < 5GB databases into 1 file each, break the 75 GB and 100 GB files into 2 files each and the 300 GB database into 6 files.

>>Can we add Backup Devices According to @Directory and @filename...

**Comment by snjvsnh89** [comment]
I have requirment to make Backup device as per Dynamic backup and split
with @directory\@filename
Please help......
Thanks in advance

**Comment by sapkota-pratik** [comment]
@olahallengren 
Random duplicate backup is happening after adding below parameter 
@Numberoffiles = 4,
@minbackupsizeformultiplefiles = 409600,

Both full and differential backup jobs backing up a few databases twice.

SQL Server: 2016

**Comment by praneetheranti** [comment]
@olahallengren How to use @min and @max backup size file parameter both at a time ? When backup size reach X size it should go in to split but each file should not exceed Y size. I have DB whose backup size is 195 GB with single file but when I used max parameter as 190 GB , backup files were splitted into 3 files instead 2 files . @chadwestes
