### ISSUE TITLE
IndexOptimize runs a FOR XML query that executes in AUTO mode, which returns references to derived table aliases. 

### ISSUE THREAD

**Issue by hfleitas** [olahallengren/sql-server-maintenance-solution#23]
Under compatibility level 90 or later, the query returns references to the derived table alias instead of to the derived table's base tables, so you should modify your application as required to account for the changes. For more details, please see: Line 1343, Column 60.

Here’s the affected block.

Current:

        IF @CurrentIndexID IS NOT NULL AND (@CurrentPageCount IS NOT NULL OR @CurrentFragmentationLevel IS NOT NULL)
        BEGIN
        SET @CurrentExtendedInfo = (SELECT *
                                    FROM (SELECT CAST(@CurrentPageCount AS nvarchar) AS [PageCount],
                                                 CAST(@CurrentFragmentationLevel AS nvarchar) AS Fragmentation
                                    ) ExtendedInfo FOR XML AUTO, ELEMENTS)
        END

Should be: 

        IF @CurrentIndexID IS NOT NULL AND (@CurrentPageCount IS NOT NULL OR @CurrentFragmentationLevel IS NOT NULL)
        BEGIN
        SET @CurrentExtendedInfo = (SELECT *
                                    FROM (SELECT CAST(@CurrentPageCount AS nvarchar) AS [PageCount],
                                                 CAST(@CurrentFragmentationLevel AS nvarchar) AS Fragmentation
                                    ) ExtendedInfo FOR XML RAW('Fragmentation'), ELEMENTS)
        END

**Comment by olahallengren** [comment]
When I am testing it with the current code, it looks like this:

```
<ExtendedInfo>
  <PageCount>4</PageCount>
  <Fragmentation>75</Fragmentation>
</ExtendedInfo>
```

This is how it is intended to look like.

**Comment by hfleitas** [comment]
Ok I understand, the change should return the same output though. 

Here's another test: 

`SELECT *
FROM (SELECT CAST(4 AS nvarchar) AS [PageCount],
			 CAST(75 AS nvarchar) AS Fragmentation
) ExtendedInfo FOR XML RAW('ExtendedInfo'), ELEMENTS`

**Comment by olahallengren** [comment]
I decided to change the code as you suggested. Thank you.
