### ISSUE TITLE
Add {NumberOfFiles} token

### ISSUE THREAD

**Issue by DavidWiseman** [olahallengren/sql-server-maintenance-solution#233]
**Description of the feature**
Add a {NumberOfFiles} token.  e.g.

{DatabaseName}_{BackupType}_{Year}{Month}{Day}_{FileNumber}of_{NumberOfFiles}.{FileExtension}

Example:
MyDB_FULL_20190521_1of2.BAK

So given the file above I know that I also need:
MyDB_FULL_20190521_2of2.BAK

It's possible to workaround this by hard-coding the number of files, but it would be nice as a token:
{DatabaseName}_{BackupType}_{Year}{Month}{Day}_{FileNumber}of_2.{FileExtension}

**Comment by olahallengren** [comment]
I have added the token.
https://ola.hallengren.com/versions.html

Thank you for the suggestion.

**Comment by DavidWiseman** [comment]
Wow!  Thank you for the fast turn around.  👍
