### ISSUE TITLE
Log Backup in Availability Group

### ISSUE THREAD

**Issue by bjeli1980** [olahallengren/sql-server-maintenance-solution#234]
**Description of the issue**
I'm trying to do a LOG BACKUP in the primary but it doesn't work. It looks like that it works but I don't get any new row in the CommandLog table and the new file is not create in the Log backup directory.

I change the availability group to set the backup preference to PRIMARY
ALTER AVAILABILITY GROUP [AlwaysOn_HOSTPRO] SET(
AUTOMATED_BACKUP_PREFERENCE = PRIMARY
);

It works when I comment the line 209 3in the procedure DatabaseBackup

--AND NOT (@CurrentAvailabilityGroup IS NOT NULL AND @CurrentBackupType = 'LOG' AND @CopyOnly = 'N' AND (@CurrentIsPreferredBackupReplica <> 1 OR @CurrentIsPreferredBackupReplica IS NULL) AND @OverrideBackupPreference = 'N')

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Server 2017 (RTM-CU14) (KB4484710) - 14.0.3076.1 (X64)   Mar 12 2019 19:29:19   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 
**Version of the script**
Check the header of the stored procedure
Version: 2019-02-10 10:40:47 
**What command are you executing?**
-- Backup Transaction log
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'ZZ_BORRAR',
@Directory = '\\lk2shares.cl.clpek.net\HOSTPRO_BackupBBDD$', 
@BackupType = 'LOG',
@Verify = 'Y',
@CleanupTime = NULL, 
@Compress = 'Y',
@CheckSum = 'Y',
@LogToTable = 'Y'

**What output are you getting?**
Date and time: 2019-05-21 15:42:09
Server: HOSTPRO
Version: 14.0.3076.1
Edition: Enterprise Edition: Core-based Licensing (64-bit)
Platform: Windows
Procedure: [master].[dbo].[DatabaseBackup]
Parameters: @Databases = 'ZZ_BORRAR', @Directory = '\\lk2shares.cl.clpek.net\HOSTPRO_BackupBBDD$', @BackupType = 'LOG', @Verify = 'Y', @CleanupTime = NULL, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'N', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'Y', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = NULL, @Credential = NULL, @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @AvailabilityGroupDirectoryStructure = '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'
Version: 2019-02-10 10:40:47
Source: https://ola.hallengren.com
	
Date and time: 2019-05-21 15:42:09
Database: [ZZ_BORRAR]
Status: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Is accessible: Yes
Recovery model: FULL
Encrypted: No
Availability group: AlwaysOn_HOSTPRO
Availability group role: PRIMARY
Availability group backup preference: PRIMARY
Is preferred backup replica: No
Differential base LSN: 43000000895200037
Last log backup LSN: 43000001320800001
Last log backup: 2019-05-21 15:33:32
Log size since last log backup (MB): 23.5391
	
Date and time: 2019-05-21 15:42:09

**Comment by olahallengren** [comment]
Could you execute this command on all the replicas as a test?

```
SELECT availability_groups.name,
       dm_hadr_availability_replica_states.role_desc,
       availability_groups.automated_backup_preference_desc,
       sys.fn_hadr_backup_is_preferred_replica (databases.name) AS backup_is_preferred_replica
FROM sys.databases databases
INNER JOIN sys.dm_hadr_availability_replica_states dm_hadr_availability_replica_states ON databases.replica_id = dm_hadr_availability_replica_states.replica_id
INNER JOIN sys.availability_groups availability_groups ON dm_hadr_availability_replica_states.group_id = availability_groups.group_id
WHERE databases.name = 'ZZ_BORRAR'
```

**Comment by bjeli1980** [comment]
I run the command in the primary and I get:
name	role_desc	automated_backup_preference_desc	backup_is_preferred_replica
AlwaysOn_HOSTPRO	PRIMARY	primary	0

If I run in the replica:
name	role_desc	automated_backup_preference_desc	backup_is_preferred_replica
AlwaysOn_HOSTPRO	SECONDARY	primary	0

**Comment by BachhF00** [comment]
Had similar problem a while ago because a colleague used the servers' FQDN to set up the AG. So sys.fn_hadr_backup_is_preferred_replica always returned 0 because it depends on the @@ servername output.
