### ISSUE TITLE
Log and Incremental Backups not running in SQL 2016 HA AGs

### ISSUE THREAD

**Issue by Cadius1** [olahallengren/sql-server-maintenance-solution#24]
I'm not sure if this is a bug or not, but I set up a three-node SQL 2016 AlwaysOn High Availability Availability Group.

Without realizing the impact, I set the backup preferences of this AG  to perform backups on Any Replica, and left the backup priority at the default 50 on all three nodes.

I installed the maintenance solution on all three nodes.

The Full backups from the default USER_DATABASES - FULL job runs fine per the schedule I set.

The Incremental backups and the Log backups do not run. The job runs, but it skips all databases in the AG. If I run the execute step manually, it lists those AG databases with the AG name, but no backups occur.

If I change the backup priority so they are not equal, then the logs and incremental backups run successfully from the node with highest priority.

I'm not sure if the script is looking at the backup priority value, deciding it's not higher than any of the other nodes, and skipping it? Maybe because it assumes some other node with a higher priority should do the job?

**Comment by olahallengren** [comment]
Here is how DatabaseBackup is doing backup of databases in availability groups:

Copy-only full backups and (non copy-only) log backups will always be performed on the preferred backup replica. DatabaseBackup is checking [sys.fn_hadr_backup_is_preferred_replica](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-hadr-backup-is-preferred-replica-transact-sql) to find the preferred backup replica.

Full backups (non copy-only) and differential backups are only supported on the primary replica. DatabaseBackup will always perform these types of backups on the primary replica.

To understand what is happening in your scenario, I would need the output - files from DatabaseBackup. If you could send them to me in a mail, I will look into it.
https://ola.hallengren.com/contact.html
