### ISSUE TITLE
Set case of backup folder and filename

### ISSUE THREAD

**Issue by griffitmatt** [olahallengren/sql-server-maintenance-solution#240]
Is it possible to have an option to change the case of the backup folder name and filename to be all lower case or upper case. 

For example instead of the backup file being written as

MyDb/MyDb_FULL_

you can set it be all lower case

mydb/mydb_full_

Thanks

Matt

**Comment by olahallengren** [comment]
Another option here would be to introduce some new tokens for lower case.
DatabaseName_LC, BackupType_LC and so on.

Could I ask you about the reason for preferring lower case? Company standard? Linux?

**Comment by olahallengren** [comment]
I have been doing some work on this. Please have a look at https://github.com/olahallengren/sql-server-maintenance-solution/pull/836.

**Comment by olahallengren** [comment]
Here is the documentation:
https://ola.hallengren.com/sql-server-backup.html#DirectoryStructureCase
https://ola.hallengren.com/sql-server-backup.html#FileNameCase
