### ISSUE TITLE
Index Maintenance procedure creation fails on Azure SQLDB

### ISSUE THREAD

**Issue by kodaksmile1** [olahallengren/sql-server-maintenance-solution#241]
When running the script to create the index optimize stored procedure in an Azure SQL DB it fails with the following error:
Msg 319, Level 15, State 1, Procedure IndexOptimize, Line 1621 [Batch Start Line 9]
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.

**SQL Server version and edition**
Microsoft SQL Azure (RTM) - 12.0.2000.8   May  2 2019 20:11:13   Copyright (C) 2019 Microsoft Corporation 

**Version of the script**
 Version: 2019-06-14 00:05:34  

**What command are you executing?**
See above
**What output are you getting?**
See above

**Comment by olahallengren** [comment]
Could it be that you have "Column Encryption Setting=enabled" in the SSMS connection string?

There was another issue reported, #313, with the same error message, that was caused by that.
