### ISSUE TITLE
DatabaseBackup Jobs are not deployed to Azure Managed Instance

### ISSUE THREAD

**Issue by gbargsley** [olahallengren/sql-server-maintenance-solution#242]
**Description of the issue**
When deploying the MaintenanceSolution to an Azure Managed Instance all the jobs except DatabaseBackup and a couple cleanup jobs.  I am able to manually create the job and run it to an Azure BLOB storage.

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Azure (RTM) - 12.0.2000.8   May 29 2019 23:24:58   Copyright (C) 2019 Microsoft Corporation 

**Version of the script**
Check the header of the stored procedure
Version: 2019-06-14 00:05:34

**What command are you executing?**
Just running the MaintenanceSolution.sql file in its entirety with create jobs equals yes.

**What output are you getting?**
No errors in the output, just not creating the jobs.

**Comment by olahallengren** [comment]
I am not creating the backup jobs on Azure SQL Database Managed Instance, as Microsoft is doing the backup automatically for you.

I know that it is possible to perform copy-only full backups to Azure Blob Storage, but normally you don't need to do that.
