### ISSUE TITLE
Reorg Index on Small File

### ISSUE THREAD

**Issue by taylord-hutgroup** [olahallengren/sql-server-maintenance-solution#243]
**Description of the issue**
When reorganising an index on a database where the file group has multiple files but the index is contained a file that is to small (and cannot grow) to host the new index it just fails instead of attempting a rebuild - I appreciate this is a very particular set of circumstances so will be low priority.

**SQL Server version and edition**
SQL Server 2016 (SP2-CU5) (KB4475776)
Enterprise Edition

**Version of the script**
I can't find the version however it is from March 2018.

**What command are you executing?**
EXECUTE *********.dbo.IndexOptimize 
    @Databases = 'ALL_DATABASES',
    @FragmentationLow = NULL,
    @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',
    @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',
    @FragmentationLevel1 = 30,
    @FragmentationLevel2 = 50,
    @SortInTempdb = 'Y',
    @LogToTable = 'Y'

is executing "ALTER INDEX [PK__shipment__18EE3BAE3D5E1FD2] ON [Sherlock].[dbo].[shipment] REORGANIZE WITH (LOB_COMPACTION = ON)"

**What output are you getting?**
Could not allocate space for object 'dbo.********'.'PK__********__********' in database 'Sherlock' because the 'PRIMARY' filegroup is full. Create disk space by deleting unneeded files, dropping objects in the filegroup, adding additional files to the filegroup, or setting autogrowth on for existing files in the filegroup.

**Comment by olahallengren** [comment]
I don't think that I can do anything in the stored procedure, if the filegroup is getting full.
