### ISSUE TITLE
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server :  Driver's SQLAllocHandle on SQL_HANDLE_ENV failed

### ISSUE THREAD

**Issue by Ken-White** [olahallengren/sql-server-maintenance-solution#244]
**Description of the issue**
Backup not executing

**SQL Server version and edition**
Microsoft SQL Server Express (64-bit) 16
13.0.1742.0

**Version of the script**
2018-10-28 14.45.02

**What command are you executing?**
SQLCMD -S HPDESKTOP\SQLEXPRESS01 -U xxxxxxxxx -P yyyyyyyy -d master -Q "EXECUTE dbo.DatabaseBackup @Databases = 'ALL_DATABASES', @Directory = '\\HPDESKTOP\SQLServerBackupDrive', @BackupType = 'FULL', @Verify = 'Y', @CleanupMode = 'AFTER_BACKUP', @CleanUpTime = 48, @CheckSum = 'Y', @LogToTable = 'Y', @Execute = 'Y'" -b -o C:\Users\xxx\Desktop\TherapyWorksSplit\Temp\SQLServerUtilityResults.txt

**What output are you getting?**
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server :  Driver's SQLAllocHandle on SQL_HANDLE_ENV failed.

**Comment by olahallengren** [comment]
This looks like an issue in sqlcmd. Does it happen every time?
