### ISSUE TITLE
Data Domain Boost and SQL Backup Compression

### ISSUE THREAD

**Issue by dokier** [olahallengren/sql-server-maintenance-solution#248]
Should SQL Backup compression be enabled or not when using Dell EMC Data Domain Boost? Thanks!

https://blog.dellemc.com/en-us/sql-server-maintenance-solution-supports-dell-emc-data-protection/

**Comment by olahallengren** [comment]
The backup will always be compressed in Data Domain Boost, when you specify ```@BackupSoftware = 'DATA_DOMAIN_BOOST'```.

The ```@Compress``` parameter is not used with Data Domain Boost, so you don't need to specify it.
