### ISSUE TITLE
Please overwrite Azure Blob backups using WITH FORMAT

### ISSUE THREAD

**Issue by Daemach** [olahallengren/sql-server-maintenance-solution#251]
Please add the WITH FORMAT parameter when I pass Init = 'Y' for Azure Blob backups so the backup file will be overwritten.  If this parameter is not added, the following error results:

Msg 3271, Level 16, State 1, Line 1
A nonrecoverable I/O error occurred on file "https://myAzureAccount.blob.core.windows.net/myazurecontainer/latest/mydatabase.bak:" The file https://myAzureAccount.blob.core.windows.net/myazurecontainer/latest/mydatabase.bak exists on the remote endpoint, and WITH FORMAT was not specified. Backup cannot proceed..
Msg 3013, Level 16, State 1, Line 1
BACKUP DATABASE is terminating abnormally.

More info here: https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2017#support-for-backup-arguments

**Comment by olahallengren** [comment]
I have added support for the FORMAT option.
https://ola.hallengren.com/sql-server-backup.html#Format
