### ISSUE TITLE
Agent Job sp_purge_jobhistory

### ISSUE THREAD

**Issue by troyf** [olahallengren/sql-server-maintenance-solution#253]
Agent Job sp_purge_jobhistory

I'd like to see the sp_purge_jobhistory include an additional line in the step...

EXEC msdb.dbo.sp_set_sqlagent_properties @jobhistory_max_rows=-1, @jobhistory_max_rows_per_job=-1

This is included when one goes to SSMS/Object Explorer/SQL Server Agent/properties/history and unchecks the default log history size limit of 1000 rows and checks the 'Remove agent history, older than' -> thereby changing the max log size from a number of rows to an amount of time.

Without this additional line, there's one log size limit maintained by SQL Server, and another maintained by the agent job.

Troy.
#

**Comment by olahallengren** [comment]
The risk with this would just be that, if you have some other job that is running very frequently, that could generate very large amounts of rows in msdb.dbo.sysjobhistory.

**Comment by olahallengren** [comment]
Another thing is that, as this is a one-time configuration change, there is no need to include that in a job.
