### ISSUE TITLE
@DirectoryStructure = "" fails

### ISSUE THREAD

**Issue by Daemach** [olahallengren/sql-server-maintenance-solution#254]
When backing up to Azure, I need to be able to pass the filename ONLY without a "/" or anything else to have it stored in the container root.  But @DirectoryStructure = '' fails.  Using {DirectorySeparator} on a local file system would be OK, but when using this on Azure, it creates a subfolder called "no name".  Listing files in the container shows the preceding "/" but using Get-AzureBlobContent tries to store the downloaded files in the root folder which fails as well.

Please allow me to pass NO directory structure, at least for Azure backups.

**Comment by olahallengren** [comment]
Could you try with ```@DirectoryStructure = NULL```?

**Comment by Daemach** [comment]
That worked.  Please add this information to the backup examples.  Thank you!

**Comment by olahallengren** [comment]
I am happy that it worked.

There is this example:

```
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@DirectoryStructure = NULL,
@AvailabilityGroupDirectoryStructure = NULL
```

https://ola.hallengren.com/sql-server-backup.html#Examples

Maybe I should add one example with backup to URL without sub-directories.
