### ISSUE TITLE
IndexOptimize Against Azure SQL DB Getting Wrong Database ID

### ISSUE THREAD

**Issue by jacobgexigo** [olahallengren/sql-server-maintenance-solution#255]
**Description of the issue**
I’m getting an error message when running the IndexOptimize proc against an Azure SQL connection that has multiple Azure SQL DB databases (DaaS) on it.  It turns out that if you run SELECT * FROM sys.databases from Master (returns DB ID 16), you may get a different database ID than if you run the same statement against the database itself (returns DB ID 19).  So in your code it seems that maybe you are getting the ID from master and then later in the code using it against the database itself (what it thinks is the correct database ID).  Microsoft says this is by design and that we should use database name instead.  

The output below has been cleansed of server and database name.  It does continue and finish reindexing, etc. but causes the job to fail because of the messages returned.

**SQL Server version and edition**
Azure SQL DB (DaaS)

**Version of the script**
2019-06-14 00:05:34 fails with errors
2018-06-24 15:24:40 works fine

**What command are you executing?**
EXECUTE dbo.IndexOptimize   
       @Databases = '{dbname}', 
       @FragmentationLow = 'INDEX_REORGANIZE',    
       @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',    
       @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',    
       @FragmentationLevel1 = 10,    
       @FragmentationLevel2 = 30,    
       @UpdateStatistics = 'ALL', 
       @MinNumberOfPages = 1, 
       @FillFactor = 80,    
       @Delay = 1,    
       @MaxDOP = 1,  
       @LogToTable = 'Y'

**What output are you getting?**
Date and time: 2019-07-18 03:40:05
Server: {servername}
Version: 12.0.2000.8
Edition: SQL Azure
Platform: Windows
Procedure: [{dbname}].[dbo].[IndexOptimize]
Parameters: @Databases = '{dbname}', @FragmentationLow = 'INDEX_REORGANIZE', @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationLevel1 = 10, @FragmentationLevel2 = 30, @MinNumberOfPages = 1, @MaxNumberOfPages = NULL, @SortInTempdb = 'N', @MaxDOP = 1, @FillFactor = 80, @PadIndex = NULL, @LOBCompaction = 'Y', @UpdateStatistics = 'ALL', @OnlyModifiedStatistics = 'N', @StatisticsModificationLevel = NULL, @StatisticsSample = NULL, @StatisticsResample = 'N', @PartitionLevel = 'Y', @MSShippedObjects = 'N', @Indexes = NULL, @TimeLimit = NULL, @Delay = 1, @WaitAtLowPriorityMaxDuration = NULL, @WaitAtLowPriorityAbortAfterWait = NULL, @Resumable = 'N', @AvailabilityGroups = NULL, @LockTimeout = NULL, @LockMessageSeverity = 16, @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'
Version: 2019-06-14 00:05:34
Source: https://ola.hallengren.com
       
Date and time: 2019-07-18 03:40:05
Database: [{dbname}]
State: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Recovery model: FULL
       
**Msg 50000, Level 16, State 1, Procedure dbo.IndexOptimize, Line 1811 [Batch Start Line 0] Msg 2521, Could not find database ID 19. The database ID either does not exist, or the database was dropped before a statement tried to use it. Verify if the database ID exists by querying the sys.databases catalog view.**

**Msg 50000, Level 16, State 1, Procedure dbo.IndexOptimize, Line 1811 [Batch Start Line 0] Msg 2521, Could not find database ID 19. The database ID either does not exist, or the database was dropped before a statement tried to use it. Verify if the database ID exists by querying the sys.databases catalog view.**

**Msg 50000, Level 16, State 1, Procedure dbo.IndexOptimize, Line 1811 [Batch Start Line 0] Msg 2521, Could not find database ID 19. The database ID either does not exist, or the database was dropped before a statement tried to use it. Verify if the database ID exists by querying the sys.databases catalog view.**
       
Date and time: 2019-07-18 03:40:05
Command: UPDATE STATISTICS [{dbname}].[dbo].[{tablename}] [{statname}]
Comment: ObjectType: Table, IndexType: Column, Incremental: N, RowCount: 1588, ModificationCounter: 0
Outcome: Succeeded
Duration: 00:00:00
Date and time: 2019-07-18 03:40:05

etc.

**Comment by olahallengren** [comment]
@jacobgexigo, I am looking at this. I am trying to understand what statement in IndexOptimize that is generating the error. In your output it says line 1811, but that does not make any sense. Have you found out about that?

**Comment by olahallengren** [comment]
I found out about it. It is when IndexOptimize is querying sys.dm_db_index_physical_stats that it happens.

**Comment by jacobgexigo** [comment]
Oh great, thank you!


Sincerely,

Jacob Golden
Database Services Manager
Mobile 913-486-8328
After Hours  214-367-9999

[imgLogoSmall]

CONFIDENTIALITY NOTICE: This email and any attachments may contain privileged and confidential information intended only for the use of the individual or entity named above.  If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution, or duplication of this communication is strictly prohibited.  If you are not the intended recipient, please notify the sender immediately and destroy this message without disclosing the contents to anyone, using it for any purpose, or storing or copying it into any medium.

**Comment by olahallengren** [comment]
I have released a fix for this.
https://ola.hallengren.com/versions.html
