### ISSUE TITLE
@URL parameter and backup subdirectories

### ISSUE THREAD

**Issue by GeorgePalacios** [olahallengren/sql-server-maintenance-solution#26]
Currently backup to URL with Azure supports subdirectories - this is not currently implemented in the solution so all backup files are dropped into the root folder supplied as a parameter in the job (or default value).

Could this be changed so when a backup to an URL occurs to Azure, subdirectories are used in the same way as when backing up to disk?

**Comment by olahallengren** [comment]
I am looking into making the directory structure configurable. This would work for disk and URL.

**Comment by olahallengren** [comment]
I have a preview version where you can configure the directory structure. This works for disk and URL. By default it is backing up to sub-directories. You can download the preview version [here](https://ola.hallengren.com/preview.html).

**Comment by olahallengren** [comment]
This feature is available in the branch [feature-configurable_directory_structure].
