### ISSUE TITLE
Minimum permissions to run indexoptimize

### ISSUE THREAD

**Issue by webbexpert** [olahallengren/sql-server-maintenance-solution#268]
I have your database maintenance script installed in azure's sql db's solution. It seems the only role that works is db_owner. I've tried assigning db_datawriter/db_datareader, and GRANT execute on the security context via role (db_executor), however, one of these security roles allows for running the stored procedure. 
Do you know what the minimum permissions required for the user who is executing IndexOptimize?
Thanks in advance!!

**Comment by olahallengren** [comment]
The minimum permissions are:

EXECUTE on dbo.IndexOptimize
VIEW DEFINITION on dbo.CommandExecute
VIEW DEFINITION on dbo.CommandLog
VIEW SERVER STATE
db_owner on all target databases
