### ISSUE TITLE
LitreSpeed Adaptive Compression

### ISSUE THREAD

**Issue by cabana1** [olahallengren/sql-server-maintenance-solution#27]
When using LiteSpeed compression you can only set @CompressionLevel values from 0 - 8.

It would be great to be able to use @adaptivecompression instead of @CompressionLevel.

https://support.quest.com/technical-documents/litespeed-for-sql-server/8.5/installation-guide/xp_backup_database#@adaptiv

@adaptivecompression Automatically selects the optimal compression level based on CPU usage or Disk IO. You can tell Adaptive Compression to optimize backups either for size or for speed. This argument accepts one of the following values:
Size
Speed

**Comment by olahallengren** [comment]
I have released a new version with this support for this option.
https://ola.hallengren.com/sql-server-backup.html#AdaptiveCompression
