### ISSUE TITLE
Azure BLOB storage not working on SQL 2008R2?

### ISSUE THREAD

**Issue by tvandael** [olahallengren/sql-server-maintenance-solution#272]
Hi,

we are currently migrating our environment to SQL2016.
However, we still have some 2008/2008R2 system in place (I know they are out of support but we are trying to move them).
One task in this process is the backup to Azure BLOB storage.
This is working for all versions higher than 2008.
When running the command on 2008/2008R2, we receive the following error:
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 1360 [Batch Start Line 0]
The value for the parameter @URL is not supported.
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 1604 [Batch Start Line 0]
The documentation is available at https://ola.hallengren.com/sql-server-backup.html.

This exact identical command is running fine on higher versions.
Anyone knows what module/program is missin on 2008/2008R2 to get it working?

Tx

T

**Comment by dczarny** [comment]
Was backing up to a URL available in SQL Server 2008R2?  Have you tried to run the native command to see if it works properly?

**Comment by tvandael** [comment]
You are correct: URL backup was only introduced as of 2012 SP1...

Tx

T
