### ISSUE TITLE
IndexOptimize is failing azure sql

### ISSUE THREAD

**Issue by chinozhang** [olahallengren/sql-server-maintenance-solution#275]
**Description of the issue**
IndexOptimize.sql is failing with an error that the database cannot be found.
The issue is that de database id in the sys.databases does not match with db_id('databaseName')
This can happen in rare cases only for azure sql databases when a failover happened. 
From the [documentation ](https://docs.microsoft.com/en-us/sql/t-sql/functions/db-id-transact-sql?view=sql-server-2017) 
> When used with Azure SQL Database, DB_ID may not return the same result as querying database_id from sys.databases. If the caller of DB_ID is comparing the result to other sys views, then sys.databases should be queried instead.

**Suggested/Possible solution**
Change line 1357 of IndexOptimize.sql 
from
` SELECT @CurrentDatabaseID = database_id`
to
` SELECT @CurrentDatabaseID = db_id(@CurrentDatabaseName)`

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Azure (RTM) - 12.0.2000.8   Aug 23 2019 18:35:02   Copyright (C) 2019 Microsoft Corporation 

**Version of the script**
Check the header of the stored procedure
2019-06-14 00:05:34   

**What command are you executing?**
The indexoptimize script

**What output are you getting?**
Msg 2521, Could not find database ID 5. The database ID either does not exist, or the database was dropped before a statement tried to use it. Verify if the database ID exists by querying the sys.databases catalog view.

**Comment by chinozhang** [comment]
#255 most likely same issue, if so please close this issue

**Comment by olahallengren** [comment]
I am looking at this, and I am trying to understand what statement in IndexOptimize that is generating the error. Have you found out about that?

**Comment by chinozhang** [comment]
> I am looking at this, and I am trying to understand what statement in IndexOptimize that is generating the error. Have you found out about that?

It's been some time, I don't remember exactly but I just checked the code again and I think it should have failed on this statement here: 
`EXECUTE sp_executesql @statement = @CurrentCommand05, @params = N'@ParamDatabaseID int, @ParamObjectID int, @ParamIndexID int, @ParamPartitionNumber int, @ParamFragmentationLevel float OUTPUT, @ParamPageCount bigint OUTPUT', @ParamDatabaseID = @CurrentDatabaseID, @ParamObjectID = @CurrentObjectID, @ParamIndexID = @CurrentIndexID, @ParamPartitionNumber = @CurrentPartitionNumber, @ParamFragmentationLevel = @CurrentFragmentationLevel OUTPUT, @ParamPageCount = @CurrentPageCount OUTPUT`

As stated in the initial bug report the id is not found because we are on azure sql and a failover took place. Therefore the database id does not match when you compare the db id from sys.databases and db_id('databaseName') Hope this helps.

**Comment by olahallengren** [comment]
Now I understand. It is when IndexOptimize is querying sys.dm_db_index_physical_stats that it happens.

**Comment by olahallengren** [comment]
I have released a fix for this.
https://ola.hallengren.com/versions.html
