### ISSUE TITLE
DatabaseBackup - @FileName - Inclusion of Non-Token words

### ISSUE THREAD

**Issue by imajaydwivedi** [olahallengren/sql-server-maintenance-solution#279]
### Allow extra keywords as part of @FileName apart from Tokens.

For example:- I need to generate a backup file like below:-

test_mirroring_data_20190908_010016.bak

`{DatabaseName}_data_{Year}_{Month}_{Day}_{Hour}{Minute}{Second}.{FileExtension}`

where {DatabaseName} = 'test_mirroring'
{Year}_{Month}_{Day} = '2019_09_08'
{Hour}{Minute}{Second} = '010016'
{FileExtension} = 'bak'

But, **data** is a normal word which I wish to add in backup file name. Currently, we receive below error message:-

> Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 1299 [Batch Start Line 12]
> The parameter @FileName contains one or more tokens that are not supported.
> Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 1370 [Batch Start Line 12]
> The documentation is available at https://ola.hallengren.com/sql-server-backup.html.

**Comment by olahallengren** [comment]
I tested this:
```@FileName = '{DatabaseName}_data_{Year}_{Month}_{Day}_{Hour}{Minute}{Second}.{FileExtension}'```

That results in a backup file name like this:
model_data_2019_12_26_153811.bak
