### ISSUE TITLE
UpdateStatistics='ALL' even when index is rebuilt?

### ISSUE THREAD

**Issue by KitLemmonds** [olahallengren/sql-server-maintenance-solution#280]
My understanding is that MSSQL automatically rebuilds statistics with full scan when rebuilding an index. Does IndexOptimize call "update statistics" and manually rebuild statistics for those rebuilt indexes?  Am I replacing better full scan statistics with sampled indexes by specifying  @UpdateStatistics = 'ALL' when rebuilding indexes?

**Comment by markaugust** [comment]
Check out Line 1913 in the IndexOptimize.sql file.  I believe this is where the logic is that will answer your question.

If you use the @OnlyModifiedStatistics = 'Y' parameter as well, it will definitely not, as after the index is rebuilt, the modification counter (for the statistic with the same name as the index) is 0.

**Comment by olahallengren** [comment]
If the index has been rebuilt, it will not explicitly update statistics for that index.
