### ISSUE TITLE
DatabaseBackup Init does not replace existing file in Azure Storage Account

### ISSUE THREAD

**Issue by GrumpyVader** [olahallengren/sql-server-maintenance-solution#282]
**Description of the issue**
When setting @Init = 'Y' option, when backing up to Azure Storage Account, if a backup file with the same name already exists, it is not over written and an error is thrown that directs you to use the Format option.

**SQL Server version and edition**
14.0.3223.3

**Version of the script**
Version: 2019-02-10 10:40:47

**What command are you executing?**
EXECUTE dbo.DatabaseBackup 
@Databases = '<database>', 
@BackupType = 'FULL', 
@Compress = 'Y', 
@URL = 'https://<storageaccount>.blob.core.windows.net/<container>/', 
@Credential = '<credential>', 
@NumberOfFiles = 1, 
@DirectoryStructure = NULL, 
@Init = 'Y',
@FileName = '{ServerName}$_{DatabaseName}_{Year}{Month}{Day}_{FileNumber}.{FileExtension}'

**What output are you getting?**
A nonrecoverable I/O error occurred on file ... The file ... exists on the remote endpoint, and WITH FORMAT was not specified. Backup cannot proceed..

**Comment by olahallengren** [comment]
I have added support for the FORMAT option.
https://ola.hallengren.com/sql-server-backup.html#Format
