### ISSUE TITLE
SQL Server Backup - Always on

### ISSUE THREAD

**Issue by RobKaye** [olahallengren/sql-server-maintenance-solution#288]
The SQL Server Integrity Check has an option for "AvailabilityGroupReplicas", can this option be added to SQL Server Backup?  Please?

**Comment by olahallengren** [comment]
Here is how it works for backups (from the Frequently Asked Questions, https://ola.hallengren.com/frequently-asked-questions.html):

********************************************************************************

First you need to decide where you want the backups to be performed; on the primary replica or on the secondary replica. SQL Server has an option called backup preference that you can set on the availability group. By default it is set to Prefer Secondary, but you can change it to Primary if you prefer that.

Not all backup types are supported on the secondary replica. Here are the backup types that are supported:

Copy-only full backups
Log backups (non copy-only)
DatabaseBackup will perform these types of backups on the preferred backup replica. It is using the function sys.fn_hadr_backup_is_preferred_replica to determine if the current replica is the preferred replica.

Full backups (non copy-only) and differential backups are only supported on the primary replica. DatabaseBackup will always perform these types of backups on the primary replica.

********************************************************************************

Will this work in your scenario?

**Comment by RobKaye** [comment]
Hi,

Yes it would work, and does work.  I’m using SQL 2016 which allows backups on either replica but still with the constraints in the FAQ’s.  The idea was to perform log backups on the primary in addition to log and full backups on the secondary and for that to be handled in one script which is copied to both replicas.  This would ensure the appropriate backup would take place on each replica if there ever was an issue and the secondary became the primary.

I’d just tested a similar script to perform Integrity Checks (IC) which can run on either primary or secondary and using @AvailabilityGroupReplicas means I didn’t need to use any conditional logic to check which replica the job is running on, and therefore which checks to perform.

If it was to be included in the backup scripts I’d be grateful, if not it won’t be a hardship to me and I’d be happy to close the request as answered.

I really do appreciate your response, thank you!

Kind regards,
Robert J Kaye
Information Manager Data Warehouse
P&I Department
South West Yorkshire Partnership NHS Foundation Trust
rob.kaye@swyt.nhs.uk<mailto:rob.kaye@swyt.nhs.uk>

[Description: allofusinmind]<http://www.southwestyorkshire.nhs.uk/> [Description: Twitter] <http://www.twitter.com/allofusinmind>  [Description: Facebook] <http://www.facebook.com/allofusinmind>  [Description: LinkedIn] <https://www.linkedin.com/company/south-west-yorkshire-partnership-nhs-foundation-trust>  [Description: Description: Description: cid:image006.jpg@01D53E4C.05F55B20]
Be a member!<http://www.southwestyorkshire.nhs.uk/about-us/how-we-are-run/membership/become-a-member/> | We proudly support #hellomynameis<http://www.southwestyorkshire.nhs.uk/service-users-and-carers/hellomynameis/>
