### ISSUE TITLE
Linux SQL backup with verify fails on permissions

### ISSUE THREAD

**Issue by Daemach** [olahallengren/sql-server-maintenance-solution#289]
I'm backing up with verify = "Y" on linux.  The backup works, but verifying fails because of permissions.  Is there any way around this?  Not being able to verify isn't a deal breaker, but it would be nice if there were a way to make it work.

Date and time: 2019-09-27 11:45:04
Command: BACKUP LOG [Offline] TO DISK = N'/var/opt/mssql/backup/2019-09-27/Offline_20190927_114504.trn' WITH NO_CHECKSUM, COMPRESSION
Msg 3201, Level 16, State 1, Server ip-172-26-8-187, Line 1
Cannot open backup device '/var/opt/mssql/backup/2019-09-27/Offline_20190927_114504.trn'. Operating system error 5(Access is denied.).
Msg 3013, Level 16, State 1, Server ip-172-26-8-187, Line 1
BACKUP LOG is terminating abnormally.
Outcome: Failed
Duration: 00:00:01
Date and time: 2019-09-27 11:45:05

**Comment by olahallengren** [comment]
In your example, it looks like it is the backup that fails.

Can you reproduce it outside of DatabaseBackup?
```BACKUP LOG [Offline] TO DISK = N'/var/opt/mssql/backup/2019-09-27/Offline_20190927_114504.trn' WITH NO_CHECKSUM, COMPRESSION```

**Comment by Daemach** [comment]
Yes, at the time I tested this backup to azure was not supported in Linux. I will try to test this again when I get a chance but needed a solution and ended up putting them on S3 instead. It’s typical MS to be lazy and end up driving customers to other solutions ;)

**Comment by olahallengren** [comment]
Thanks, @Daemach.

Could I ask how you did backup to S3? Backup to URL is only supported with Azure.

**Comment by Daemach** [comment]
cron job executing shell file:

`#!/bin/bash

DATESTAMP=$(date +"%F")
BACKUP_DIR="/var/opt/mssql/backup/$DATESTAMP"
S3_DIR="s3://thcgdbasebackups"
SA_USER="sa"
SA_PASS="somepassword"

/bin/mkdir -p $BACKUP_DIR
/bin/chown -R mssql:mssql $BACKUP_DIR

/opt/mssql-tools/bin/sqlcmd -Q "EXECUTE dbo.DatabaseBackup 
@Databases = 'USER_DATABASES', 
@Directory = '$BACKUP_DIR', 
@BackupType = 'DIFF', 
@DirectoryStructure = NULL, 
@AvailabilityGroupDirectoryStructure = NULL, 
@FileName='{DatabaseName}_{Year}{Month}{Day}.{FileExtension}',
@Compress = 'Y',
@LogToTable = 'Y'" -U $SA_USER -P $SA_PASS

/usr/bin/aws s3 sync "$BACKUP_DIR" "$S3_DIR/$DATESTAMP/diff" --storage-class "STANDARD_IA"

/bin/rm $BACKUP_DIR/*

/opt/mssql-tools/bin/sqlcmd -Q "EXECUTE dbo.DatabaseBackup 
@Databases = 'SYSTEM_DATABASES', 
@Directory = '$BACKUP_DIR', 
@BackupType = 'FULL', 
@DirectoryStructure = NULL, 
@AvailabilityGroupDirectoryStructure = NULL, 
@FileName='{DatabaseName}_{Year}{Month}{Day}.{FileExtension}', 
@Compress = 'Y',
@LogToTable = 'Y'" -U $SA_USER -P $SA_PASS

/usr/bin/aws s3 sync "$BACKUP_DIR" "$S3_DIR/$DATESTAMP/full" --storage-class "STANDARD_IA"

/bin/rm -R $BACKUP_DIR`

**Comment by Daemach** [comment]
There are actually 3 scripts - let me know if you want the other 2.

**Comment by olahallengren** [comment]
Thank you.

Now what happens if you enable ```@Verify = 'Y'```?

**Comment by olahallengren** [comment]
I have tested to perform a backup with verify on SQL Server on Linux. It works well in my testing.

It looks like there has been some problem with permissions on your server.
