### ISSUE TITLE
Install-All-Scripts missing objects

### ISSUE THREAD

**Issue by TDK1964** [olahallengren/sql-server-maintenance-solution#29]
The module 'sp_DatabaseRestore' depends on the missing object 'dbo.CommandExecute'. The module will still be created; however, it cannot run successfully until the object exists.

The module 'sp_AllNightLog' depends on the missing object 'master.dbo.DatabaseBackup'. The module will still be created; however, it cannot run successfully until the object exists.

**Comment by BlitzErik** [comment]
Tim, Ola doesn't support sp_DatabaseRestore, we do in our [GitHub repo](firstresponderkit.org). 

We also don't distribute Ola's scripts with our First Responder Kit scripts and don't have any plans to do so.

**Comment by TDK1964** [comment]
OK thanks
