### ISSUE TITLE
Jobs don't make a Output file

### ISSUE THREAD

**Issue by Spurs12345** [olahallengren/sql-server-maintenance-solution#297]
I have download and executed the MaintenanceSolution.sql script. 
When I take a look at the jobs (for example 'DatabaseBackup - SYSTEM_DATABASES - FULL') I notice that the Output file is stored in: $(ESCAPE_SQUOTE(SQLLOGDIR))\$(ESCAPE_SQUOTE(JOBNAME))_$(ESCAPE_SQUOTE(STEPID))_$(ESCAPE_SQUOTE(DATE))_$(ESCAPE_SQUOTE(TIME)).txt

But when I execute this job, no file is written to the logdir. 
Change (JOBNAME) to (JOBID) works, a file is nicely written to the logdir (but jobid is not an friendly name).
Has anyone ran into the same problem? And how can I make it work that JOBNAME can be used?

**Comment by olahallengren** [comment]
What version is this (```SELECT @@VERSION```)?

What is the name of the job in our environment?

**Comment by olahallengren** [comment]
I know that if the job name contains a character that is now allowed in the file system, and you are using the token JOBNAME, then you will get no output - file at all.

**Comment by Spurs12345** [comment]
That did the trick.
I had a - in the jobname.
Thanks!

**Comment by olahallengren** [comment]
Here you can see the characters that are not allowed in the file system in Windows:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

"-" should work fine.

**Comment by Spurs12345** [comment]
I'm sorry, but you're wright.....
I had a : in the jobname. Change it to -, and it works.....
