### ISSUE TITLE
Object level Recovery Map for Litespeed variable to be added

### ISSUE THREAD

**Issue by Dkruge** [olahallengren/sql-server-maintenance-solution#298]
Hi, 

i use litespeed as a 3rd party backup tool and noticed OLRMAP is missing from the code which could be added easily and makes a huge difference for performance for Object level recovery in litespeed. 
i would like to see this added permanent as to be able to enable or disable this feature. 
for now on my script i have added manually as below: 
          WHEN @CurrentBackupType IN('DIFF','FULL') THEN 'DECLARE @ReturnCode int EXECUTE @ReturnCode = [master].dbo.xp_backup_database @olrmap = 1, @database = N''' + REPLACE(@CurrentDatabaseName,'''','''''') + ''''
          WHEN @CurrentBackupType = 'LOG' THEN 'DECLARE @ReturnCode int EXECUTE @ReturnCode = [master].dbo.xp_backup_log @olrmap = 1, @database = N''' + REPLACE(@CurrentDatabaseName,'''','''''') + ''''

as stated by litespeed in the user guide 
"LiteSpeed may take a long time to read the backup file for large databases, often with little response in the LiteSpeed UI Console. To prevent this, the Optimize Object Level Recovery speed option on the Backup wizard Options page is selected by default to create the index during the backup"

It is not selected by default when xp_backup_database is ran manually the paramter @OLRMAP = 1 must be added. 
https://support.quest.com/litespeed-for-sql-server/kb/14507/what-is-the-lsm-file-that-gets-created-with-the-backup-file-and-can-it-be-deleted-

this explains a file which creates also as people will see a file added. 

i used a 30GB database as an example and before OLRMAP 4 minutes 6 seconds to read the backup file. With OLRMAP enabled it took 3 seconds. :) imagine larger databases. 
Thanks 
Danny Kruge

**Comment by olahallengren** [comment]
I have added this now. Please try it out.
https://ola.hallengren.com/versions.html

https://ola.hallengren.com/sql-server-backup.html#ObjectLevelRecoveryMap
