### ISSUE TITLE
Procedure output shows Updateability: READ_WRITE on the secondary replica in an Availability Group

### ISSUE THREAD

**Issue by timweigel** [olahallengren/sql-server-maintenance-solution#300]
**Description of the issue**
On a secondary replica in an availability group on SQL Server 2014 SP3, the is_read_only value for a, AG database in sys.databases is 0, but the value returned by DATABASEPROPERTYEX is READ_ONLY. This discrepancy causes an incorrect value returned in the output. 

As the check for whether the commands should be executed or not is against the DATABASEPROPERTYEX value, IndexOptimize correctly doesn't attempt to execute anything on a secondary replica, but the output in the history is based on the @CurrentIsReadOnly value, which is gathered from sys.databases.

While I encountered this in IndexOptimize, it looks like this is also the case in DatabaseBackup and IntegrityCheck based on the code.

**SQL Server version and edition**
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64) 
	Sep  7 2018 01:37:51 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Version of the script**
2019-06-14 00:05:34  

**What command are you executing?**
IndexOptimize

**What output are you getting?**
Date and time: 2019-11-14 11:00:25  
Database: [<my database>]  
State: ONLINE  
Standby: No  
Updateability: READ_WRITE  <-- this should be READ_ONLY
User access: MULTI_USER  
Is accessible: Yes  
Recovery model: FULL  
Availability group: <my AG> 
Availability group role: SECONDARY

**Comment by olahallengren** [comment]
Is it only the logging that you would like to have changed?
Are the stored procedures working as they should otherwise?

**Comment by timweigel** [comment]
This is the only logging issue we’ve run across, thanks. The procs are all working as expected.

**Comment by d3m1sc0** [comment]
Hello,

I have similar issue on running this command:

EXECUTE [dbo].[DatabaseIntegrityCheck] @Databases = 'USER_DATABASES'

on the standby. 
This returns the following error:

Msg 976, Level 14, State 1, Procedure usp_CommandExecute, Line 194 [Batch Start Line 0]
The target database, 'dbname', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

So the integrity checks are not run against the standby dbs.

One interesting finding: the following command runs as expected:

DECLARE @Command nvarchar(max)
set @Command = 'DBCC CHECKDB ([dbname]) WITH NO_INFOMSGS, ALL_ERRORMSGS, DATA_PURITY'
EXECUTE (@Command)

whereas the following fails with the above mentioned message:
EXECUTE @sp_executesql @Command

**Comment by olahallengren** [comment]
@d3m1sc0, this is a different issue. Could I ask you to submit a new issue (bug report). I will investigate it a bit later today.
https://github.com/olahallengren/sql-server-maintenance-solution/issues/new/choose

**Comment by olahallengren** [comment]
@d3m1sc0, before submitting the bug report, could you download the very latest version and test again. The issue that you are experiencing looks similar to a bug that I fixed some days ago.

**Comment by d3m1sc0** [comment]
The version i am using is this:  Version: 2020-01-05 15:00:38    

Should i try newer? I went through the code of the version "2020-01-08 20:52:41" and it looks similar, but i could give it a try. Let me know

**Comment by d3m1sc0** [comment]
I downloaded the versions Version: 2020-01-09 23:10:28  for both CheckDatabaseIntegrity and CommandExecute.
Same issue as mentioned in my first message

**Comment by d3m1sc0** [comment]
I submitted the issue #326

**Comment by olahallengren** [comment]
The intention is to display the columns from sys.databases in the logging.
https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sql-server-ver16
I could consider calling it IsReadOnly instead of Updateability to make it more clear where it is coming from.

In the code in IndexOptimize, I use `DATABASEPROPERTYEX(@CurrentDatabaseName,'Updateability') = 'READ_WRITE'` in the check for whether I should process the database or not. The reason for that is that it returns the effective updateability (also taking availability group role into account). I could consider checking @CurrentIsReadOnly in combination with @CurrentAvailabilityGroupRole here instead to make it more clear.

**Comment by olahallengren** [comment]
I have created a pull request to improve this: #852

**Comment by olahallengren** [comment]
I have released this now.  @timweigel thank you for reporting it.
