### ISSUE TITLE
 number of checkdb errors

### ISSUE THREAD

**Issue by lpalummo** [olahallengren/sql-server-maintenance-solution#301]
**Description of the issue**
The checkdb job logs a single error in the CommandLog table even if the checkdb fails with more errors.

**SQL Server version and edition**
ALL version

**Version of the script**
Version: 2019-06-14 00:05:34

**What command are you executing?**

**What output are you getting?**

**Comment by lpalummo** [comment]
I implemented a modification to the DatabaseIntegrityCheck.sql and CommandExecute.sql script in my work environment
in order to execute the DBCC CHECKDB command ([database name]) WITH ALL_ERRORMSGS, DATA_PURITY, TABLERESULTS and capture all possible errors returned.
I'm going to store in a new table with FOREIGN KEY ([CommandLogId]) REFERENCES [dbo]. [CommandLog] ([ID]).

**Comment by olahallengren** [comment]
You will see all errors in the output - file.

I am not using WITH TABLERESULTS, as that is an undocumented argument in the DBCC CHECKDB command.
