### ISSUE TITLE
Spaces in the Fragmentation Action input parameter values for IndexOptimize

### ISSUE THREAD

**Issue by jacobgexigo** [olahallengren/sql-server-maintenance-solution#302]
At line 745 of the IndexOptimize proc, you start checking input parameters for validity.  If a user accidentally adds a space between the comma and next value for @FragmentationLow/Medium/High, it just throws an error saying the parameter value isn't supported, which is confusing.  It's easy to accidentally add spaces because that's how we are used to programming.

Could we either do a REPLACE and remove the spaces to make the input more accurate OR throw a meaningful error telling the user that they need to remove spaces from the input?

**Example:** 
@FragmentationLow ='INDEX_REBUILD_ONLINE, INDEX_REBUILD_OFFLINE'
That space in the actions above will throw the generic error.

**Comment by olahallengren** [comment]
I have changed so that it now works with a space after the comma.
