### ISSUE TITLE
Allow Log Shipped primary databases to have a Tail Log Backup taken

### ISSUE THREAD

**Issue by RobAshton-IM** [olahallengren/sql-server-maintenance-solution#303]
I'm trying to use the DatabaseBackup procedure as part of my strategy for automating Log Shipping failovers across my company's SQL Server platform, but discovered that the stored procedure explicitly (and silently!) does not take a log backup of a database if it is the primary for Log Shipping.

It would be useful for an exception to be added to DatabaseBackup so that it would take a log backup of a Log Shipping primary database if:
1. The database is online.
2. The database is a primary for Log Shipping.
3. The Log Shipping Backup Job is disabled.
4. The @NoRecovery parameter is set to 'Y' to indicate a Tail Log Backup is being taken.

**Comment by RobAshton-IM** [comment]
I envision this being an additional check being made after the check for the Log Shipping status of the database. I'll see if I can get a pull request together to demonstrate what I mean.

**Comment by olahallengren** [comment]
Wouldn't this break the Log Shipping?

**Comment by RobAshton-IM** [comment]
Yes, but it's a necessary step to guarantee no data loss in a controlled failover of Log Shipping.

**Comment by olahallengren** [comment]
Does Log Shipping in SQL Server not have any support for the tail log backup?

**Comment by RobAshton-IM** [comment]
Setting up Log Shipping and monitoring it are both handled by tooling from MS, but the failover process is still a manual one.

I'm trying to set up an automated mechanism to manage it over the 100+ instances I have to manage, hence why I want to simplify the tail log backup step with your solution since I already use it a few other parts of my overall strategy and it would make for a consistent approach.

**Comment by olahallengren** [comment]
Thank you for explaining. I understand your requirement.

I am just concerned that if I allow this, then someone might accidentally break Log Shipping.

**Comment by RobAshton-IM** [comment]
Totally understood Ola, though if you're asking for a tail-log backup to be taken of a log-shipped database, then it can be presumed that you're intending to break Log Shipping :)

Would it be more comfortable if the solution had an independent switch to indicate the intent to failover Log Shipping, rather than it being inferred from the state of the database, its Log Shipping backup job's state, and the parameters set on the DatabaseBackup call?

**Comment by olahallengren** [comment]
>Totally understood Ola, though if you're asking for a tail-log backup to be taken of a log-shipped database, then it can be presumed that you're intending to break Log Shipping :)

Well, it could be that the intention is just to perform a tail-log backup of the databases that are not log shipped.

>Would it be more comfortable if the solution had an independent switch to indicate the intent to failover Log Shipping, rather than it being inferred from the state of the database, its Log Shipping backup job's state, and the parameters set on the DatabaseBackup call

This could be an option, but if you need this now you have to do a small customization.

I think that the best would be if the SQL Server Log Shipping feature had an option to do a tail-log backup. Then the tail-log backups would automatically get into the right directories, automatically be restored and so on. Is there a SQL Server request for this on User Voice?

**Comment by RobAshton-IM** [comment]
> Well, it could be that the intention is just to perform a tail-log backup of the databases that are not log shipped.

Hence the check against the primary database's Log Shipping backup job's status. If it isn't running, it's safe to take a tail-log backup without breaking Log Shipping since reverting that DB from RECOVERING to ONLINE should be as simple as calling "ALTER DATABASE <db_name> SET ONLINE = ON;" then setting the Log Shipping backup job to be enabled.

> I think that the best would be if the SQL Server Log Shipping feature had an option to do a tail-log backup. Then the tail-log backups would automatically get into the right directories, automatically be restored and so on. Is there a SQL Server request for this on User Voice?

Not than I know of. Whilst Log Shipping is one of the non-deprecated DR options in SQL Server, it hasn't changed much at all in many, many versions, so I doubt they'd be willing to plumb in this sort of new functionality, especially when it's one of the many reasons that AlwaysOn is a preferred feature for DR as far as MS are concerned.

**Comment by olahallengren** [comment]
>Hence the check against the primary database's Log Shipping backup job's status.

Sorry, I missed that. I will think some more about it.

>Not than I know of. Whilst Log Shipping is one of the non-deprecated DR options in SQL Server, it hasn't changed much at all in many, many versions, so I doubt they'd be willing to plumb in this sort of new functionality, especially when it's one of the many reasons that AlwaysOn is a preferred feature for DR as far as MS are concerned.

Well, someone has to ask for it, for them to consider it. :smile:

**Comment by olahallengren** [comment]
I have added a parameter that would allow this.
https://ola.hallengren.com/sql-server-backup.html#ExcludeLogShippedFromLogBackup
