### ISSUE TITLE
LogSizeSinceLastLogBackup and backup on secondary replica

### ISSUE THREAD

**Issue by kroilia** [olahallengren/sql-server-maintenance-solution#305]
Hello,  
I'm having an issue with the use of the @LogSizeSinceLastLogBackup parameter with the databasebackup sp. 
here is my statement I run:  
EXEC [dbo].[DatabaseBackup]   
@Databases = 'MyDb'  
, @Directory = '\\\bkpserver\'  
, @BackupType = 'LOG'  
, @Verify = 'Y'  
, @CleanupTime = 336  
, @Compress = 'Y'   
, @Encrypt = 'Y'  
, @EncryptionAlgorithm = 'AES_256'  
, @ServerCertificate = 'MyCert'  
, @LogSizeSinceLastLogBackup = 1024 --1gb  
, @TimeSinceLastLogBackup = 1800 -- 30 mins  
, @LogToTable = 'Y' 

But if i run this command multiple times in a row, the backup will create  new file at every occurrence.  
So i checked at the function dm_db_log_stats,and here is the result :   
database_id	recovery_model	log_min_lsn	log_end_lsn	current_vlf_sequence_number	current_vlf_size_mb	total_vlf_count	total_log_size_mb	active_vlf_count	active_log_size_mb	log_truncation_holdup_reason	log_backup_time	log_backup_lsn	log_since_last_log_backup_mb	log_checkpoint_lsn	log_since_last_checkpoint_mb	log_recovery_lsn	log_recovery_size_mb	recovery_vlf_count
8	FULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	2019-12-06 14:15:05.950	NULL	NULL	NULL	NULL	NULL	NULL	NULL

There is no record for the database in the function, that explains the fact he make the backup every time. Am I missing something ?

**SQL Server version and edition**
Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64) 

**Version of the script**
Version: 2019-12-01 21:32:32

**Comment by kroilia** [comment]
The reason is explicitly written on msdn : 
![image](https://user-images.githubusercontent.com/20705239/70327460-228aa180-1837-11ea-910d-51e1450e774a.png)
[source msdn](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-log-stats-transact-sql?view=sql-server-2017)
I'll try to fix it and create pull request when done

**Comment by kroilia** [comment]
I created the pull request to fix this issue
https://github.com/olahallengren/sql-server-maintenance-solution/pull/306

**Comment by olahallengren** [comment]
Unfortunately sys.dm_db_log_stats has this limitation.

Could you describe how you would like my stored procedure to work in this scenario?

As it works now, if DatabaseBackup does not get any information from the function, then it will perform a backup.

**Comment by kroilia** [comment]
Thank you for your answer. 
As the dm_db_log_stats fn doesn't work on secondary, it is impossible to rely on the LogSizeSinceLastLogBackup and TimeSinceLastLogBackup values to make intelligent backups.
I found a solution that works actually on my instances : I chose to rely on the function on the primary replicate. Even though I backup on a secondary replicate, the information is updated on the primary. I created a pull request with my actual version of the script. You can find it in the PR #306.

**Comment by olahallengren** [comment]
Thank you, @kroilia.

I was looking at the pull request. The downside with using linked servers is just that it makes the configuration a bit more complex.

**Comment by olahallengren** [comment]
I have documented the current behavior.
https://ola.hallengren.com/sql-server-backup.html#LogSizeSinceLastLogBackup
https://ola.hallengren.com/sql-server-backup.html#TimeSinceLastLogBackup

**Comment by olahallengren** [comment]
@kroilia, thank you for your work on this, but I am not planning to use linked servers.

Hopefully Microsoft will improve sys.dm_db_log_stats in a future version of SQL Server, so that it returns information on the secondary.
