### ISSUE TITLE
RESAMPLE - Incorrect Syntax

### ISSUE THREAD

**Issue by js0505** [olahallengren/sql-server-maintenance-solution#31]
When a RESAMPLE occurs, it fails because of incorrect syntax. The solution is to include WITH before RESAMPLE. I will take this and update and create a PR after testing.

**Comment by olahallengren** [comment]
This issue should be fixed in the 25 Sep 2016 release. Could you please test again with the latest version, and send me a repro if you are still getting the error.

**Comment by js0505** [comment]
Issue looks to be resolved in latest release.
