### ISSUE TITLE
Maintenance Success Or Failure

### ISSUE THREAD

**Issue by owhitehouse-asti** [olahallengren/sql-server-maintenance-solution#310]
Ola, this is a very useful set of tools you have provided to the SQL community. Thank you!

I was wondering if you had any recommendations for some notification to SQL admins on completion of the maintenance stored procedures. It would be nice to have a log sent via email so the admin can feel assured that the databases are being maintained automatically.

Thanks again!
Owen

**Comment by Thomas-S-B** [comment]
Hello Owen,

sorry for my interruption, i don't want to annoy you - perhaps this is helpful for you:
https://github.com/Thomas-S-B/SQLServerTools/blob/master/HallengrenHeaviestMail.sql
This sends an email, which shows in a table the heaviest updates from the "Hallengren commandlog".

BTW: Thank you Ola - this is such a beautiful project!

Cheers
Thomas

**Comment by owhitehouse-asti** [comment]
Hi Thomas,

No annoyance at all, this is very helpful! Once I get my test environment up and running, I may want to tweak this with options in the subject line to notify the Admin that all scripts ran successfully, or alternatively, warn if one of them threw an error. After all, a maintenance plan really should include an audit, since not all DBAs stop by the server every day to read the logs.

Thank you for the script!

Owen

**Comment by olahallengren** [comment]
You could configure SQL Server Agent to send a mail on job failure or job completion.

https://docs.microsoft.com/en-us/sql/ssms/agent/job-properties-new-job-notifications-page?view=sql-server-ver15

https://docs.microsoft.com/en-us/sql/relational-databases/database-mail/configure-sql-server-agent-mail-to-use-database-mail?view=sql-server-ver15
