### ISSUE TITLE
Procedure does not catch severe database error and stops processing backups.

### ISSUE THREAD

**Issue by SlavaSQL** [olahallengren/sql-server-maintenance-solution#311]
In case of a single database has severe internal error, which produces errors higher than 16, the "DatabaseBackup" procedure just trows it out and stops processing all other databases in the queue.

**SQL Server version and edition**
`Microsoft SQL Server 2014 (SP2-GDR) (KB4505217) - 12.0.5223.6 (X64)   May 26 2019 20:36:50   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) `

**Version of the script**
  --// Version: 2019-06-14 00:05:34                                                               //--  

**What command are you executing?**
```
	EXECUTE [dbo].[DatabaseBackup]
	@Databases = 'Temp_Failure, Another_Database',
	@Directory = '\\ABC\SQLServerDev\',
	@DirectoryStructure = '{ServerName}{DirectorySeparator}{InstanceName}{DirectorySeparator}{BackupType}{DirectorySeparator}{DatabaseName}{DirectorySeparator}',
	@FileName = '{DatabaseName}_{Description}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}',
	@Compress = 'N',
	@Encrypt = 'N',
	@BackupType = 'FULL',
	@Verify = 'Y',
	@CleanupTime = NULL,
	@CheckSum = 'Y',
	@LogToTable = 'Y',
	@Description = 'db';
```

**What output are you getting?**
```
Date and time: 2019-12-18 10:34:36
Command: BACKUP DATABASE [Temp_Failure] TO DISK = N'\\ABC\SQLServerDev\ServerName\Instance\FULL\Temp_Failure\Temp_Failure_db_20191218_103436.bak' WITH CHECKSUM, NO_COMPRESSION, DESCRIPTION = N'db'
Msg 3013, Level 16, State 1, Line 23
BACKUP DATABASE is terminating abnormally.
Outcome: Failed
Duration: 00:00:00
Date and time: 2019-12-18 10:34:36
	
Date and time: 2019-12-18 10:34:36
	
Msg 829, Level 21, State 1, Line 23
**Database ID 15, Page (1:2) is marked RestorePending, which may indicate disk corruption. To recover from this state, perform a restore.**

```
**How to reproduce the issue**
`DBCC WRITEPAGE ('Temp_Failure',1,2, 1, 8, 0xFFFFFFFFFFFFFFFF);
`

**Comment by MichelZ** [comment]
That would probably be a good feature request.
"Continue Backup On Errors" or something like this.

**Comment by olahallengren** [comment]
@SlavaSQL , could you reproduce it again, and this time also include the information about the database in the output. I am especially interested in the database state. Was it ONLINE, even though the error message says RestorePending?

**Comment by olahallengren** [comment]
I am aware of the issue that some rare errors that are batch-aborting, are aborting the stored procedure execution. Unfortunately, there is nothing that I can do about that.

**Comment by SlavaSQL** [comment]
I believe the database is still online.
To reproduce just run command "DBCC WRITEPAGE ('Temp_Failure',1,2, 1, 8, 0xFFFFFFFFFFFFFFFF);"
I did not go deep into, but I think the problem is that "CommandExecute" raises a severe error and DatabaseBackup does not have a try-catch block on it.
I might be able to fix it myself, but would like to have it in your solution and well tested and approved by others.

**Comment by olahallengren** [comment]
I am able to reproduce it now. I will do some testing. Thank you for reporting this issue.

**Comment by SlavaSQL** [comment]
Thanks Ola for your job!!!

**Comment by olahallengren** [comment]
Could I ask you how you are executing DatabaseBackup?
A SSMS query window? A T-SQL job step? A CmdExec job step with sqlcmd?

**Comment by SlavaSQL** [comment]
T-SQL job step. Wrapping it in the additional TRY-Catch block

**Comment by olahallengren** [comment]
Could you try without wrapping the stored procedure call in TRY CATCH?

In my testing, it is working as it should then.

**Comment by SlavaSQL** [comment]
It works fine without TRY-CATCH. That is why simple tests always worked.
Is it how it is supposed to be?

**Comment by olahallengren** [comment]
If you execute DatabaseBackup (or any of the other stored procedures in the maintenance solution) from a TRY block, then the error handling will not work as designed.

**Comment by olahallengren** [comment]
The problem is that if the stored procedure is executed in a TRY block, then it will abort execution if there is an error.

**Comment by SlavaSQL** [comment]
I assume that is a feature. 
So, it would be nice to have that mentioned on the main description page as "Do not wrap the procedure into Try-Catch block"
I think issue can be closed, if there is no other objections.
Thank you very much.

**Comment by olahallengren** [comment]
I added it to the Frequently Asked Questions.
"The job stops executing after the first error. What could the reason be?"
https://ola.hallengren.com/frequently-asked-questions.html

**Comment by SlavaSQL** [comment]
Ola, thank you again.
