### ISSUE TITLE
error during installl 

### ISSUE THREAD

**Issue by mauricioQrails** [olahallengren/sql-server-maintenance-solution#313]
**Description of the issue**
the install script fails with 3 errors.

**SQL Server version and edition**
Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64)   Nov 27 2019 18:09:22   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

**Version of the script**
Check the header of the stored procedure
Version: 2019-12-26 15:59:04

**What command are you executing?**
MaintenanceSolution.sql

**What output are you getting?**

Msg 319, Level 15, State 1, Procedure DatabaseIntegrityCheck, Line 1532 [Batch Start Line 3725]
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Procedure DatabaseIntegrityCheck, Line 1708 [Batch Start Line 3725]
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 319, Level 15, State 1, Procedure IndexOptimize, Line 1621 [Batch Start Line 5505]
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.

**Comment by mauricioQrails** [comment]
![error](https://user-images.githubusercontent.com/36901289/71491370-8c221e00-27ed-11ea-8552-ce955ef76ece.jpg)

**Comment by mauricioQrails** [comment]
those are the errors I get in my SMSS 18.1

**Comment by mauricioQrails** [comment]
I figured out the issue. 
it seems to be a Microsoft issue with **"Column Encryption Setting=enabled"** . when I took out this setting from the connection in SMSS then the scripts worked just fine. 
Thank you so much to Ola for pointing me to the right direction

**Comment by olahallengren** [comment]
It is really good that you found out about this issue. Thank you for reporting back.
