### ISSUE TITLE
Support for SQL Server 2005

### ISSUE THREAD

**Issue by olahallengren** [olahallengren/sql-server-maintenance-solution#317]
When I started on this project in 2008, I supported SQL Server 2005, that was the latest version at that time. Since then I have added support for SQL Server 2008 to SQL Server 2019.

SQL Server 2005 was going end of support in 2016.
https://www.microsoft.com/en-us/sql-server/sql-server-2005

SQL Server 2008 and SQL Server 2008 R2 was going end of support in 2019. However Microsoft announced that you could get Extended Security Updates for 3 more years.
https://azure.microsoft.com/mediahandler/files/resourcefiles/end-of-support-sql-server-and-windows-server-2008-and-2008-r2/Windows_Server_2008_SQL_Server_2008_End_of_Support_Security_Brief.pdf

The question is how long I should support old versions of SQL Server in the maintenance solution.

On one hand it is nice for customers to be able to use the same version of the script on all their servers. On the other hand it means that I can't take advantage of new features in T-SQL.  Supporting many versions also makes testing complex.

- I am thinking about dropping support for SQL Server 2005 in the main version of the maintenance solution.
- I will continue to support SQL Server 2008 and SQL Server 2008 R2.
- Users will still be able to download the latest SQL Server 2005 - compatible version of the script.

Are you using SQL Server 2005 in your organization? Do you have customers that are using it? Do you see any problem of SQL Server 2005 not being supported in the main version?

Any feedback on this is greatly appreciated.

**Comment by deckTECHeu** [comment]
Jo Ola !
Thanks for that Topic. I do not support SQL Server 2005, thought still there are few SQL 2008 which I have to take care. Generally speaking I do not see any need for longer support than Microsoft. Most of the company if not all cannot take the risk to run unsupported SQL Server versions so if you keep support for your brilliant maintenance solution at the same level as Microsoft will be more than enough.

**Comment by olahallengren** [comment]
I have made made an update that is using features that are not available on SQL Server 2005. I have removed SQL Server 2005 from the list of supported versions.

The last version that is supported on SQL Server 2005 is available here:
https://github.com/olahallengren/sql-server-maintenance-solution/tree/292242a8bf4cb1cc72253a54e4f38f29c8c79119
