### ISSUE TITLE
Inability to capture an error

### ISSUE THREAD

**Issue by SlavaSQL** [olahallengren/sql-server-maintenance-solution#319]
Accordingly to an issue #311 I removed Try-Catch wrapper around backup procedure and had an issue.

Here is what happened:
1.The original deployment of scripts was version of 2019-06-14 00:05:34 (DB Backup + CommandExecute)
2. On Jan 2 tried to deploy "DatabaseIntegrityCheck" of the newest version of 2020-01-02 20:43:38
3. During the test the procedure failed complaining n the old version of CommandExecute procedure.
4. After installing new "CommandExecute", "DatabaseIntegrityCheck" worked fine.
5. This morning I realized that my Backup job is failing because the newest "CommandExecute" procedure required new @DatabaseContext parameter, which was not supplied by old DatabaseBackup procedure.

THE ERROR:
Msg 201, Level 16, State 4, Procedure CommandExecute, Line 0 [Batch Start Line 2]
Procedure or function 'CommandExecute' expects parameter '@DatabaseContext', which was not supplied.

I understand that it was my negligence with having different versions and not properly testing it (all processes still run in dev) and I'm glad that this issue was uncovered so early and we can address it during the migration. 
However, we have a big question on how to handle an error within a job.
We can't use Try-Catch, because it interrupts the process, but without Try-Catch block we are not able to intercept any errors, originated by the proc.

So, I'd suggest to use Try-Catch block within DatabaseBackup procedure for CommandExecute calls.
That will allow DatabaseBackup procedure not fail and return an error to calling job or procedure.

Thanks.

**Comment by olahallengren** [comment]
>We can't use Try-Catch, because it interrupts the process, but without Try-Catch block we are not able to intercept any errors, originated by the proc.

Could you explain a bit more what you would like to do.
Is the goal just that the backup job should report failure, if the stored procedure fails?

**Comment by SlavaSQL** [comment]
The goal is to not report "job failure" if backup procedure fails, but process it within the same job step and send a notification about it.

See below what I'm trying to do. In case of a single (or multiple) database backup errors I try to capture numbers of processed databases and report failed databases.
`
```
/* Database's Full Backup 
Developed by Slava Murygin based on Ola Hallengren scripts
Implemented by the configuration script "0450_Ola_Hallengren_Create_Full_Backup_Job_1.sql"
*/
DECLARE @Error INT = 0, @LastID INT, @MaxID INT;
DECLARE @ErrorMessage NVARCHAR(MAX);
DECLARE @DBCount INT, @Processed INT;
DECLARE @Operator_Name nvarchar(3);
DECLARE @Operator_email nvarchar(50);
DECLARE @Subject nvarchar(250);
DECLARE @BodyText nvarchar(max);
DECLARE @Databases nvarchar(max);
DECLARE @Directory NVARCHAR(255);
DECLARE @DirectoryStructure NVARCHAR(255);
DECLARE @AvailabilityGroupDirectoryStructure NVARCHAR(255);
DECLARE @FileName NVARCHAR(255);
DECLARE @FailedDBList NVARCHAR(MAX);

SELECT @Databases = 'USER_DATABASES'
	, @Directory = '\\ABCXYZ\SQLServerDev'
	, @DirectoryStructure = '{ClusterName}{DirectorySeparator}{ServerName}{DirectorySeparator}{InstanceName}{DirectorySeparator}{BackupType}{DirectorySeparator}{DatabaseName}{DirectorySeparator}'
	, @AvailabilityGroupDirectoryStructure = '{ClusterName}{DirectorySeparator}AGs{DirectorySeparator}{AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}'
	, @FileName = '{DatabaseName}_{Description}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}'
	, @FailedDBList = '';

/* GET Mailing address */
SELECT @Operator_name = 'DBA'
SELECT @Operator_email = email_address 
FROM msdb.dbo.sysoperators WHERE name = @Operator_name;

/* Get previous CommandLog MAX ID */
SELECT @LastID = IsNull(MAX(ID), 0)
FROM DBA_Pro.[dbo].[CommandLog];

/* Get approximate count of databases to be processed */
SELECT @DBCount = CASE @Databases
	WHEN 'ALL_DATABASES' THEN (SELECT COUNT(*)-1 FROM master.sys.databases WHERE state = 0)
	WHEN 'SYSTEM_DATABASES' THEN 3
	WHEN 'USER_DATABASES' THEN (SELECT COUNT(*) FROM master.sys.databases WHERE state = 0 and database_id > 4)
	ELSE LEN(@Databases) - LEN(REPLACE(@Databases,',','')) + 1 END;

/* Here perform Ola's scripts */
EXECUTE DBA_Pro.[dbo].[DatabaseBackup]
@Databases = @Databases,
@Directory = @Directory,
@DirectoryStructure = @DirectoryStructure,
@AvailabilityGroupDirectoryStructure = @AvailabilityGroupDirectoryStructure,
@FileName = @FileName,
@Compress = 'Y',
@Encrypt = 'N',
@BackupType = 'FULL',
@Verify = 'Y',
@CleanupTime = NULL,
@CheckSum = 'Y',
@LogToTable = 'Y',
@Description = 'db';

IF @@ERROR > 0
BEGIN
	SELECT @Error = @@ERROR, @ErrorMessage = ERROR_MESSAGE();
	PRINT @ErrorMessage;
END

/* Get Most recent CommandLog MAX ID */
SELECT @MaxID = IsNull(MAX(ID), 0)
FROM DBA_Pro.[dbo].[CommandLog];

/*
Check if any Backup error happened during the Ola's script
*/
IF @Error > 0 OR EXISTS (
	SELECT TOP 1 1 FROM DBA_Pro.[dbo].[CommandLog]
	WHERE ID > @LastID AND ID <= @MaxID
		AND IsNull(ErrorNumber,1) != 0 
		AND CommandType like 'BACKUP%')
BEGIN

	;WITH E as (
		SELECT DatabaseName, Errors = SUM(ErrorNumber) 
		FROM DBA_Pro.[dbo].[CommandLog]
		WHERE ID > @LastID AND ID <= @MaxID AND CommandType like 'BACKUP%'
		GROUP BY DatabaseName
	)
	SELECT @Processed = COUNT(*) FROM E WHERE Errors = 0;

	SELECT @FailedDBList = @FailedDBList + QUOTENAME(IsNull(DatabaseName,'Unknown')) + ','
	FROM DBA_Pro.[dbo].[CommandLog]
	WHERE ID > @LastID AND IsNull(ErrorNumber,1) != 0 AND CommandType like 'BACKUP%'
	SELECT @FailedDBList = LEFT(@FailedDBList,LEN(@FailedDBList)-1)

	SET @BodyText = IsNull(CAST((
		SELECT TD = IsNull(DatabaseName,'Unknown'), ''
			, TD = CASE CommandType
				WHEN 'BACKUP_DATABASE' THEN 'Full'
				WHEN 'BACKUP DATABASE WITH DIFFERENTIAL' THEN 'Diff'
				WHEN 'BACKUP_LOG' THEN 'Log'
				ELSE 'Unknown' END
			FROM DBA_Pro.[dbo].[CommandLog]
			WHERE ID > @LastID AND IsNull(ErrorNumber,1) != 0 AND CommandType like 'BACKUP%'
		FOR XML PATH('TR') 
	) AS NVARCHAR(MAX)),'')

	SELECT @Subject = 'Database Backup(s) Failed on '+  @@SERVERNAME
		, @BodyText ='<html><body>
			<H4>' + CONVERT(VARCHAR(24),GetDate(),121) + '</H4>
			<H3>Error: <FONT Color="RED">' + IsNull(@ErrorMessage,'Databases Failed To Backup') 
				+ '</FONT></H3>
			<H4>Approximate execution statistcs:</H4>
			<H5>Databases to Process: <FONT Color="BLUE">' + CAST(@DBCount as VARCHAR) + '</FONT></H5>
			<H5>Processed Databases: <FONT Color="RED">' + CAST(@Processed as VARCHAR) + '</FONT></H5>
			' + CASE @BodyText WHEN '' THEN '' ELSE '
			<HR><H3>Errored Database(s):</H3>
			<table border = 1> 
			<tr>
				<th> Database </th>
				<th> BackupType </th>
			</tr>' + @BodyText +'</table>' 
			END + '<H4>To get Logged data run following script:</H4>
			<table border = 1><tr><td><FONT COLOR="BLUE">SELECT</FONT> ID, c.DatabaseName, c.CommandType, c.StartTime, c.EndTime<BR>
 &nbsp &nbsp , Duration = <FONT COLOR="BLUE">CASE</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp <FONT COLOR="BLUE">WHEN</FONT> <FONT COLOR="FUCHSIA">DATEDIFF</FONT>(<FONT COLOR="FUCHSIA">SECOND</FONT>,c.StartTime,c.EndTime) >= 3600 <FONT COLOR="BLUE">THEN</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp  &nbsp &nbsp <FONT COLOR="FUCHSIA">CAST</FONT>(<FONT COLOR="FUCHSIA">CAST</FONT>(<FONT COLOR="FUCHSIA">DATEDIFF</FONT>(<FONT COLOR="FUCHSIA">SECOND</FONT>,c.StartTime,c.EndTime) /3600. <FONT COLOR="BLUE">AS Decimal</FONT>(7,2)) <FONT COLOR="BLUE">AS VARCHAR</FONT>) + <FONT COLOR="RED">'' Hr''</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp <FONT COLOR="BLUE">WHEN</FONT> <FONT COLOR="FUCHSIA">DATEDIFF</FONT>(<FONT COLOR="FUCHSIA">SECOND</FONT>,c.StartTime,c.EndTime) >= 60  <FONT COLOR="BLUE">THEN</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp  &nbsp &nbsp <FONT COLOR="FUCHSIA">CAST</FONT>(<FONT COLOR="FUCHSIA">CAST</FONT>(<FONT COLOR="FUCHSIA">DATEDIFF</FONT>(<FONT COLOR="FUCHSIA">SECOND</FONT>,c.StartTime,c.EndTime) /60. <FONT COLOR="BLUE">AS Decimal</FONT>(7,2)) <FONT COLOR="BLUE">AS VARCHAR</FONT>) + <FONT COLOR="RED">'' Min''</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp <FONT COLOR="BLUE">ELSE</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp  &nbsp &nbsp <FONT COLOR="FUCHSIA">CAST</FONT>(<FONT COLOR="FUCHSIA">CAST</FONT>(<FONT COLOR="FUCHSIA">DATEDIFF</FONT>(MILLI<FONT COLOR="FUCHSIA">SECOND</FONT>,c.StartTime,c.EndTime) /1000. <FONT COLOR="BLUE">AS Decimal</FONT>(7,2)) <FONT COLOR="BLUE">AS VARCHAR</FONT>) + <FONT COLOR="RED">'' Sec''</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp <FONT COLOR="BLUE">END</FONT><BR>
 &nbsp &nbsp  &nbsp &nbsp , ErrorNumber = <FONT COLOR="FUCHSIA">IsNull</FONT>(c.ErrorNumber,-1)<BR>
 &nbsp &nbsp  &nbsp &nbsp , ErrorMessage = <FONT COLOR="FUCHSIA">IsNull</FONT>(c.ErrorMessage, m.text)<BR>
	, c.Command<BR>
<FONT COLOR="BLUE">FROM</FONT> DBA_Pro.[dbo].[CommandLog] <FONT COLOR="BLUE">AS</FONT> c<BR>
<FONT COLOR="GRAY">LEFT JOIN</FONT> <FONT COLOR="#28B463">sys.messages</FONT> <FONT COLOR="BLUE">AS</FONT> m <BR>
 &nbsp &nbsp <FONT COLOR="BLUE">ON</FONT> c.ErrorNumber = m.message_id <FONT COLOR="GRAY">AND</FONT> m.language_id = 1033<BR>
<FONT COLOR="BLUE">WHERE</FONT> ID > ' + CAST(@LastID as VARCHAR) + ' <FONT COLOR="GRAY">AND</FONT> 
	ID <= '	+ CAST(@MaxID as VARCHAR) + '<BR>
<FONT COLOR="BLUE">ORDER BY</FONT> c.ID <FONT COLOR="BLUE">DESC</FONT></td></tr>
</td></tr></table>

<BR><H4>To try to re-run Backup process you can use following script:</H4><table border = 1><tr><td>
<FONT COLOR="BLUE">DECLARE</FONT> @Databases <FONT COLOR="BLUE">nvarchar</FONT>(<FONT COLOR="FUCHSIA">max</FONT>) = 
<FONT COLOR="RED">''' + @FailedDBList + N'''</FONT>;
<BR><FONT COLOR="BLUE">DECLARE</FONT> @Directory <FONT COLOR="BLUE">nvarchar</FONT>(<FONT COLOR="FUCHSIA">max</FONT>) = 
<FONT COLOR="RED">''' + @Directory + N'''</FONT>;
<BR><FONT COLOR="BLUE">DECLARE</FONT> @DirectoryStructure <FONT COLOR="BLUE">nvarchar</FONT>(<FONT COLOR="FUCHSIA">max</FONT>) = 
<FONT COLOR="RED">''' + @DirectoryStructure + N'''</FONT>;
<BR><FONT COLOR="BLUE">DECLARE</FONT> @AvailabilityGroupDirectoryStructure <FONT COLOR="BLUE">nvarchar</FONT>(<FONT COLOR="FUCHSIA">max</FONT>) = 
<FONT COLOR="RED">''' + @AvailabilityGroupDirectoryStructure + N'''</FONT>;
<BR><FONT COLOR="BLUE">DECLARE</FONT> @FileName <FONT COLOR="BLUE">nvarchar</FONT>(<FONT COLOR="FUCHSIA">max</FONT>) = 
<FONT COLOR="RED">''' + @FileName + N'''</FONT>;

<BR><FONT COLOR="BLUE">EXECUTE</FONT> DBA_Pro.[dbo].[DatabaseBackup]
<BR> &nbsp &nbsp @Databases = @Databases,
<BR> &nbsp &nbsp @Directory = @Directory,
<BR> &nbsp &nbsp @DirectoryStructure = @DirectoryStructure,
<BR> &nbsp &nbsp @AvailabilityGroupDirectoryStructure = @AvailabilityGroupDirectoryStructure,
<BR> &nbsp &nbsp @FileName = @FileName,
<BR> &nbsp &nbsp @Compress = <FONT COLOR="RED">''Y''</FONT>,
<BR> &nbsp &nbsp @Encrypt = <FONT COLOR="RED">''N''</FONT>,
<BR> &nbsp &nbsp @BackupType = <FONT COLOR="RED">''FULL''</FONT>,
<BR> &nbsp &nbsp @Verify = <FONT COLOR="RED">''Y''</FONT>,
<BR> &nbsp &nbsp @CleanupTime = NULL,
<BR> &nbsp &nbsp @CheckSum = <FONT COLOR="RED">''Y''</FONT>,
<BR> &nbsp &nbsp @LogToTable = <FONT COLOR="RED">''Y''</FONT>,
<BR> &nbsp &nbsp @Description = <FONT COLOR="RED">''db''</FONT>;
</td></tr></table>
			</body></html>';
			
	PRINT @Subject;
	PRINT @BodyText;
	PRINT REPLICATE('=',80)
	
	EXEC msdb.dbo.sp_send_dbmail  
		@subject = @Subject, 
		@body = @BodyText,
		@body_format ='HTML',
		@attach_query_result_as_file = 0,
		@recipients = @Operator_email,
		@importance = 'High';
END
GO
```
`

**Comment by olahallengren** [comment]
Would it work to check the return code from the stored procedure, instead of using TRY CATCH?

```
DECLARE @ReturnCode int = 0

DECLARE @StartTime datetime2 = SYSDATETIME()

EXECUTE @ReturnCode = dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@Verify = 'Y',
@Compress = 'Y',
@CheckSum = 'Y',
@LogToTable = 'Y'

IF @ReturnCode <> 0
BEGIN
  -- Code to send mail
END
```

**Comment by SlavaSQL** [comment]
The @returncode works and send an email, but error is still reported to the job and the job fails, even though only one of many DB backups failed.
It kind of seems not like a big deal, but because of each job has assigned operator, that operator also will get an email about job failure. That means duplication of an alert.
In addition to that, will be generated a special report with all Job-Step failures happened that day on that server. That is third notification.
Somebody can say: "-Just to turn of notification from a job itself", but at first, there is a hard rule to have operator assigned for each job and second, it will get into violation report.
Not everything is so easy.

Will try to combine customers' requirements together:
1. Customer needs notification if entire job fails by any reason.
2. Customer needs a daily report if any job/step failed during a day.
3. For backup job customer wants job not to fail and not get into the daily report, but send a specific email telling which database and when failed to be backed up.
4. Duplication of failure emails is not considered as a good option.

Have I described the problem?

**Comment by olahallengren** [comment]
>For backup job customer wants job not to fail and not get into the daily report, but send a specific email telling which database and when failed to be backed up.

One more thing to consider. The stored procedure could fail in some place in the code, other than the actual BACKUP DATABASE (or RESTORE VERIFYONLY) command. It could be that you are passing an invalid parameter to the stored procedure or there could be a bug in the code.

So wrapping the stored procedure into TRY CATCH could be dangerous from this point of view.

**Comment by SlavaSQL** [comment]
Any script problems within a job, not related to the actual backup would be considered as "job failure" and would cause the whole job to fail.

That was my plan "B" to create a second step. In that case customer will receive only one error message and then report at the morning, which is not ideal, but acceptable.

I assume you can close that case, but it still would be nice to have more flexibility with the control.
I could change the scripts for my customer, but do not want them to fail in a nightmare of problems associated with applying any future releases.

Thanks again.

**Comment by olahallengren** [comment]
>Any script problems within a job, not related to the actual backup would be considered as "job failure" and would cause the whole job to fail.

With the approach that I am not suggesting the job would not fail.

If the backup would fail, it will still go to the second step. Then the mail sending would succeed, and the job would report success.

**Comment by olahallengren** [comment]
>I assume you can close that case, but it still would be nice to have more flexibility with the control.

The core problem is that the backup command is reporting two errors, and you can only catch one of them using the error functions. This limitation has been there since Microsoft introduced TRY CATCH in SQL Server 2005. Hopefully they will improved this in a future version.

**Comment by srutzky** [comment]
@SlavaSQL Is your client using Azure Single DB or AWS RDS? If not, then I believe you can accomplish this via SQLCLR. I am very close to having something working. Technically I already have something that catches the first error (the one with the detail needed here), but am working on capturing and returning both, including both error messages, msg numbers, levels, and states.

Just to pre-answer the obvious questions:
1. Yes, the Assembly is marked as `SAFE`
1. Yes, security is handled properly via Certificates / signatures
Meaning: absolutely no security risks (I am being explicit about this since most people misunderstand SQLCLR in the context of security due to the overwhelming amount of misinformation that has been published on this topic).

P.S. We met last month at the SQL Saturday, Charlotte speaker dinner 😺

**Comment by SlavaSQL** [comment]
@olahallengren do you have a handy link to a request to fix that problem? I'd vote for it and maybe have more people to do the same.

**Comment by SlavaSQL** [comment]
@srutzky of cause I remember you and see your comments here and in stackexchange all the time.
It is interesting to see how you solve that problem capturing those errors, can you point me to a blog? 
However, I still won't implement it on the client's site.
At first, I've spent about 6 months just to convince people in Ola's scripts, so it will be very hard to sell that idea.
At second, I'm trying to do everything as simple as possible, that after I leave the company, regular DBAs and newbies will be able to support and won't have troubles with new implementations.

**Comment by olahallengren** [comment]
@SlavaSQL, here is a link for the user voice request.
https://feedback.azure.com/forums/908035-sql-server/suggestions/32901061-make-is-possible-to-retrieve-all-error-messages-in

**Comment by SlavaSQL** [comment]
Thanks. Voted.
