### ISSUE TITLE
DatabaseIntegrityCheck - The value for the parameter @Objects is not supported

### ISSUE THREAD

**Issue by dukesql** [olahallengren/sql-server-maintenance-solution#324]
**Description of the issue**
When trying to pass values to @Objects get the following error:

Msg 50000, Level 16, State 1, Procedure dbo.DatabaseIntegrityCheck, Line 885 [Batch Start Line 7]
The value for the parameter @Objects is not supported.

**SQL Server version and edition**
Microsoft SQL Server 2017 (RTM-CU18) (KB4527377) - 14.0.3257.3 (X64)   Nov 16 2019 01:14:50   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

**Version of the script**
Version: 2020-01-08 20:52:41     

**What command are you executing?**
EXECUTE [dbo].[DatabaseIntegrityCheck]
@Databases = 'USER_DATABASES',
@Objects = 'ALL_OBJECTS, -Db.dbo.table',
@LogToTable = 'Y'

or 

EXECUTE [dbo].[DatabaseIntegrityCheck]
@Databases = 'USER_DATABASES',
@Objects = 'ALL_OBJECTS',
@LogToTable = 'Y'

**What output are you getting?**
Msg 50000, Level 16, State 1, Procedure dbo.DatabaseIntegrityCheck, Line 885 [Batch Start Line 8]
The value for the parameter @Objects is not supported.

**Comment by olahallengren** [comment]
I am sorry about this issue. I will investigate it a bit later today.

**Comment by olahallengren** [comment]
There is a parameter called CheckCommands. By default it is ```@CheckCommands = 'CHECKDB'```.
https://ola.hallengren.com/sql-server-integrity-check.html#CheckCommands

When you are using the ```@Objects``` parameter you need to set ```@CheckCommands = 'CHECKTABLE'``` or ```@CheckCommands = 'CHECKALLOC,CHECKTABLE,CHECKCATALOG'```

**Comment by dukesql** [comment]
Thanks, Works great.  Didn't realize that was required.  Normally don't need to worry but putting a working around until a vendor fixes a log table that blowing up.
