### ISSUE TITLE
Excluding Databases That Don't Exist (MSX Deployed Jobs)

### ISSUE THREAD

**Issue by HandyDSQL** [olahallengren/sql-server-maintenance-solution#325]
### Issue
When executing DatabaseIntegrityCheck via a Master Job Server job (MSX), you cannot exclude databases that don't exist on all instances that the job is deployed to because it throws the following error during execution:

`The following databases in the @Databases parameter do not exist: `

For including databases this makes sense, however, when excluding databases, once they're set as `Selected = 0` in the @SelectedDatabases table, they're never referenced again except in the error checks. If the `Selected = 0` records are ignored in the error check, the procedure will still execute correctly and gracefully handle excluded databases that don't exist.

### Repro
`EXECUTE [dbo].[DatabaseIntegrityCheck] @Databases = 'USER_DATABASES, -ExcludedDB', @LogToTable = 'Y'`

Where "ExcludedDB" is any DB name that doesn't exist on that instance. The job fails with the above error.

### Potential Solution
Edit DatabaseIntegrityCheck.sql and add this line after line 808:

`AND Selected = 1`

NOTE: Potential Solution only solves the issue for basic DB checks. For FileGroup/AG/Object etc checks, this same fix would need to be applied to those error checks.

NOTE 2: This same issue occurs in DatabaseBackup and IndexOptimize, so the potential solution should work for those as well.

**Comment by olahallengren** [comment]
@HandyDSQL, thank you for reporting this.

The behavior until a few days ago, was that the stored procedures were reporting missing databases as an informational message and then continued the execution.

However then I made some changes to the code for input parameter checking, to make it easier to maintain. Unfortunately I missed the special case with missing databases as informational.

I will work on getting this issue fixed.

**Comment by olahallengren** [comment]
I have released a fix for this.
