### ISSUE TITLE
Index statistics extended info was logged for index regorg command when both index fix and statistics update were specified

### ISSUE THREAD

**Issue by StevenRaoDeveloper** [olahallengren/sql-server-maintenance-solution#333]
**Description of the issue**

**SQL Server version and edition**
Execute ```SELECT @@VERSION```

Microsoft SQL Server 2016 (SP2-CU4) (KB4464106) - 13.0.5233.0 (X64) 
	Nov  3 2018 00:01:54 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Version of the script**
Check the header of the stored procedure
SchemaName	ObjectName	Version	Checksum
dbo	CommandExecute	2020-01-14 21:48:14	-1254828029
dbo	DatabaseBackup	2020-01-14 21:48:14	1125239229
dbo	DatabaseIntegrityCheck	2020-01-14 21:48:14	306023191
dbo	IndexOptimize	2020-01-14 21:48:14	619462769

**What command are you executing?**
truncate table CommandLog
EXECUTE dbo.IndexOptimize
@Databases = 'MyDatabase',
--@FragmentationLow = NULL,
--@FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',
--@FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',
--@PageCountLevel = 0,
@UpdateStatistics = 'ALL',
@OnlyModifiedStatistics = 'Y',
@LogToTable = 'Y',
@Execute = 'N'

select 
	ExtendedInfo
	,ExtendedInfo.value('(ExtendedInfo/PageCount)[1]','int') AS [PageCount]
	,ExtendedInfo.value('(ExtendedInfo/Fragmentation)[1]','float') AS Fragmentation
	,CommandType
	,Command
	FROM dbo.CommandLog
WHERE CommandType = 'ALTER_INDEX'
	ORDER BY ID ASC
**What output are you getting?**

No page count and fragementation was logged for alter index command.

**Comment by StevenRaoDeveloper** [comment]
ExtendedInfo is for statistics object but not for the index object if index reorg command is chosen

**Comment by olahallengren** [comment]
This issue has been fixed. Thank you for reporting it.

**Comment by StevenRaoDeveloper** [comment]
Thank you so much for your help. I did some tests and it looks to me the bug has been fixed. Cheers! Your help and contribution to MS SQL Server community is greatly appreciated.
