### ISSUE TITLE
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Unable to complete login process due to delay in opening server connection.

### ISSUE THREAD

**Issue by cincy122** [olahallengren/sql-server-maintenance-solution#335]
**Description of the issue**
Backup not executing

**SQL Server version and edition**
Microsoft SQL Server 2017 (RTM-CU17) Enterprise Edition (64-bit)

**Version of the script**
Check the header of the stored procedure

**What command are you executing?**
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d master -Q "EXECUTE [dbo].[DatabaseBackup] @Databases = 'USER_DATABASES', @Directory = N'\\backup\location', @BackupType = 'LOG', @Verify = 'Y', @CleanupTime = 168, @CheckSum = 'Y', @LogToTable = 'Y'" -b

**What output are you getting?**
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Unable to complete login process due to delay in opening server connection.

**Comment by olahallengren** [comment]
It looks like sqlcmd is not able to connect to the SQL Server. It is not even getting to my stored procedure. Could it be that the CPU was very high?

Could you try changing this to a T-SQL job?
