### ISSUE TITLE
Error when LOG_SIZE_SINCE_LAST_LOG_BACKUP_* is specified

### ISSUE THREAD

**Issue by Rob-S** [olahallengren/sql-server-maintenance-solution#337]
**Description of the issue**

Error: The value for the parameter @DatabaseOrder is not supported. The column sys.dm_db_log_stats.log_since_last_log_backup_mb is not available in this version of SQL Server.

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

**Version of the script**
Check the header of the stored procedure
[DatabaseBackup] Version: 2020-01-14 21:48:14

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup]
   @Directory = N'.../directory/path/...',
   @BackupType = N'LOG',
   @CleanupTime = 200,
   @DatabaseOrder = N'LOG_SIZE_SINCE_LAST_LOG_BACKUP_DESC';

**What output are you getting?**
The value for the parameter @DatabaseOrder is not supported. The column sys.dm_db_log_stats.log_since_last_log_backup_mb is not available in this version of SQL Server.

**Comment by olahallengren** [comment]
This issue has been fixed. Thank you for reporting it, and finding the issue in the code.
