### ISSUE TITLE
Request: Add Backing up SSAS databases to the backup module

### ISSUE THREAD

**Issue by Snamelisch** [olahallengren/sql-server-maintenance-solution#34]
This would be a very nice addition to the scripts. I am downloading it today again and have not seen this as a part of the tooling. Of course maybe I missed it. 
But if not, this would be a very cool addition to the current tooling.

**Comment by olahallengren** [comment]
Thank you for the feedback. It is a good idea, but I have currently no plans to add support for SSAS.
