### ISSUE TITLE
Invalid object name '#Config'.

### ISSUE THREAD

**Issue by mitchplanck** [olahallengren/sql-server-maintenance-solution#343]
**Description of the issue**
I'm trying to install the maintenance solution on some new servers. Running the SQL script gives the error.

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64)   Jun 15 2019 00:26:19   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

**Version of the script**
Check the header of the stored procedure
Version: 2020-01-26 14:06:53

**What command are you executing?**
Running the script to install the stored procedures.

**What output are you getting?**
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near '﻿'.
Msg 208, Level 16, State 0, Line 8666
Invalid object name '#Config'.

**Comment by mitchplanck** [comment]
was not able to reproduce, working fine.

**Comment by ReeceGoding** [comment]
Seems you can also trip this if you try calling `MaintenanceSolution.sql` from dbatools' `Invoke-DbaQuery`. I don't think it's any fault of `MaintenanceSolution.sql` .
