### ISSUE TITLE
ChangeBackupType folder structure

### ISSUE THREAD

**Issue by SQLPadre** [olahallengren/sql-server-maintenance-solution#347]
I current make use of the ability to configure Directory Structure because we use and rotate between multiple CIF shares to maintain our retention.

I am currently using these parameters:
```
,@Directory = '\\xxxx.xxx\DBA\BKP-DC0-DEV-DIFF\'
,@DirectoryStructure = '{ServerName}_{InstanceName}{DirectorySeparator}'
,@FileName = '{DatabaseName}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}'
,@BackupType = 'DIFF'
,@FileExtensionDiff = 'diff'
,@ChangeBackupType='Y'
```

My question (and I may be missing this) when I use the parameters this way and a new database is created and never been backed up, it places the backups in this DIFF network share.

is there anyway to change the @Directory parameter (or any of them) to another share when @ChangeBackupType is used ?  example:   \\xxxx.xxx\DBA\BKP-DC0-DEV-FULL\

because right now the first BAK file is being stored in my DIFF directory structure

**Comment by olahallengren** [comment]
@SQLPadre, as it currently works, the only way would be to add the token {BackupType} to the ```@DirectoryStructure``` parameter and remove the hard coded backup type from the ```@Directory``` parameter.

**Comment by SQLPadre** [comment]
would @Directory = '\\xxx.xx\DBA\BKP-DC0-{BackupType}' work?

if my 3 folder structures use the toke {BackupType}?

**Comment by SQLPadre** [comment]
Nevermind Ola, I think I figured it out by bring the @Directory parameter down one level

`@Databases = 'USER_DATABASES'
	,@Directory = '\\xxxx.xxx\DBA\'
	,@DirectoryStructure = 'BKP-DC0-DEV-{BackupType}{DirectorySeparator}{ServerName}_{InstanceName}{DirectorySeparator}'
	,@FileName = '{DatabaseName}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}'`

**Comment by olahallengren** [comment]
@SQLPadre, yes, that is the way to do it.
