### ISSUE TITLE
SQL Server Backup Solution no longer includes ServerName in destination folder path

### ISSUE THREAD

**Issue by Bill-2020** [olahallengren/sql-server-maintenance-solution#349]
I would like to thank Ola for the work done with the SQL Server Scripts over the years! They have been extremely helpful many times over.

I am experiencing an issue with the latest (version 2020-01-06 19:43:36) SQL Backup solution on MSSQL 2014 and 2017 Enterprise versions. The Server Name is no longer used in the creation of the backup file location path. For example, with older versions of the backup procedure, my file backup path would be G:\MSSQL14.MSSQLSERVER\MSSQL\Backup\ServerName\master\FULL\filename_with_date.bak
Now my file backup path is like G:\MSSQL14.MSSQLSERVER\MSSQL\Backup\master\FULL\filename_with_date.bak. This could cause a number of issues.
The SQL Agent Jobs are executed with the following parameters:
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'SYSTEM_DATABASES',
@Directory = NULL,
@BackupType = 'FULL',
@Verify = 'Y',
@CleanupMode = 'AFTER_BACKUP',
@CleanupTime = 12,
@Encrypt = 'N',
@CheckSum = 'Y',
@LogToTable = 'Y'

I see @DirectoryStructure nvarchar(max) = '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', set in StoredProcedure [dbo].[DatabaseBackup]
But for some reason, the ServerName token is not used and added to the path. But it is used and added for filename creation.

Thank you for any insight you can provide.
Best Regards,
Bill

**Comment by olahallengren** [comment]
@Bill-2020, there is some special code so that the server name and instance name are not included, if you are backing up to the default backup directory, and that contains the name of the SQL Server service.

```
        IF @Directory IS NULL AND @MirrorDirectory IS NULL AND @URL IS NULL AND @DefaultDirectory LIKE '%' + '.' + @@SERVICENAME + @DirectorySeparator + 'MSSQL' + @DirectorySeparator + 'Backup'
        BEGIN
          SET @CurrentDirectoryStructure = REPLACE(@CurrentDirectoryStructure,'{ServerName}','')
          SET @CurrentDirectoryStructure = REPLACE(@CurrentDirectoryStructure,'{InstanceName}','')
          SET @CurrentDirectoryStructure = REPLACE(@CurrentDirectoryStructure,'{ClusterName}','')
          SET @CurrentDirectoryStructure = REPLACE(@CurrentDirectoryStructure,'{AvailabilityGroupName}','')
        END
```

**Comment by Bill-2020** [comment]
Thank you Ola for your clarification! That makes sense now that you explain it. I thought perhaps we had something odd in our environment or the way in which our tokens were being applied. 
I know I speak for many DBAs when I say how appreciative I am for the work that you've put forth in these scripts and the help that you provide. 
Best Regards,
Bill
