### ISSUE TITLE
Wrong variable name: DirectorySeperator

### ISSUE THREAD

**Issue by daniel-stan** [olahallengren/sql-server-maintenance-solution#358]
**Description of the issue**
A variable name is misspelled as: DirectorySeperator.
Details:
There is a variable DirectorySeparator declared at line 452 in the script file MaintenanceSolution.sql.
This variable is referred incorrectly as %{DirectorySeperator}% at lines: 
2333
and 2377

**SQL Server version and edition**
Microsoft SQL Server 2014 - 12.0.2269.0 (X64)   Jun 10 2015 03:35:45   Copyright (c) Microsoft Corporation  Express Edition (64-bit) on Windows NT 6.3 <X64> (Build 18363: ) 

**Version of the script**
2020-01-26 14:06:53

**What command are you executing?**
Running the file MaintenanceSolution.sql

**What output are you getting?**
Commands completed successfully.

**Comment by olahallengren** [comment]
This issue has been fixed. Thank you for reporting it.
