### ISSUE TITLE
USER_DATABASES - DIFF Failing

### ISSUE THREAD

**Issue by MFK-DGAF** [olahallengren/sql-server-maintenance-solution#363]
**Description of the issue**
Backup is failing at first database. Backup worked previously, but nothing has changed that should cause the backup to be failing.

**SQL Server version and edition**
Execute ```SELECT @@VERSION```

Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64)   Jul 12 2019 17:43:08   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

**Version of the script**
Check the header of the stored procedure
Version: 2019-05-22 22:32:33

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES, -RHA_EDW_LAUREL',
@Directory = 'G:\Backups',
@BackupType = 'DIFF',
@Verify = 'Y',
@CleanupTime = 168,
@CheckSum = 'Y',
@LogToTable = 'Y'

**What output are you getting?**
Message
Executed as user: RHADATA\SQL-Master. ...ge 50000)  Server: TELLER-MART4 [SQLSTATE 01000] (Message 50000)  Version: 14.0.3223.3 [SQLSTATE 01000] (Message 50000)  Edition: Standard Edition (64-bit) [SQLSTATE 01000] (Message 50000)  Platform: Windows [SQLSTATE 01000] (Message 50000)  Procedure: [master].[dbo].[DatabaseBackup] [SQLSTATE 01000] (Message 50000)  Parameters: @Databases = 'USER_DATABASES, -RHA_EDW_LAUREL', @Directory = 'G:\Backups', @BackupType = 'DIFF', @Verify = 'Y', @CleanupTime = 168, @CleanupMode = 'AFTER_BACKUP', @Compress = NULL, @CopyOnly = 'N', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'Y', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = NULL, @Credential = NULL, @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @AvailabilityGroupDirectoryStructure = '{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y' [SQLSTATE 01000] (Message 50000)  Version: 2019-05-22 22:32:33 [SQLSTATE 01000] (Message 50000)  Source: https://ola.hallengren.com [SQLSTATE 01000] (Message 50000)  	 [SQLSTATE 01000] (Message 50000)  Date and time: 2020-03-04 20:00:02 [SQLSTATE 01000] (Message 50000)  Database: [DA_ERwin] [SQLSTATE 01000] (Message 50000)  Status: ONLINE [SQLSTATE 01000] (Message 50000)  Standby: No [SQLSTATE 01000] (Message 50000)  Updateability: READ_WRITE [SQLSTATE 01000] (Message 50000)  User access: MULTI_USER [SQLSTATE 01000] (Message 50000)  Is accessible: Yes [SQLSTATE 01000] (Message 50000)  Recovery model: FULL [SQLSTATE 01000] (Message 50000)  Encrypted: No [SQLSTATE 01000] (Message 50000)  Differential base LSN: 116000002170200037 [SQLSTATE 01000] (Message 50000)  Differential base is snapshot: Yes [SQLSTATE 01000] (Message 50000)  Last log backup LSN: 116000002173400001 [SQLSTATE 01000] (Message 50000)  Allocated extent page count: N/A [SQLSTATE 01000] (Message 50000)  Modified extent page count: N/A [SQLSTATE 01000] (Message 50000)  	 [SQLSTATE 01000] (Message 50000)  Date and time: 2020-03-04 20:00:02 [SQLSTATE 01000] (Message 50000)  Command: DECLARE @ReturnCode int EXECUTE @ReturnCode = [master].dbo.xp_create_subdir N'G:\Backups\DA_ERwin\DIFF' IF @ReturnCode <> 0 RAISERROR('Error creating directory.', 16, 1) [SQLSTATE 01000] (Message 50000)  Outcome: Succeeded [SQLSTATE 01000] (Message 50000)  Duration: 00:00:00 [SQLSTATE 01000] (Message 50000)  Date and time: 2020-03-04 20:00:02 [SQLSTATE 01000] (Message 50000)  	 [SQLSTATE 01000] (Message 50000)  Date and time: 2020-03-04 20:00:02 [SQLSTATE 01000] (Message 50000)  Command: BACKUP DATABASE [DA_ERwin] TO DISK = N'G:\Backups\DA_ERwin\DIFF\TELLER-MART4_DA_ERwin_DIFF_20200304_200002.bak' WITH CHECKSUM, NO_COMP...  The step failed.

**Comment by olahallengren** [comment]
@MFK-DGAF, it looks like you have some snapshot based (VSS) backups running on the server.

Differential base is snapshot: Yes

A VSS based full backup can't be used as a base for a SQL Server Native differential backup.
