### ISSUE TITLE
Option to exclude the backup type folder

### ISSUE THREAD

**Issue by drstonephd** [olahallengren/sql-server-maintenance-solution#37]
Please provide a option to remove the folder (e.g., FULL, DIFF, and LOG) for the backup type.  For other folders with the backup type embedded (e.g., FULL_COPY_ONLY), remove just the part of the folder name that refers to the backup type (e.g., FULL_COPY_ONLY becomes COPY_ONLY).  

For the native SQL backups, this would require changing the DIFF backup extension to something else like "dif" so that the file cleanup works correctly.  I don't know what this would mean for other backup products...perhaps this is an invalid option for some.  Perhaps also provide an option to set the extension used when making a backup?  In this case, it would be the user's responsibility to insure that extensions and cleanup work properly together.

**Comment by olahallengren** [comment]
I am considering adding support for a configurable directory structure, and also support for setting the file extensions.

**Comment by olahallengren** [comment]
I have a preview version where you can configure the directory structure, file names, and file extensions.  You can download the preview version [here](https://ola.hallengren.com/preview.html).

**Comment by olahallengren** [comment]
This feature is available in the branch [feature-configurable_directory_structure].

**Comment by olahallengren** [comment]
This feature has now been released.
https://ola.hallengren.com/versions.html

Documentation:
https://ola.hallengren.com/sql-server-backup.html#DirectoryStructure
https://ola.hallengren.com/sql-server-backup.html#AvailabilityGroupDirectoryStructure

https://ola.hallengren.com/sql-server-backup.html#FileExtensionFull
https://ola.hallengren.com/sql-server-backup.html#FileExtensionDiff
https://ola.hallengren.com/sql-server-backup.html#FileExtensionLog
