### ISSUE TITLE
Backup Extension

### ISSUE THREAD

**Issue by sandeshjonnala** [olahallengren/sql-server-maintenance-solution#373]
Usually the Backup extension used for Differential is .dif

But in your Script this was used as bak for full and differential both. what could be the reason or any advantage of using it as bak for SQL Native Backup's ?

**Comment by olahallengren** [comment]
I have been using the same file extensions as the built-in Maintenance Plans. They are using .bak for full and differential backup and .trn for transaction log backup.

You can use the parameter ```@FileExtensionDiff```, if you would like to use another file extension for differential backup.
https://ola.hallengren.com/sql-server-backup.html#FileExtensionDiff
