### ISSUE TITLE
ChangeBackupType on AG

### ISSUE THREAD

**Issue by KiwiKev** [olahallengren/sql-server-maintenance-solution#376]
Hi
I have an AG running on MSSQL 2017 Standard with a single Secondary
The database is 2008 version
When i fallover the database i would expect to see the backup change from LOG to FULL with the ChangeBackupType option set.

When the database fall's over and the transaction log job runs i get a transaction log backup without a full backup on the new server.

Job script 
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'AVAILABILITY_GROUP_DATABASES',
@Directory = N'F:\MSSQLBackup\SQLBackups',
@BackupType = 'LOG',
@Verify = 'Y',
@CleanupTime = 48,
@CheckSum = 'Y',
@LogToTable = 'Y',
@Compress = 'Y',
@ChangeBackupType='Y'

resulting backup command

BACKUP LOG [MQFDATABASE] TO DISK = N'F:\MSSQLBackup\SQLBackups\AWS-SQLCLUS-01$AWS-xxDATABASE\xxDATABASE\LOG\AWS-SQLCLUS-01$AWS-xxDATABASE_xxDATABASE_LOG_20200331_100802.trn' WITH CHECKSUM, COMPRESSION

**Comment by olahallengren** [comment]
@KiwiKev, there is no need to perform a new full backup after a failover. You can perform a point-in-time restore, using backups from multiple replicas together.

You could consider backing up to an UNC path, so that you have all your backups in one place.
