### ISSUE TITLE
Slowness when checking for CurrentAvailabilityGroup on SQL Server 2019

### ISSUE THREAD

**Issue by tarynpratt** [olahallengren/sql-server-maintenance-solution#378]
In SQL Server 2019 CU3, we are noticing issues with the following code in the DatabaseBackup script  being slow on replicas with a lot of databases:

   
    IF @Version >= 11 AND SERVERPROPERTY('IsHadrEnabled') = 1
    BEGIN
      SELECT @CurrentAvailabilityGroup = availability_groups.name,
             @CurrentAvailabilityGroupRole = dm_hadr_availability_replica_states.role_desc,
             @CurrentAvailabilityGroupBackupPreference = UPPER(availability_groups.automated_backup_preference_desc)
      FROM sys.databases databases
      INNER JOIN sys.dm_hadr_availability_replica_states dm_hadr_availability_replica_states ON databases.replica_id = dm_hadr_availability_replica_states.replica_id
      INNER JOIN sys.availability_groups availability_groups ON dm_hadr_availability_replica_states.group_id = availability_groups.group_id
      WHERE databases.name = @CurrentDatabaseName
    END

The join to `sys.dm_hadr_availability_replica_states` is the costly piece of the query. There are two possible options I can see to improve the performance of the query at this time. You can use a HASH JOIN hint (thanks Paul White):

    IF @Version >= 11 AND SERVERPROPERTY('IsHadrEnabled') = 1
    BEGIN
      SELECT @CurrentAvailabilityGroup = availability_groups.name,
             @CurrentAvailabilityGroupRole = dm_hadr_availability_replica_states.role_desc,
             @CurrentAvailabilityGroupBackupPreference = UPPER(availability_groups.automated_backup_preference_desc)
      FROM sys.databases databases
      INNER HASH JOIN sys.dm_hadr_availability_replica_states dm_hadr_availability_replica_states ON databases.replica_id = dm_hadr_availability_replica_states.replica_id
      INNER JOIN sys.availability_groups availability_groups ON dm_hadr_availability_replica_states.group_id = availability_groups.group_id
      WHERE databases.name = @CurrentDatabaseName
    END

Or remove the JOIN to ` sys.dm_hadr_availability_replica_states` and select the `@CurrentAvailabilityGroupRole` in a subquery.

    IF @Version >= 11 AND SERVERPROPERTY('IsHadrEnabled') = 1
    BEGIN
      SELECT @CurrentAvailabilityGroup = availability_groups.name,
		   @CurrentAvailabilityGroupRole = (Select dm_hadr_availability_replica_states.role_desc 
											  From sys.dm_hadr_availability_replica_states 
											 Where availability_groups.group_id = dm_hadr_availability_replica_states.group_id 
											   AND databases.replica_id = dm_hadr_availability_replica_states.replica_id),
		   @CurrentAvailabilityGroupBackupPreference = UPPER(availability_groups.automated_backup_preference_desc)
	FROM sys.databases databases
	INNER JOIN sys.availability_databases_cluster availability_databases_cluster
			ON databases.group_database_id = availability_databases_cluster.group_database_id
	INNER JOIN sys.availability_groups availability_groups
			ON availability_databases_cluster.group_id = availability_groups.group_id
	WHERE databases.name = @CurrentDatabaseName;
    END

Both of these versions perform much faster than the existing version in SQL Server 2019. It appears to possibly be a regression with querying those states in 2019, as we did not hit this issue until we upgraded recently.

**Comment by olahallengren** [comment]
@tarynpratt, I have been improving this.
https://ola.hallengren.com/versions.html

I changed the code like this:

```
    IF @Version >= 11 AND SERVERPROPERTY('IsHadrEnabled') = 1
    BEGIN
      SELECT @CurrentReplicaID = databases.replica_id
      FROM sys.databases databases
      INNER JOIN sys.availability_replicas availability_replicas ON databases.replica_id = availability_replicas.replica_id
      WHERE databases.[name] = @CurrentDatabaseName

      SELECT @CurrentAvailabilityGroupRole = role_desc,
             @CurrentAvailabilityGroupID = group_id
      FROM sys.dm_hadr_availability_replica_states
      WHERE replica_id = @CurrentReplicaID

      SELECT @CurrentAvailabilityGroup = [name],
             @CurrentAvailabilityGroupBackupPreference = UPPER(automated_backup_preference_desc)
      FROM sys.availability_groups
      WHERE group_id = @CurrentAvailabilityGroupID
    END
```

Could I ask you to test the latest version?
