### ISSUE TITLE
User Database Integrity Check (CHECKFILEGROUP) jobs fail on secondary AG servers

### ISSUE THREAD

**Issue by AS-DBA** [olahallengren/sql-server-maintenance-solution#382]
**Description of the issue**
User Database Integrity Check (CHECKFILEGROUP) jobs fail on secondary AG servers

**SQL Server version and edition**
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 

**Version of the script**
Version: 2020-01-26 14:06:53           

**What command are you executing?**
EXECUTE dbo.DatabaseIntegrityCheck
@Databases = 'USER_DATABASES',
@CheckCommands = 'CHECKFILEGROUP'

**What output are you getting?**
Date and time: 2020-05-03 22:12:13
Version: 13.0.5026.0
Edition: Enterprise Edition (64-bit)
Platform: Windows
Procedure: [DBADB].[dbo].[DatabaseIntegrityCheck]
Parameters: @Databases = 'USER_DBASES', @CheckCommands = 'CHECKFILEGROUP', @PhysicalOnly = 'N', @DataPurity = 'N', @NoIndex = 'N', @ExtendedLogicalChecks = 'N', @TabLock = 'N', @FileGroups = NULL, @Objects = NULL, @MaxDOP = NULL, @AvailabilityGroups = NULL, @AvailabilityGroupReplicas = 'ALL', @Updateability = 'ALL', @TimeLimit = NULL, @LockTimeout = NULL, @LockMessageSeverity = 16, @StringDelimiter = ',', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'N', @Execute = 'Y'
Version: 2020-01-26 14:06:53
Source: https://ola.hallengren.com
	
Date and time: 2020-05-03 22:12:14
Database: [a]
State: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Recovery model: FULL
Is accessible: Yes
Availability group: AG_DEFAULT
Availability group role: SECONDARY
	
Msg 976, Level 14, State 1, Procedure DatabaseIntegrityCheck, Line 1452 [Batch Start Line 0]
The target database, 'a', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

**Comment by olahallengren** [comment]
I have changed so that DatabaseIntegrityCheck is not trying to perform CHECKFILEGROUP or CHECKTABLE on secondary replicas.
