### ISSUE TITLE
Backup Fails with Error: Incorrect syntax near the keyword 'WITH'

### ISSUE THREAD

**Issue by Shivers103** [olahallengren/sql-server-maintenance-solution#387]
**Description of the issue**
Incorrect syntax near the keyword 'WITH'. 

Hopefully this is helpful.
After some debugging the issue is with when SUM(modified_extent_page_count) equals zero  and the parameter @MaxFileSize is set, the variable @CurrentNumberOfFiles gets incorrectly set to zero. 
When the code comes to this statement "WHILE @CurrentFileNumber < @CurrentNumberOfFiles" both are zero and therefore the table @CurrentFiles never gets any inserted values. When the code creates @CurrentCommand, it assembles incorrect syntax.

**SQL Server version and edition**
Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64)   Nov 30 2018 12:57:58   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

**Version of the script**
2020-01-26 14:06:53 

**What command are you executing?**
```
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@Directory = N'\\<PATH>',
@BackupType = 'DIFF',
@Verify = 'N',
@CleanupTime = 336,
@CheckSum = 'Y',
@LogToTable = 'Y',
@Compress = 'Y',
@MaxFileSize = 250000
```

**What output are you getting?**
```
Date and time: 2020-05-19 15:23:22
Database context: [master]
Command: BACKUP DATABASE [xxx] TO WITH CHECKSUM, COMPRESSION, DIFFERENTIAL
Msg 156, Level 15, State 1, Line 1
Incorrect syntax near the keyword 'WITH'.
Msg 319, Level 15, State 1, Line 1
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Outcome: Failed
Duration: 00:00:00
Date and time: 2020-05-19 15:23:22
```

**Comment by olahallengren** [comment]
Thank you for reporting this issue. It has been fixed now.
