### ISSUE TITLE
Support of "MaxTransferSize" for backups to blob container

### ISSUE THREAD

**Issue by CarlosGzz-SQL** [olahallengren/sql-server-maintenance-solution#389]
**Description of the issue**
While doing a backup to blob container using failure due code condition

`  IF @MaxTransferSize IS NOT NULL AND @URL IS NOT NULL AND @Credential IS NOT NULL
  BEGIN
    INSERT INTO @Errors ([Message], Severity, [State])
    SELECT 'The value for the parameter @MaxTransferSize is not supported.', 16, 4
  END`

**SQL Server version and edition**
Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 (X64) 
	Jul 20 2019 21:42:29 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Version of the script**
Version: 2020-01-26 14:06:53   and older

**What command are you executing?**
`EXECUTE master.[dbo].[DatabaseBackup] @Databases = 'USER_DATABASES', @URL='https://BlobStorageAccount.blob.core.windows.net/MyBackupContainer/DIFF',
@Credential='MyCredentialForBlob', @BackupType = 'DIFF', @Verify = 'Y', 
@CleanupTime = null, @CheckSum = 'Y', @LogToTable = 'Y', @Compress='y', @BufferCount = 7, @MaxTransferSize =1048576`

**What output are you getting?**
Msg 50000, Level 16, State 4, Procedure DatabaseBackup, Line 2272
The value for the parameter @MaxTransferSize is not supported.
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 2272
The documentation is available at https://ola.hallengren.com/sql-server-backup.html.

**Comment by olahallengren** [comment]
You need to change to use a Shared Access Signature, instead of specifying a credential.
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url
