### ISSUE TITLE
 Differential backup of master database does not work

### ISSUE THREAD

**Issue by daniloalves19** [olahallengren/sql-server-maintenance-solution#390]
Hello, I am using the command below to make differential backup of system databases. But it is not being realized from the "master" database.

I performed the Full Backup, then created a new table, inserted records and performed the differential backup, captured by SQL Server Profiller.

See the sequence of commands sent and only the "model" and "msdb" databases were performed

`EXECUTE [dbo].[DatabaseBackup]
@Databases = 'SYSTEM_DATABASES',
@Directory = FOLDER,
@FileName = '{DatabaseName}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{BackupType}.{FileExtension}',
@BackupType = 'DIFF',
@Verify = 'Y',
@Compress = 'Y',
@CleanupTime = NULL,
@CheckSum = 'Y',
@LogToTable = 'Y',
@DirectoryStructure = '{DatabaseName}'`

![Erro Backup master](https://user-images.githubusercontent.com/56640018/83172024-58755800-a0ed-11ea-866c-043c13b4e96d.png)

**Comment by MikeyBronowski** [comment]
@daniloalves19 have a look at [MS Docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/backup-transact-sql?view=sql-server-ver15).

`Only a full database backup can be performed on the master database.`


If you try it from the SQL Server Management Studio you get
```
Msg 3024, Level 16, State 0, Line 1
You can only perform a full backup of the master database. Use BACKUP DATABASE to back up the entire master database.
Msg 3013, Level 16, State 1, Line 1
BACKUP DATABASE is terminating abnormally.
```

**Comment by olahallengren** [comment]
@MikeyBronowski, this is correct.

I can add that the master database is being skipped because of this code in DatabaseBackup.

```AND NOT (@CurrentBackupType IN('DIFF','LOG') AND @CurrentDatabaseName = 'master')```
