### ISSUE TITLE
Out of 4 user databases the USER_DATABASES - LOG  backing up only 1

### ISSUE THREAD

**Issue by Houuse** [olahallengren/sql-server-maintenance-solution#397]
**every thing fine except when I went to restore the backup found out the LOG backup of the user databases isn't being made
and when I query the table [master].[dbo].[CommandLog] the command type BACKUP_LOG is there for only that one database but not for the other ones **

**Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64)   Mar 13 2020 14:53:45   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) **

**--// Version: 2020-01-26 14:06:53   **

**EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'DatabaseBackup - USER_DATABASES - LOG', 
		@step_id=1, 
		@cmdexec_success_code=0, 
		@on_success_action=1, 
		@on_success_step_id=0, 
		@on_fail_action=2, 
		@on_fail_step_id=0, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'TSQL', 
		@command=N'EXECUTE [dbo].[DatabaseBackup]
@Databases = ''USER_DATABASES'',
@Directory = N''E:\SQLBackup'',
@BackupType = ''LOG'',
@Verify = ''Y'',
@CleanupTime = 192,
@CheckSum = ''Y'',
@LogToTable = ''Y''', 
		@database_name=N'master', 
		@output_file_name=N'E:\SQLBackup\$(ESCAPE_SQUOTE(JOBNAME))_$(ESCAPE_SQUOTE(STEPID))_$(ESCAPE_SQUOTE(DATE))_$(ESCAPE_SQUOTE(TIME)).txt', 
		@flags=0**

**What output are you getting?**
![image](https://user-images.githubusercontent.com/37629725/84782486-5d407400-afe8-11ea-8f9c-836c25b7f74c.png)

**Comment by CrazySwimmer** [comment]
Hi Houuse,

What is the recovery model of your user databases? Log backups are performed only for full and bulk-logged recovery models, not for simple.

Best,
Danilo

**Comment by Houuse** [comment]
@CrazySwimmer Thanks for the reply, the problem solved by changing the DB recovery mode to FULL , thank you :)
