### ISSUE TITLE
CHECKCATALOG fails on secondary replica database

### ISSUE THREAD

**Issue by tonyfountain** [olahallengren/sql-server-maintenance-solution#403]
**Description of the issue**
DatabaseIntegrityCheck fails when issuing CHECKCATALOG on a secondary replica since it is considered read-only.  This server has a bunch of databases, some are secondary replicas of an AO, others live on the server that are not part of AO.

Can a check be added to see if a database is a read-only secondary replica and just be skipped without an error?

**SQL Server version and edition**
Microsoft SQL Server 2017 (RTM-CU18) (KB4527377) - 14.0.3257.3 (X64) 
	Nov 16 2019 01:14:50 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Version of the script**
2020-01-26 14:06:53

**What command are you executing?**
EXEC dbo.DatabaseIntegrityCheck @Databases = 'USER_DATABASES', @CheckCommands = 'CHECKALLOC,CHECKTABLE,CHECKCATALOG', @PhysicalOnly = 'Y', @DataPurity = 'N', @NoIndex = 'Y', @ExtendedLogicalChecks = 'N', @TabLock = 'N', @FileGroups = NULL, @Objects = 'ALL_OBJECTS,-%.dbo.redacted', @MaxDOP = NULL, @AvailabilityGroups = NULL, @AvailabilityGroupReplicas = 'ALL', @Updateability = 'ALL', @TimeLimit = NULL, @LockTimeout = NULL, @LockMessageSeverity = 16, @StringDelimiter = ',', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'

**What output are you getting?**
Msg 3906, Level 16, State 8, Line 1
Failed to update database "redacted" because the database is read-only.

**Comment by olahallengren** [comment]
I am trying to reproduce this issue. In my testing, CHECKCATALOG works well on secondary replica. However, there is a problem with CHECKTABLE on secondary replicas that are not readable.

Could you please perform a test with only CHECKCATALOG?

**Comment by olahallengren** [comment]
I have not been able to reproduce this issue. However, I have fixed some other issues related to check commands on secondary replicas. Could I ask you to update to the latest version and test again?

**Comment by olahallengren** [comment]
Are you still having this issue?

**Comment by brendanxmccaffrey** [comment]
I've seen issues like this when the procedures are being run from a read-only database, such as be that is a member of AG, and tying to log.

**Comment by olahallengren** [comment]
Here is one thing to check if you are having this issue:

"Basic availability groups cannot be upgraded to advanced availability groups. The group must be dropped and re-added to a group that contains servers running only SQL Server 2016 Enterprise Edition."

https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-ver16
