### ISSUE TITLE
SET Lock_TimeOut Error Not Recorded in CommandLog Table

### ISSUE THREAD

**Issue by lmarkum** [olahallengren/sql-server-maintenance-solution#406]
**Description of the issue**
When using the SET LOCK_TIMEOUT option, the error generated when the lock time out value is exceeded is not recorded in the CommandLog table.  It is only found in the output files.

Another person confirmed this same behavior on my StackExchange question.
https://dba.stackexchange.com/questions/271166/how-can-i-capture-error-thrown-by-set-locktimeout-in-ola-hallengren

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

**Version of the script**
Stored procedure doesn't have any header info.  Just shows the following
  ----------------------------------------------------------------------------------------------------
  --// Source: https://ola.hallengren.com                                                          //--
  ----------------------------------------------------------------------------------------------------

**What command are you executing?**
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d DBA -Q "EXECUTE [dbo].[IndexOptimize] @Databases = 'USER_DATABASES', @LogToTable = 'Y'" -b

**What output are you getting?**
In the output files I get the below, as an example:
Msg 1222, Level 16, State 56, Server MySQLServer, Line 1
Lock request time out period exceeded.
Msg 50000, Level 16, State 1, Server MySQLServer, Procedure dbo.IndexOptimize, Line 1219
The index [CDREF_idx] on the object [MyDB].[dbo].[Mytable] is locked. The size and fragmentation of the index could not be checked.

**Comment by olahallengren** [comment]
It is only commands like ALTER INDEX and UPDATE STATISTICS that are logged to the CommandLog table.

In this case the lock timeout happened, when the DMF sys.dm_db_index_physical_stats was queried.

**Comment by leepfrog-ger** [comment]
It seems that the behavior is still still unchanged. Are there any recommendations how to handle this efficiently?
