### ISSUE TITLE
diff or log backup chain issue

### ISSUE THREAD

**Issue by lang8134** [olahallengren/sql-server-maintenance-solution#407]
if database testdb(full model) is restored from testdb02(full model) with replace.
then diff or log backup will be successful, but the backup chain is break without fullback after new restore.

suggest ChangeType will also cover this case.

**Comment by olahallengren** [comment]
This is by design. The database backup that the database was restored from counts as a full backup in this case.

The logic in the script only works if the database was created using CREATE DATABASE.
