### ISSUE TITLE
Filename not respected when using URL??

### ISSUE THREAD

**Issue by olsonnn** [olahallengren/sql-server-maintenance-solution#408]
**Description of the issue**
Filename not respected when using URL??

**SQL Server version and edition**
SQL2016

**Version of the script**
Version: 2020-01-26 14:06:53

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@BackupType = 'FULL',
@Credential = 'mycreds'
@Compress='Y',
@Url='https://myblob.blob.core.windows.net/sqlbackup',
@FileName = '{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}',
@DirectoryStructure = NULL,
@AvailabilityGroupDirectoryStructure = NULL,
@Verify = 'N',
@NumberOfFiles = 8,
@MaxTransferSize = 4194304,
@BlockSize = 65536

**output**

Message
BackupDiskFile::CreateMedia: Backup device 'https://myblob.blob.core.windows.net/sqlbackup/myserver$myinstance/mydab/FULL/FULL_20200818_144639_6.bak' failed to create. Operating system error 50(The request is not supported.).

myserver$myinstance is probably the issue.

**Comment by olsonnn** [comment]
totally different issue. sorry

**Comment by olahallengren** [comment]
Could you share some information about what was causing this?

I am puzzled that there are sub-directories when ```@DirectoryStructure = NULL```.
