### ISSUE TITLE
Add the option to send backup to NUL for Linux hosted SQL servers

### ISSUE THREAD

**Issue by BHubartt38** [olahallengren/sql-server-maintenance-solution#409]
On 2019-06-13 you released an update that gave [dbo].[DatabaseBackup] the ability to backup to NUL ( https://github.com/olahallengren/sql-server-maintenance-solution/issues/80 ).

Can you please extend this ability to SQL servers that are running Linux in addition to Windows.

I attempted to use the same command that was posted in the previous feature request and it generated an error saying that the parameter is invalid.  I looked at the TSQL and it is tying the "NUL" directory option to Windows.

**Comment by olahallengren** [comment]
Do you know if NUL means the same thing on Linux as on Windows?

Have you tested that it works to back up to NUL on Linux, using a BACKUP DATABASE command?

**Comment by olahallengren** [comment]
I have added support for backup to NUL on Linux.
https://ola.hallengren.com/versions.html

**Comment by srutzky** [comment]
Unix / Linux uses `/dev/null` instead of the `NUL` or `NUL:` that Windows uses. However, that does not seem to work for the `BACKUP DATABASE` command when using SQL Server on Linux:

```sql
BACKUP DATABASE [model] TO DISK = '/dev/null' WITH INIT;

/*
Msg 3634, Level 16, State 2, Line XXXXX
The operating system returned the error '31(A device attached to the system is not functioning.)' while
      attempting 'DiskChangeFileSize' on '/dev/null'.
Msg 3013, Level 16, State 1, Line XXXXX
BACKUP DATABASE is terminating abnormally.
*/
```

However , it does appear that both `NUL` and `NUL:` do, in fact, work when using SQL Server on Linux:

```sql
BACKUP DATABASE [model] TO DISK = 'NUL' WITH INIT;

BACKUP DATABASE [model] TO DISK = 'NUL:' WITH INIT;
```

Both worked for me when using the following:

* 2017 CU22
* 2019 CU8

**Comment by olahallengren** [comment]
@srutzky, that is good to know. Thank you for the testing.

**Comment by BHubartt38** [comment]
@olahallengren, Thank you for adding this support for Linux.
@srutzky, Thank you for the testing

**Comment by srutzky** [comment]
@olahallengren and @BHubartt38 : you're welcome!

Also, just to have this documented:

I have just confirmed that both `NUL` and `NUL:` also work on:

* Azure SQL Edge (RTM) - 15.0.2000.1552.

And, just in case it matters, the Linux testing was done on:

* Ubuntu 18.04.5 LTS via containers and Docker
