### ISSUE TITLE
Allow including/excluding of statistics to rebuild

### ISSUE THREAD

**Issue by leepfrog-ger** [olahallengren/sql-server-maintenance-solution#41]
Hello Ola,

thanks for your really great solution which I've worked with during the last years.
One scenario however came up several times, which (to my understanding) is not yet possible. Maybe you can consider it as feature request:

For the index Maintenance you already can either exclude specific indices from the rebuild or chose to only consider specific indices. 
Would it be possible to apply the same logic to statistics?

My use case is that I have a scheduled statistic maintenace with `OnlyModifiedStatistics = Y`, however I have a small number of large tables which take ages to built statistics on, but these tables are rarely used for select queries (mostly data is just written into these tables in new rows). So even though the data was modified I can live with not up-to-date statistics.

It would be great to have a possibility to exclude those particular statistics (either by table name or by statistic name) from the scheduled rebuild and only include those in less frequest rebuilds.

Thanks for considering and keep up the good work!

**Comment by olahallengren** [comment]
You can use the Indexes parameter for this.

```
EXECUTE dbo.IndexOptimize
@Databases = 'WideWorldImporters',
@FragmentationLow = NULL,
@FragmentationMedium = NULL,
@FragmentationHigh = NULL,
@UpdateStatistics = 'ALL',
@Indexes = 'WideWorldImporters.Sales.Invoices'

EXECUTE dbo.IndexOptimize
@Databases = 'WideWorldImporters',
@FragmentationLow = NULL,
@FragmentationMedium = NULL,
@FragmentationHigh = NULL,
@UpdateStatistics = 'ALL',
@Indexes = 'ALL_INDEXES, -WideWorldImporters.Sales.Invoices'
```
