### ISSUE TITLE
Support for incremental statistics

### ISSUE THREAD

**Issue by mrscore** [olahallengren/sql-server-maintenance-solution#42]
Would like support for incremental statistics that was introduced with SQL Server 2014. 
It would be very nice to be able to cut down maintenance time on big partitioned tables even more, and be able to maintain good quality stats without scanning too much. 
Perhaps run it at the same time when executing partitioned index maintenance, and update the stats for the same partition, if the option is turned on?

Thanks,
Jan

**Comment by blazdax** [comment]
Agreed, this would be a great feature upgrade.
You can use `sys.dm_db_incremental_stats_properties` - for example, the modification_counter column to help identify partitions with changes.

**Comment by olahallengren** [comment]
I am working on adding support for incremental statistics. I am planning to use ```sys.dm_db_incremental_stats_properties```.

I am thinking about if there should be a parameter to update statistics on the partiton - level for incremental statistics, or if I should do it automatically if ```@PartitionLevel = 'Y'```. Any thoughts on this?

**Comment by tboggiano** [comment]
I vote for automatic and let me know again if need aomeken to test this feature.  It will replace a process I wrote a while back.

**Comment by olahallengren** [comment]
I have a test version now in the branch [feature-incremental-statistics].

I haven't decided about the parameter question. In this version I have a parameter ```@IncrementalStatistics = 'Y'``` that you can use. If you are specifying ```@OnlyModifiedStatistics = 'Y'``` it will check ```sys.dm_db_incremental_stats_properties```. It has been tested on SQL Server 2017.

**Comment by olahallengren** [comment]
I have also been doing some testing with a version that does not have a parameter.

It has some code like this that decides if statistics should be updated on the partition level.

```SET @PartitionLevelStatistics = CASE WHEN @PartitionLevel = 'Y' AND ((@Version >= 12.05 AND @Version < 13) OR @Version >= 13.04422) THEN 1 ELSE 0 END```

The version numbers are the versions where ```sys.dm_db_incremental_stats_properties``` is available.

**Comment by BlitzErik** [comment]
@olahallengren to make stuff like that easier, I like to have a bit variable that gets set to true or false based on if objects exist in system views. This helps you from having to increment higher version numbers later, or lower version numbers if MS back ports things. 

For example:

```
DECLARE @IncrementalStats BIT;

SELECT @IncrementalStats
    = CASE WHEN EXISTS ( SELECT 1/0 
	                     FROM sys.all_objects AS ao 
						 WHERE ao.name = 'dm_db_incremental_stats_properties' )
           THEN 1 
		   ELSE 0 
	  END;

PRINT @IncrementalStats;

```

**Comment by olahallengren** [comment]
This is a very good idea. Thanks, Erik.

**Comment by olahallengren** [comment]
I have updated the version in the [feature-incremental-statistics] branch, so that it does not have a new parameter. You can just use it like this:

```
EXECUTE dbo.IndexOptimize
@Databases = 'USER_DATABASES',
@UpdateStatistics = 'ALL',
@OnlyModifiedStatistics = 'Y'
```

**Comment by olahallengren** [comment]
I have now released a new version with support for incremental statistics. It will automatically update statistics on the partition level for incremental statistics, if you have ```@PartitionLevel = 'Y'``` (which is the default).
https://ola.hallengren.com/versions.html
