### ISSUE TITLE
emc (datadomain boost) backups do not perform a delete of old backup files

### ISSUE THREAD

**Issue by strinhmofo** [olahallengren/sql-server-maintenance-solution#420]
**Description of the issue**
The documentation states that by default after a successful backup, the old backup files outside of the cleanup value will get deleted.  We are using EMC's Data Domain Boost backup procedures and find that they are not being deleted.

I've reviewed the DatabaseBackup procedure and did not find the emc_run_delete procedure in the code.

**SQL Server version and edition**
Execute ```SELECT @@VERSION```
Microsoft SQL Server 2016 (SP2-GDR) (KB4532097) - 13.0.5102.14 (X64)   Dec 31 2019 22:39:35   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

This occurs on 2008 - 2016 versions.  I haven't not tested on 2019 yet.

**Version of the script**
Check the header of the stored procedure
  --// Version: 2020-01-26 14:06:53   

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup]
  @Databases                   = 'model'
  ,@BackupSoftware             = 'DATA_DOMAIN_BOOST'
  ,@BackupType                 = 'FULL'
  ,@ChangeBackupType           = 'Y'
  ,@CheckSum                   = 'N'
  ,@CleanupTime                = 336 --14 DAYS 
  ,@Compress                   = 'N'
  ,@DataDomainBoostDevicePath  = '/ddb_path'
  ,@DataDomainBoostHost        = 'ddb_host.mofo.com'
  ,@DataDomainBoostLockboxPath = 'C:\Program Files\DPSAPPS\common\lockbox'
  ,@DataDomainBoostUser        = 'ddb_username'
  ,@Description                = 'Scheduled Daily Full Backup'
  ,@Encrypt                    = 'N'
  ,@LogToTable                 = 'Y'

**What output are you getting?**
Start time: Fri Oct 02 16:32:04 2020 
Computer name: servername User name: serviceaccount
Check the detailed logs at 'D:\Program Files\DPSAPPS\MSAPPAGENT\logs\ddbmsqlsv.log'. 
Version information for D:\Program Files\DPSAPPS\MSAPPAGENT\bin\ddbmsqlsv.exe: Original file name: ddbmsqlsv.exe Version: 19.4.0.0.Build.21 Comments: A Dell EMC product that allows backup and recovery of Microsoft applications 
52701:ddbmsqlsv: Command line: 
  D:\Program Files\DPSAPPS\MSAPPAGENT\bin\ddbmsqlsv.exe -c SAWFSSQL01 -l full -y +14d -S 1 -b Scheduled Daily Full Backup -a NSR_DFA_SI_DD_HOST=awdatadom01.mofo.com -a NSR_DFA_SI_DD_USER=ddb_user -a NSR_DFA_SI_DEVICE_PATH=/ddb_path -a NSR_DFA_SI_DD_LOCKBOX_PATH=C:\Program Files\DPSAPPS\common\lockbox -a NSR_SKIP_NON_BACKUPABLE_STATE_DB=TRUE MSSQL:model  
Backing up model... 
BACKUP database [model] TO virtual_device='EMC#32b2d579-3b9f-4075-aaef-91bf4ae31d03' WITH name=N'DDBMMSSQL', description=N'MSSQL:model', mediadescription=N'6ad9a07f-c21e-451d-a139-a7b2bd4507a2', maxtransfersize = 4194304, EXPIREDATE=N'2020-10-16T16:32:04' 
. 
Processed 328 pages for database 'model', file 'modeldev' on file 1. 
Backup of model succeeded. 
Successfully completed databases 
============================== 
model 
Backup succeeded. 
Stop time: Fri Oct 02 16:32:07 2020

**Comment by olahallengren** [comment]
>The documentation states that by default after a successful backup, the old backup files outside of the cleanup value will get deleted. We are using EMC's Data Domain Boost backup procedures and find that they are not being deleted.

>I've reviewed the DatabaseBackup procedure and did not find the emc_run_delete procedure in the code.

DatabaseBackup will only set the -y option that is the expiry time. 

You need to have a separate job then runs dbo.emc_run_delete to delete the backups.

When I added support for Data Domain Boost, I could not find a way to run dbo.emc_run_delete only for specific databases. Because of that I decided not to include it in DatabaseBackup.
