### ISSUE TITLE
Not getting compression with @Compress = 'Y'

### ISSUE THREAD

**Issue by patrick-steele** [olahallengren/sql-server-maintenance-solution#427]
**Description of the issue**
Setting @Compress = 'Y' does not result in "COMPRESSION" option be included in BACKUP command.

**SQL Server version and edition**
Microsoft SQL Azure (RTM) - 12.0.2000.8   Sep 11 2020 22:32:15   Copyright (C) 2019 Microsoft Corporation 

**Version of the script**
2019-02-10 10:40:47

**What command are you executing?**
```
EXECUTE dbo.DatabaseBackup
	@Databases = 'ALPHA',
	@URL = 'https://something.blob.core.windows.net/development',
	@BackupType = 'FULL',
	@CheckSum = 'Y',
	@Compress = 'Y',
	@CopyOnly = 'Y',
	@LogToTable = 'Y',
	@MaxTransferSize = 4194304,
	@BlockSize = 65536,
	@DirectoryStructure = 'WEEKLY',
	@FileName = '{Year}-{Month}-{Day}-{DatabaseName}_{BackupType}_{CopyOnly}.{FileExtension}',
	@Execute = @execute;
```

**What output are you getting?**
Date and time: 2020-10-20 01:30:22
Server: xxxx.database.windows.net
Version: 12.0.2000.8
Edition: SQL Azure
Platform: Windows
Procedure: [SQLAdmin].[dbo].[DatabaseBackup]
Parameters: @Databases = 'ALPHA', @Directory = NULL, @BackupType = 'FULL', @Verify = 'N', @CleanupTime = NULL, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'Y', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'Y', @BlockSize = 65536, @BufferCount = NULL, @MaxTransferSize = 4194304, @NumberOfFiles = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = 'https://something.blob.core.windows.net/development', @Credential = NULL, @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = 'WEEKLY', @AvailabilityGroupDirectoryStructure = '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{Year}-{Month}-{Day}-{DatabaseName}_{BackupType}_{CopyOnly}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'N'
Version: 2019-02-10 10:40:47
Source: https://ola.hallengren.com
	
Date and time: 2020-10-20 01:30:22
Database: [ALPHA]
Status: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Is accessible: Yes
Recovery model: FULL
Encrypted: Yes
Differential base LSN: 26028000399648800202
Last log backup LSN: 26472000049663200001
	
Date and time: 2020-10-20 01:30:23
Command: BACKUP DATABASE [ALPHA] TO URL = N'https://something.blob.core.windows.net/development/WEEKLY/2020-10-20-ALPHA_FULL_COPY_ONLY.bak' WITH CHECKSUM, NO_COMPRESSION, COPY_ONLY, BLOCKSIZE = 65536, MAXTRANSFERSIZE = 4194304
Outcome: Not Executed
Duration: 00:00:00
Date and time: 2020-10-20 01:30:23
	
Date and time: 2020-10-20 01:30:23

Completion time: 2020-10-19T21:30:23.2487834-04:00

**Comments**
It seems the issue is caused by this line of code:

```
IF @Version >= 10
BEGIN
	SET @CurrentCommand += CASE WHEN @Compress = 'Y' AND (@CurrentIsEncrypted = 0 OR (@CurrentIsEncrypted = 1 AND @Version >= 13 AND @CurrentMaxTransferSize > 65536)) THEN ', COMPRESSION' ELSE ', NO_COMPRESSION' END
END
```

I'm not sure why using compression with an encrypted database and maxtransfersize > 65536 is limited to only version 13 and higher.  The command generated above (using NO_COMPRESSION) fails for us but manually running the same BACKUP DATABASE command but using "COMPRESSION" works fine on our TDE-encrypted database under 12.0.2000.8.  In fact, it was a recommendation from Microsoft that told us to use COMPRESSION.  I'm wondering if this limitation is related to this [comment in the docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/backup-transact-sql?view=sql-server-ver15#general-remarks):

> Starting with SQL Server 2016 (13.x), setting MAXTRANSFERSIZE larger than 65536 (64 KB) enables an optimized compression algorithm for Transparent Data Encryption (TDE) encrypted databases that first decrypts a page, compresses it, and then encrypts it again. If MAXTRANSFERSIZE is not specified, or if MAXTRANSFERSIZE = 65536 (64 KB) is used, backup compression with TDE encrypted databases directly compresses the encrypted pages, and may not yield good compression ratios.

But I don't see why that should prevent the use of compression.

**Comment by olahallengren** [comment]
@patrick-steele, thank you for reporting this issue. It looks like a bug in DatabaseBackup.

Could you please confirm that you are running on an Azure SQL Database Managed Instance?

**Comment by olahallengren** [comment]
I made a fix in the branch hotfix-managed-instance-compression. Could you please test it?
