### ISSUE TITLE
Backup files pruning does not work in Linux when @Directory is passed as null

### ISSUE THREAD

**Issue by DanielAdeniji** [olahallengren/sql-server-maintenance-solution#430]
**Description of the issue**

**SQL Server version and edition**
Execute ```SELECT @@VERSION```

Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64) 
	Sep 23 2020 16:03:08 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (CentOS Linux 8 (Core)) <X64>

**Version of the script**
Check the header of the stored procedure
2020-10-25 18:05:29 

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup]
      @Databases = 'USER_DATABASES'
    , @Directory = NULL
    , @BackupType = 'FULL'
    , @Verify = 'Y'
    , @CleanupTime = 96
    , @CheckSum = 'Y'
    , @LogToTable = 'Y'

**What output are you getting?**
Date and time: 2020-10-25 15:27:52
Database context: [master]
Command: DECLARE @ReturnCode int EXECUTE @ReturnCode = dbo.xp_delete_file 0, N'./dbsqlserver/lab/FULL', 'bak', '2020-10-21T15:27:52' IF @ReturnCode <> 0 RAISERROR('Error deleting files.', 16, 1)
**Msg 22049, Level 15, State 0, Line 0
Error executing extended stored procedure: Invalid Parameter**
Msg 50000, Level 16, State 1, Line 1
Error deleting files.
Outcome: Failed
Duration: 00:00:00
Date and time: 2020-10-25 15:27:52

**Comment by olahallengren** [comment]
This issue has been fixed now.
https://ola.hallengren.com/versions.html

**Comment by DanielAdeniji** [comment]
Confirmed issue resolved as of Version dated 1 Nov 2020.

Tested against Microsoft SQL Server 2019 on a Linux Cent-OS engine.

Daniel Adenji
