### ISSUE TITLE
Backup to Blob Storage error

### ISSUE THREAD

**Issue by jemaccou** [olahallengren/sql-server-maintenance-solution#431]
While backing up to Azure Blob Storage error received : Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 2268 [Batch Start Line 28]
The value for the parameter @Credential is not supported.

Ola Scripts details
SchemaName	                        ObjectName	                      Version	                      Checksum
dbo	                                         CommandExecute	               2020-01-26 14:06:53	431750767
dbo	                                          DatabaseBackup	                2020-01-26 14:06:53	-1034257979
dbo	                                          DatabaseIntegrityCheck	2020-01-26 14:06:53	417283523
dbo	                                          IndexOptimize	                2020-01-26 14:06:53	1528201776

SQL Server Details
Microsoft SQL Server 2012 (SP4-GDR) (KB4532098) - 11.0.7493.4 (X64)   Dec 24 2019 19:33:24   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

Full error details
Date and time: 2020-10-29 10:49:35
Server: SQL09
Version: 11.0.7493.4
Edition: Standard Edition (64-bit)
Platform: Windows
Procedure: [master].[dbo].[DatabaseBackup]
Parameters: @Databases = 'SEC-old', @Directory = NULL, @BackupType = 'FULL', @Verify = 'N', @CleanupTime = NULL, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'Y', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'N', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @MinBackupSizeForMultipleFiles = NULL, @MaxFileSize = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = 'https://stordiipusscsqlbkup2.blob.core.windows.net/sql-backup/sec-old.bak', @Credential = NULL, @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @AvailabilityGroupDirectoryStructure = '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @Format = 'N', @ObjectLevelRecoveryMap = 'N', @StringDelimiter = ',', @DatabaseOrder = NULL, @Dat...
Version: 2020-01-26 14:06:53
Source: https://ola.hallengren.com
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 2268 [Batch Start Line 28]
The value for the parameter @Credential is not supported.
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 2268 [Batch Start Line 28]
The documentation is available at https://ola.hallengren.com/sql-server-backup.html.
	
Date and time: 2020-10-29 10:49:35

**Comment by olahallengren** [comment]
When you are backing up to URL on SQL Server 2012, you need to specify the ```@Credential``` parameter.

https://techcommunity.microsoft.com/t5/datacat/sql-server-backup-to-url-a-cheat-sheet/ba-p/346358
