### ISSUE TITLE
Database not doing differential backups

### ISSUE THREAD

**Issue by Clifra-Jones** [olahallengren/sql-server-maintenance-solution#432]
I have a database that is not doing differential backups. In the DIFF log file it is running a full backup.
Here is the previous database in the log.
`Date and time: 2020-11-04 00:00:06 [SQLSTATE 01000]
Database: [AvectoReporting] [SQLSTATE 01000]
Status: ONLINE [SQLSTATE 01000]
Standby: No [SQLSTATE 01000]
Updateability: READ_WRITE [SQLSTATE 01000]
User access: MULTI_USER [SQLSTATE 01000]
Is accessible: Yes [SQLSTATE 01000]
Recovery model: SIMPLE [SQLSTATE 01000]
Encrypted: No [SQLSTATE 01000]
Differential base LSN: 458836000008911300259 [SQLSTATE 01000]
Differential base is snapshot: No [SQLSTATE 01000]
Last log backup LSN: N/A [SQLSTATE 01000]
Allocated extent page count: 25674696 [SQLSTATE 01000]
Modified extent page count: 6700328 [SQLSTATE 01000]
	 [SQLSTATE 01000]
Date and time: 2020-11-04 00:00:06 [SQLSTATE 01000]
Command: DECLARE @ReturnCode int EXECUTE @ReturnCode = [master].dbo.xp_create_subdir N'z:\mssql\backup\AWSSQLPRD01\AvectoReporting\DIFF' IF @ReturnCode <> 0 RAISERROR('Error creating directory.', 16, 1) [SQLSTATE 01000]
Outcome: Succeeded [SQLSTATE 01000]
Duration: 00:00:00 [SQLSTATE 01000]
Date and time: 2020-11-04 00:00:06 [SQLSTATE 01000]
	 [SQLSTATE 01000]
Date and time: 2020-11-04 00:00:06 [SQLSTATE 01000]
Command: BACKUP DATABASE [AvectoReporting] TO DISK = N'z:\mssql\backup\AWSSQLPRD01\AvectoReporting\DIFF\AWSSQLPRD01_AvectoReporting_DIFF_20201104_000006.bak' WITH CHECKSUM, NO_COMPRESSION, DIFFERENTIAL [SQLSTATE 01000]
Processed 6700336 pages for database 'AvectoReporting', file 'AvectoReporting' on file 1. [SQLSTATE 01000]
Processed 6355 pages for database 'AvectoReporting', file 'AvectoReporting_log' on file 1. [SQLSTATE 01000]
BACKUP DATABASE WITH DIFFERENTIAL successfully processed 6706691 pages in 564.938 seconds (92.746 MB/sec). [SQLSTATE 01000]
Outcome: Succeeded [SQLSTATE 01000]
Duration: 00:09:26 [SQLSTATE 01000]`

here is the database in question
`Date and time: 2020-11-04 00:13:00 [SQLSTATE 01000]
Database: [BBUS] [SQLSTATE 01000]
Status: ONLINE [SQLSTATE 01000]
Standby: No [SQLSTATE 01000]
Updateability: READ_WRITE [SQLSTATE 01000]
User access: MULTI_USER [SQLSTATE 01000]
Is accessible: Yes [SQLSTATE 01000]
Recovery model: FULL [SQLSTATE 01000]
Encrypted: No [SQLSTATE 01000]
Differential base LSN: 46361000009549500051 [SQLSTATE 01000]
Last log backup LSN: 46601000005875500001 [SQLSTATE 01000]
Allocated extent page count: 939952 [SQLSTATE 01000]
Modified extent page count: 934456 [SQLSTATE 01000]
	 [SQLSTATE 01000]
Date and time: 2020-11-04 00:13:00 [SQLSTATE 01000]
Command: DECLARE @ReturnCode int EXECUTE @ReturnCode = [master].dbo.xp_create_subdir N'z:\mssql\backup\AWSSQLPRD01\BBUS\FULL' IF @ReturnCode <> 0 RAISERROR('Error creating directory.', 16, 1) [SQLSTATE 01000]
Outcome: Succeeded [SQLSTATE 01000]
Duration: 00:00:00 [SQLSTATE 01000]
Date and time: 2020-11-04 00:13:00 [SQLSTATE 01000]
	 [SQLSTATE 01000]
Date and time: 2020-11-04 00:13:00 [SQLSTATE 01000]
Command: BACKUP DATABASE [BBUS] TO DISK = N'z:\mssql\backup\AWSSQLPRD01\BBUS\FULL\AWSSQLPRD01_BBUS_FULL_20201104_001300.bak' WITH CHECKSUM, NO_COMPRESSION [SQLSTATE 01000]
Processed 953760 pages for database 'BBUS', file 'BBUSDataMart' on file 1. [SQLSTATE 01000]
Processed 6 pages for database 'BBUS', file 'BBUSDataMart_log' on file 1. [SQLSTATE 01000]
BACKUP DATABASE successfully processed 953766 pages in 48.394 seconds (153.971 MB/sec). [SQLSTATE 01000]
Outcome: Succeeded [SQLSTATE 01000]
Duration: 00:00:49 [SQLSTATE 01000]`

If I do a manual Differential backup it does do a differential backup.

One thing to mention is the database was renamed "after" these scripts were configured.

**Comment by Clifra-Jones** [comment]
Also, ChangeBackupType is set to Y in the job

**Comment by olahallengren** [comment]
Could I see the command that you are running, with all the parameters?

**Comment by Clifra-Jones** [comment]
Here you are.

EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@Directory = N'z:\mssql\backup',
@BackupType = 'DIFF',
@Verify = 'Y',
@CleanupTime = 168,
@CheckSum = 'Y',
@LogToTable = 'Y',
@ChangeBackupType = 'Y',
@ModificationLevel = 50

**Comment by olahallengren** [comment]
This happens because you have specified ```@ModificationLevel```.
https://ola.hallengren.com/sql-server-backup.html#ModificationLevel

As you can see, almost all of the extents have been modified.
Allocated extent page count: 939952
Modified extent page count: 934456

You have specified that if 50% or more of the extents have been modified, it should change to a full backup.

**Comment by Clifra-Jones** [comment]
Cool, now I know what to look for in the future.
