### ISSUE TITLE
DIFFs randomly are promoted to FULLs

### ISSUE THREAD

**Issue by onedashkivskyi** [olahallengren/sql-server-maintenance-solution#433]
We use DatabaseBackup stored procedure to backup a load of SharePoint databases on a SQL2012 instance into Azure blob storage. We have been doing this for quite a while without any issues however for the last 6 weeks our DIFFs are randomly being promoted to FULL and we cannot see why.

This is the output from the agent step
`BACKUP DATABASE [Database] TO URL = N'https://strorgage.blob.core.windows.net/server/instance/Database/2020/11/diff/Database_FULL_20201105_200000.bak' 
WITH NO_CHECKSUM, COMPRESSION, CREDENTIAL = N'storeageaccountname'
`

DatabaseBackup (Ola proc) is from 2019-06-14 so it needs an upgrade to be fair, but it has worked well for over 18 months.

We do not call Ola code directly as we have a small wrapper procedure which builds up the virtual pathname for Azure, but essentially this is how we call Ola's code.

This is an issue were for some unknown reason DIFF backups are being promoted to FULL, this causes petabytes of Azure blob bakups instead of gigabytes - each day.
[
![image](https://user-images.githubusercontent.com/74175383/98515071-2a3a9d80-2273-11eb-8210-91ebe84787f9.png)
](url)

Do you have any thoughts on that? Thanks in advance.

**Comment by olahallengren** [comment]
Could you share the text output from DatabaseBackup, for when this happens?

**Comment by onedashkivskyi** [comment]
Here is the output:

> Message
> Executed as user: HYPERION\srv_spxsql01_sp4. ...1-08 20:00:00 [SQLSTATE 01000] (Message 50000)  Server: spxsql01\SPXHIG [SQLSTATE 01000] (Message 50000)  Version: 11.0.7493.4 [SQLSTATE 01000] (Message 50000)  Edition: Enterprise Edition: Core-based Licensing (64-bit) [SQLSTATE 01000] (Message 50000)  Platform: Windows [SQLSTATE 01000] (Message 50000)  Procedure: [iDBA].[dbo].[DatabaseBackup] [SQLSTATE 01000] (Message 50000)  Parameters: @Databases = 'DMS_Content_Casualty', @Directory = NULL, @BackupType = 'DIFF', @Verify = 'N', @CleanupTime = NULL, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'N', @ChangeBackupType = 'Y', @BackupSoftware = NULL, @CheckSum = 'N', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @MinBackupSizeForMultipleFiles = NULL, @MaxFileSize = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = 'https://strbkp.blob.core.windows.net/spxsql01/SPXHIG/dms_content_casualty/2020/11/diff/', @Credential = 'strbkp', @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'READ_WRITE', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = NULL, @AvailabilityGroupDirectoryStructure = NULL, @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @Format = 'N', @ObjectLevelRecoveryMap = 'N', @StringDelimiter = ',', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y' [SQLSTATE 01000] (Message 50000)  Version: 2020-11-01 18:16:36 [SQLSTATE 01000] (Message 50000)  Source: https://ola.hallengren.com [SQLSTATE 01000] (Message 50000)  	 [SQLSTATE 01000] (Message 50000)  Date and time: 2020-11-08 20:00:01 [SQLSTATE 01000] (Message 50000)  Database: [DMS_Content_Casualty] [SQLSTATE 01000] (Message 50000)  State: ONLINE [SQLSTATE 01000] (Message 50000)  Standby: No [SQLSTATE 01000] (Message 50000)  Updateability: READ_WRITE [SQLSTATE 01000] (Message 50000)  User access: MULTI_USER [SQLSTATE 01000] (Message 50000)  Recovery model: FULL [SQLSTATE 01000] (Message 50000)  Encrypted: No [SQLSTATE 01000] (Message 50000)  Is accessible: Yes [SQLSTATE 01000] (Message 50000)  Log shipping role: PRIMARY [SQLSTATE 01000] (Message 50000)  Differential base LSN: 852000000137600044 [SQLSTATE 01000] (Message 50000)  Last log backup LSN: 852000000144800001 [SQLSTATE 01000] (Message 50000)  	 [SQLSTATE 01000] (Message 50000)  Date and time: 2020-11-08 20:00:01 [SQLSTATE 01000] (Message 50000)  Database context: [master] [SQLSTATE 01000] (Message 50000)  Command: BACKUP DATABASE [DMS_Content_Casualty] TO URL = N'https://strbkp.blob.core.windows.net/spxsql01/SPXHIG/dms_content_casualty/2020/11/diff/spxsql01$SPXHIG_DMS_Content_Casualty_FULL_20201108_200001.bak' WITH NO_CHECKSUM, COMPRESSION, CREDENTIAL = N'strbkp' [SQLSTATE 01000] (Message 50000)  Processed 5976 pages for database 'DMS_Content_Casualty', file 'DMS_Content_Casualty' on file 1. [SQLSTATE 01000] (Message 4035)  Processed 3 pages for database 'D...  The step succeeded.

**Comment by olahallengren** [comment]
Did you find out about this issue?

**Comment by olahallengren** [comment]
I have been looking at this. It looks like there is a bug in the logging. I have fixed that now. Could you please download the latest version?

**Comment by onedashkivskyi** [comment]
Thank you.

We also found what the problem was. it was SQL Server VSS writer and it broke the backup chain.

**Comment by olahallengren** [comment]
@onedashkivskyi, thank you for the update. That is good to know.
