### ISSUE TITLE
Add parameter to override exclusion of Log Shipping primary databases from transaction log backups

### ISSUE THREAD

**Issue by nharris18** [olahallengren/sql-server-maintenance-solution#435]
I have backup procedures set up using your fine SQL Server Maintenance Solution which work really well.

Recently, a need arose for setting up Log Shipping to synchronise several databases. Rather than splitting the backup solution between the LS jobs created when setting up Log Shipping and the existing jobs, I figured I would just use the backups created by the existing jobs (they're already in a folder accessible to the secondary databases).

Took me a while to figure out why I was no longer getting Tx log backups of my primaries - SQL Server Backup excludes them (which I fully understand as a default). But could there not be a parameter to this procedure, allowing those backups to be run anyway, allowing them to be used in LS?

**Comment by olahallengren** [comment]
Is there an advantage to use the wizard to configure Log Shipping, if you are not using the jobs that it creates?

**Comment by nharris18** [comment]
I try, as far as possible, to use the “standard” way to set things up so others who take over from me will understand but, having an established backup routine for all databases, felt it made sense to retain it.

**Comment by olahallengren** [comment]
I have added a parameter to exclude databases configured for Log Shipping from log backups.
https://ola.hallengren.com/sql-server-backup.html#ExcludeLogShippedFromLogBackup

The default is 'Y', but you can set it to 'N', if you prefer that.

**Comment by nharris18** [comment]
Many thanks!
