### ISSUE TITLE
Error on CommandLogSelect

### ISSUE THREAD

**Issue by ntex777** [olahallengren/sql-server-maintenance-solution#438]
Error while running CommandLogSelect

**SQL Server version and edition**
`Microsoft SQL Server 2016 (SP2-CU15) (KB4577775) - 13.0.5850.14 (X64)   Sep 17 2020 22:12:45   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19042: ) `

**Version of the script**
`Version: 2020-11-15 14:55:23`

**What command are you executing?**
```
SELECT DatabaseName,
       SchemaName,
       ObjectName,
       CASE WHEN ObjectType = 'U' THEN 'USER_TABLE' WHEN ObjectType = 'V' THEN 'VIEW' END AS ObjectType,
       IndexName,
       CASE WHEN IndexType = 1 THEN 'CLUSTERED' WHEN IndexType = 2 THEN 'NONCLUSTERED' WHEN IndexType = 3 THEN 'XML' WHEN IndexType = 4 THEN 'SPATIAL' END AS IndexType,
       PartitionNumber,
       ExtendedInfo.value('(ExtendedInfo/PageCount)[1]','int') AS [PageCount],
       ExtendedInfo.value('(ExtendedInfo/Fragmentation)[1]','float') AS Fragmentation,
       CommandType,
       Command,
       StartTime,
       EndTime,
       CASE WHEN DATEDIFF(ss,StartTime, EndTime)/(24*3600) > 0 THEN CAST(DATEDIFF(ss,StartTime, EndTime)/(24*3600) AS nvarchar) + '.' ELSE '' END + RIGHT(CONVERT(nvarchar,EndTime - StartTime,121),12) AS Duration,
       ErrorNumber,
       ErrorMessage
FROM dbo.CommandLog
WHERE CommandType = 'ALTER_INDEX'
ORDER BY StartTime ASC
```

**What output are you getting?**
```
Msg 8117, Level 16, State 1, Line 14
Operand data type datetime2 is invalid for subtract operator.
```

I replaced this `RIGHT(CONVERT(nvarchar,EndTime - StartTime,121),12) AS Duration,` for this:
`LEFT(CAST(DATEADD(ms,DATEDIFF(ms,StartTime,EndTime),0) AS time), 12) AS Duration,`

And now works fine like this.

Regardless, it's my first time using your project and I'm mind blown, it's really awesome work here.

**Comment by olahallengren** [comment]
This issue has been fixed. I used your code. Thank you.
