### ISSUE TITLE
IndexOptimize: add parameter for statistics modification_counter

### ISSUE THREAD

**Issue by vesajuvonenx** [olahallengren/sql-server-maintenance-solution#44]
IndexOptimize: add parameter for statistics modification_counter

**Comment by olahallengren** [comment]
You have the parameter OnlyModifiedStatistics, that is checking the modification_counter in sys.dm_db_stats_properties. If it is set to 'Y' it will only update the statistics if modification_counter > 0.

https://ola.hallengren.com/sql-server-index-and-statistics-maintenance.html#OnlyModifiedStatistics

**Comment by vesajuvonenx** [comment]
Hi sorry I was not precise...
I would like to have a parameter telling, for example, that if more than 1000 modifications have occurred, then update statistics, but not if less than 1000.

**Comment by gmparker** [comment]
IndexOptimize Customization - Modify the process to check for changes to statistics to use a percentage of rows that have changed instead of the default value of > 0, So something like 'WHERE modification_counter * 1.00 / rows * 100 > ' + @StatisticsPercentage' instead of 'modification_counter > 0 '

Thanks for your consideration.

**Comment by olahallengren** [comment]
A percentage parameter is a great idea.

Could it be an idea to also have an option to use the new decreasing dynamic threshold (that is used in auto-update-statistics)?

**Comment by blazdax** [comment]
How would that (the option to use the decreasing dynamic threshold) work in combination with the percentage parameter?

**Comment by olahallengren** [comment]
I am thinking that there are different ways of defining a theshold for when statistics should be updated:

1. A percentage

2. A number of rows

3. Using the legacy auto-update-stats formula

4. Using the new auto-update-stats formula with the decreasing, dynamic threshold

https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-2017

3 and 4 would enable you to have auto-update-stats disabled, but still use the same formula, when you update statistics manually.

I am not sure if all of the options are useful, or how the parameters would look like, but the user would need to select one of them.

**Comment by tboggiano** [comment]
I would find the percentage and number of rows useful.

**Comment by emieng** [comment]
I would probably use option 4.

**Comment by sidsavy** [comment]
I checked index optimize and wanted to share something which might help it to improve. I see that the where condition for updating stats is >0 which may not be a viable option for large databases. Instead if you give the following where clause and give a parameter to the user to control it might be better.

 where CAST(100 * [modification_counter] / [rows]
 AS DECIMAL(18,2)) >= 10.00 (@percent)

**Comment by olahallengren** [comment]
One problem with only using a percentage is that it is not working well for tables with large number of rows.

This is the reason Microsoft introduced the new decreasing, dynamic statistics update threshold in SQL Server 2016 (and before that with trace flag 2371).

One idea could be to combine a percentage parameter, with the decreasing, dynamic threshold (square root of the product of 1000 and the current table cardinality).

https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-2017

https://blogs.msdn.microsoft.com/saponsqlserver/2011/09/07/changes-to-automatic-update-statistics-in-sql-server-traceflag-2371/

**Comment by olahallengren** [comment]
One idea could be to do like this:

A new parameter, ```@StatisticsModificationLevel```, that is a percentage.

And then code like this:

```
((@CurrentModificationCounter * 1. / @CurrentRowCount) * 100 >= @StatisticsModificationLevel)
OR (@StatisticsModificationLevel IS NOT NULL AND (@CurrentModificationCounter >= SQRT(@CurrentRowCount * 1000)))
```

Statistics would get updated when the percentage of modified pages is equal or greater than the parameter, or when the decreasing, dynamic threshold has been reached.

**Comment by emieng** [comment]
Good solution. IndexOptimize and SQL Server uses the same treshold by default - but it is possible to override default with a lower value.

**Comment by olahallengren** [comment]
Thank you for the feedback. I have created a branch, [feature-statistics_modification_level] with this feature.

Here's how to use it:
```
EXECUTE dbo.IndexOptimize
@Databases = 'USER_DATABASES',
@FragmentationLow = NULL,
@FragmentationMedium = NULL,
@FragmentationHigh = NULL,
@UpdateStatistics = 'ALL',
@StatisticsModificationLevel = 10
```
Please try it out.

**Comment by vesajuvonenx** [comment]
Thank you Ola so much!

**Comment by emieng** [comment]
Thank you Ola - for this long awaited feature !
The use of Incremental statistics and modification_counter in database maintenance, makes us use the full potential of partitioning and SQL Server 2016.
Weekly maintenance time for one of our databases in a test environment was reduced from 8+ hours to 90 minutes!

**Comment by olahallengren** [comment]
I have now added the parameter ```@StatisticsModificationLevel```.
https://ola.hallengren.com/versions.html

```
EXECUTE dbo.IndexOptimize
@Databases = 'USER_DATABASES',
@FragmentationLow = NULL,
@FragmentationMedium = NULL,
@FragmentationHigh = NULL,
@UpdateStatistics = 'ALL',
@StatisticsModificationLevel = 10
```

https://ola.hallengren.com/sql-server-index-and-statistics-maintenance.html#StatisticsModificationLevel

**Comment by olahallengren** [comment]
Erin Stellato wrote a blog post that describes this option very well.
https://www.sqlskills.com/blogs/erin/updating-statistics-with-ola-hallengrens-script/

**Comment by rajuvd** [comment]
Thank @olahallengren  for implementing @StatisticsModificationLevel. How do I generate a statistics report based on above parameter. Appreciate if you can share the script to full the statistics report.
