### ISSUE TITLE
The value for the parameter @CleanupTime is not supported. Cleanup is not supported if the token {BackupType} is not part of the directory.

### ISSUE THREAD

**Issue by JParkACR** [olahallengren/sql-server-maintenance-solution#440]
Msg 50000, Level 16, State 6, Procedure dbo.DatabaseBackup, Line 2266 [Batch Start Line 0]
The value for the parameter @CleanupTime is not supported. Cleanup is not supported if the token {BackupType} is not part of the directory.

SQL Server version 2019, Standard edition.
Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64) 
	Sep 23 2020 16:03:08 
	Copyright (C) 2019 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Version of the script**
Version: 2020-11-15 18:44:03

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@Directory = N'J:',
@DirectoryStructure='{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}',
@BackupType = 'FULL',
@Verify = 'N',
@CleanupTime = 72,
@CheckSum = 'Y',
@LogToTable = 'Y'

**What output are you getting?**
Date and time: 2020-11-18 15:39:54
Server: C**-******SQL19
Version: 15.0.4073.23
Edition: Standard Edition (64-bit)
Platform: Windows
Procedure: [master].[dbo].[DatabaseBackup]
Parameters: @Databases = 'USER_DATABASES', @Directory = 'J:', @BackupType = 'FULL', @Verify = 'N', @CleanupTime = 72, @CleanupMode = 'AFTER_BACKUP', @Compress = NULL, @CopyOnly = 'N', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'Y', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @MinBackupSizeForMultipleFiles = NULL, @MaxFileSize = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = NULL, @Credential = NULL, @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}', @AvailabilityGroupDirectoryStructure = '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @Format = 'N', @ObjectLevelRecoveryMap = 'N', @StringDelimiter = ',', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'
Version: 2020-11-15 18:44:03
Source: https://ola.hallengren.com
	
Msg 50000, Level 16, State 6, Procedure dbo.DatabaseBackup, Line 2266 [Batch Start Line 0]
The value for the parameter @CleanupTime is not supported. Cleanup is not supported if the token {BackupType} is not part of the directory.
	
Msg 50000, Level 16, State 1, Procedure dbo.DatabaseBackup, Line 2266 [Batch Start Line 0]
The documentation is available at https://ola.hallengren.com/sql-server-backup.html.

**Comment by JParkACR** [comment]
In the website there is no description that backupType must be part of directory to support CleanTime

**Comment by olahallengren** [comment]
@JParkACR, I know that this is not documented, but here is some background:

DatabaseBackup is using xp_delete_file to delete old backup files. (This is the same extended stored procedure that the Maintenance Plans are using.)

Here is an example:

```EXECUTE dbo.xp_delete_file 0, N'D:\Backup\ServerName$InstanceName\DatabaseName\FULL', 'bak', '2020-01-11T16:56:44'```

Now let's look at the checks that I have:

- Database name in the directory path
If the database name is not in the directory path, then it could happen that a backup of one database, is deleting a backup of another database.
 
- Backup type in the directory path
If the backup type is not in the directory path, then it could happen that a differential backup job, is deleting full backups.

- Copy_only in the directory path
If copy_only is not in the directory path then it could happen that a copy_only full backup, is deleting non copy_only full backups.

**Comment by olahallengren** [comment]
If you know that this is not an issue for you (e.g. if you are not doing differential backups), then you can comment out this check.

```
  IF @CleanupTime IS NOT NULL AND ((@DirectoryStructure NOT LIKE '%{BackupType}%' OR @DirectoryStructure IS NULL) OR (SERVERPROPERTY('IsHadrEnabled') = 1 AND (@AvailabilityGroupDirectoryStructure NOT LIKE '%{BackupType}%' OR @AvailabilityGroupDirectoryStructure IS NULL)))
  BEGIN
    INSERT INTO @Errors ([Message], Severity, [State])
    SELECT 'The value for the parameter @CleanupTime is not supported. Cleanup is not supported if the token {BackupType} is not part of the directory.', 16, 6
  END
```

**Comment by wilmerism** [comment]
afternoon, I too am getting this, I comment out the lines as suggested above. 

Can i understand more when this happens please?


Version: 2020-12-31 18:58:56
Source: https://ola.hallengren.com
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 2278 [Batch Start Line 8]
The value for the parameter @Credential is not supported.
	
Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 2278 [Batch Start Line 8]
The documentation is available at https://ola.hallengren.com/sql-server-backup.html.
	
Date and time: 2021-05-17 12:20:06

**Comment by wilmerism** [comment]
update from me... im running

Microsoft SQL Server 2014 (SP3-GDR) (KB4583463) - 12.0.6164.21 (X64)   Nov  1 2020 04:25:14   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

ive since found i cant use shared access keys. Ive now user a access key. 
 

this command works fine >> 
BACKUP DATABASE [c****s]
TO URL = 'https://ct*****.blob.core.windows.net/backups/c***ql.bak'
WITH CREDENTIAL = 'ct*az'   
     ,COMPRESSION  
     ,STATS = 1
     ,CHECKSUM ;
GO 

yet this retuens "The value for the parameter @credential is not supported." >

EXECUTE dbo.DatabaseBackup @Databases = 'USER_DATABASES' , 
@URL = 'https://ct*******.blob.core.windows.net/backups' ,
@BackupType = 'FULL',
@Compress = 'Y',
@Verify = 'Y',
@NumberOfFiles = 8,
@MaxTransferSize = 4194304,
@BlockSize = 65536

**Comment by mbento62** [comment]
Hi. I execute backkup process, but when execute the delete files, I receive this message: (I'm working with Azure storage account) The value for the parameter @CleanupTime is not supported. Cleanup is not supported on Azure Blob Storage. [SQLSTATE 42000] (Error 50000)  	 [SQLSTATE 01000] (Message 50000)  The documentation is available at https://ola.hallengren.com/sql-server-backup.html. [SQLSTATE 42000] (Error 50000)  	 [SQLSTATE 01000] (Message 50000)  Date and time: 2024-09-10 09:00:00 [SQLSTATE 01000] (Message 50000)  	 [SQLSTATE 01000] (Message 50000).  The step failed. But, I don't found explanation how I can delete files with [dbo].[DatabaseBackup] Thanks !!!
