### ISSUE TITLE
Backups of SQL 2017 AG Secondary fail

### ISSUE THREAD

**Issue by Ken-DBA** [olahallengren/sql-server-maintenance-solution#45]
I have a SQL 2017 Availability Group and when I run the command:

`EXECUTE [dbo].[DatabaseBackup] @Databases = 'USER_DATABASES', @Directory = N'H:\MSSQLBackups', @BackupType = 'FULL', @Verify = 'Y', @CleanupTime = 72, @CheckSum = 'Y', @LogToTable = 'Y'
`

on the secondary server of the AG, I get the message:

```
Msg 978, Level 14, State 1, Line 3
The target database ('AGTest') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.

```
The AG is set to allow Read-intent only connections on the secondary which is the same configuration I have in other AGs that are earlier versions of SQL Server.  Does anyone have a workaround for this?

Ken

**Comment by olahallengren** [comment]
I have fixed this bug today. Could you please download the latest version and test again.
https://ola.hallengren.com/versions.html

**Comment by Ken-DBA** [comment]
Updated version downloaded and tested.  I can confirm the problem has been fixed. 

Thank you very much for the quick fix.

Ken
