### ISSUE TITLE
Backup on Blank Directory

### ISSUE THREAD

**Issue by lukin1983** [olahallengren/sql-server-maintenance-solution#452]
Hi,
i'm using on my customers the scripts for make Backup (LOG & FULL) and Dynamically Index Rebuild.

In Backup procedure I see that I can't leave the parameter @DirectoryStructure blank, but I would like to make my backup on the root of the path specified in @Directory parameter.

I can't find how to do this.

I don't know if it's a new feature, or just exists.
Thank you for your answer.

Luigi

**Comment by lukin1983** [comment]
Resolved

**Comment by olahallengren** [comment]
You need to specify ```@DirectoryStructure = NULL```.

If you are using availability groups, you also need to specify ```@AvailabilityGroupDirectoryStructure = NULL```.

**Comment by lukin1983** [comment]
Thank you for reply.

I’m using @DirectoryStructure = ‘NULL’ with the apex.

Now it’s ok.

Best Regards.

Luigi Valente

Senior Software Engineer





EOS Solutions

Bologna
Milano
Torino

Bolzano/Bozen
Padova
Udine

Innsbruck
Perugia
Verona


mail: luigi.valente@eos-solutions.it<mailto:luigi.valente@eos-solutions.it>


legal mail: eos-solutions@legalmail.it<mailto:eos-solutions@legalmail.it>


Sede legale: Via G. Di Vittorio 23, I-39100 Bolzano (BZ)
Sede operativa: Via II Giugno 1946 8, I-40033 Casalecchio di Reno (BO)


M: +39 340 966.44.60


www.eos-solutions.it<http://www.eos-solutions.it/>




[http://www.eos-solutions.it/sig/firma.png]

Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
This e-mail (and attachments, if any) is confidential and access by anyone other than the addressee(s) is unauthorized. If you are not the intended recipient, any disclosure, copying, forwarding, or distribution of this e-mail is prohibited and immediate deletion should be effected.  We would appreciate your notifying the sender immediately should you become aware of any instances of such occurrence.


Da: Ola Hallengren <notifications@github.com>
Inviato: giovedì 26 novembre 2020 18:35
A: olahallengren/sql-server-maintenance-solution <sql-server-maintenance-solution@noreply.github.com>
Cc: Luigi Valente <Luigi.Valente@eos-solutions.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [olahallengren/sql-server-maintenance-solution] Backup on Blank Directory (#452)


You need to specify @DirectoryStructure = NULL.

If you are using availability groups, you also need to specify @AvailabilityGroupDirectoryStructure = NULL.
