### ISSUE TITLE
Re: maxtransfersize - sql 2019cu5+

### ISSUE THREAD

**Issue by SQLRocker** [olahallengren/sql-server-maintenance-solution#466]
Hi Ola,

As you might know, sql2019 cu5+ supports backup compression on TDE enabled dbs & nothing needs to be done.

However when i ran the job using your 6th Dec 2020 version, the backup is still using maxtransfersize of 65537, seems like your soln needs a update? Please let me know, thanks.

**Comment by olahallengren** [comment]
Thank you for reporting this. It has been fixed now.
https://ola.hallengren.com/versions.html

**Comment by SQLRocker** [comment]
Thanks a lot Ola! Keep up the great work!! HNY!
