### ISSUE TITLE
Ability to backup user databases (Full, Diff and Log) in explicitly specified database list

### ISSUE THREAD

**Issue by Alan-Harris** [olahallengren/sql-server-maintenance-solution#47]
Ability to backup user databases in explicit order by name as required by certain software vendors.

IE. Explicitly pass database names in required order via the @Databases = ' DBNAME3,DBNAME1,DBNAME5,DBNAME2,DBNAME4' in the job step for User Full, Diff and Log backup jobs.

**Comment by olahallengren** [comment]
I have released a new version with this feature. The databases are now backed up in the order in which they are specified. I use the database name as the second order by column.
https://ola.hallengren.com/versions.html

You can also specify just one or a few databases, before USER_DATABASES. These databases will then be backed up first.

It works the same in DatabaseBackup, DatabaseIntegrityCheck, and IndexOptimize.

**Comment by Alan-Harris** [comment]
I have tested the new version that was just released.  I verified that DatabaseBackup (Full, Diff and Log) backed up databases in the order I specified and it went on to backup the remaining databases in alphabetical order.  I also verified that both DatabaseIntegrityCheck, and IndexOptimize functioned the same way.

This is the format I used in my testing, but with actual user database names.
@Databases = ' DBNAME3,DBNAME1,DBNAME5,DBNAME2,DBNAME4,USER_DATABASES' 

No longer have to have separate job steps to backup our databases in the order required by the vendor, able to do it in a single job step again!

Thanks Ola for providing this needed functionality so quickly!

Well Done!

**Comment by CommanderBond** [comment]
This is a great feature, thank you. It works like expected, if you want to backup DBNAME1 first, than USER_DATABASES etc..
As Ola writes:
> You can also specify just one or a few databases, before USER_DATABASES. These databases will then be backed up first.

In another case, I have to defer a large database to the end of the list of databases being backupped: @databases = "USER_DATABASES, DBNAME1" should backup all user databases alphabetically except DBNAME1 that should be the last database backupped.

Is it possible to implement this, too?
