### ISSUE TITLE
Error while backing up to multiple network folders

### ISSUE THREAD

**Issue by xAnder1402** [olahallengren/sql-server-maintenance-solution#495]
Don't work:
@Directory = '\\RESERVE\mssqlbackup$, \\RESERVE\mssqlbackupmirror$',
@MirrorDirectory = 'F:\MSSQL\BACKUP',

Don't work:
@Directory = 'F:\MSSQL\BACKUP',
@MirrorDirectory = '\\RESERVE\mssqlbackup$, \\RESERVE\mssqlbackupmirror$',

Don't work:
@Directory = 'F:\MSSQL\BACKUP, \\RESERVE\mssqlbackup$',
@MirrorDirectory = '\\RESERVE\mssqlbackupmirror$',

Working:
@Directory = 'F:\MSSQL\BACKUP',
@MirrorDirectory = '\\RESERVE\mssqlbackupmirror$',

**Comment by olahallengren** [comment]
This is working as designed.

We are here using backup mirroring and backup striping together.

The number of striped directories (comma in between) has to be the same for the directory and the mirror directory.

So this should also work:

```
@Directory = 'F:\MSSQL\BACKUP, \RESERVE\mssqlbackup$',
@MirrorDirectory = '\RESERVE\mssqlbackupmirror$, \RESERVE\mssqlbackupmirror2$',
```

I will improve the error message for this.

**Comment by olahallengren** [comment]
I have improved the error message here.
https://ola.hallengren.com/versions.html
