### ISSUE TITLE
Backup LOG <DBName> To Disk = 'NUL'

### ISSUE THREAD

**Issue by BanyardiSchmardi** [olahallengren/sql-server-maintenance-solution#520]
Broken LSN.  

Microsoft SQL Server 2016 (SP2-GDR) (KB4532097) - 13.0.5102.14 (X64)   Dec 31 2019 22:39:35   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

--// Version: 2020-01-26 14:06:53  

EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@Directory = 'V:',
@BackupType = 'LOG',
@Verify = 'N',
@CleanupTime = 48,
@CheckSum = 'Y',
@LogToTable = 'Y'

When testing the restore for any of my databases, I am getting a command to: 
           Backup LOG <DBName> To Disk = 'NUL'  
which breaks the LSN.  

Brandon.Forest@RiverCityBank.com
Senior SQL DBA

**Comment by Directory** [comment]
use codeblocks plz

**Comment by BanyardiSchmardi** [comment]
The Veeam network backup solution had a legacy job running to truncate the SQL Log files for all the databases on the production server.  This command took the form: 
Backup <database name> LOG To Disk = N'NUL' 
This broke the LSN chain every night.
