### ISSUE TITLE
LogToTable in different database intead of Master

### ISSUE THREAD

**Issue by celiocf1981** [olahallengren/sql-server-maintenance-solution#525]
First let me tell you that your maintenance solution is awesome and i really like. 

A very important feature to me is the ability to log all process in a table where i can analyses later the performance and look for improvements. 
But i think use Master database (system db) as repository is not so good, i prefer to create a new user database and save all logs, store procedures and etc over there.  

So is it possible to create a variable in the procedures to the "@LogToTable" in a database that i point ? 

Thanks again.

**Comment by Jonathan-Quilter** [comment]
check the details here - https://ola.hallengren.com/frequently-asked-questions.html

**Comment by olahallengren** [comment]
You can create the log table and the stored procedures in any database (but the log table and the stored procedures have to be in the same database).
