### ISSUE TITLE
Striped Backup dynamic parameters 

### ISSUE THREAD

**Issue by ronaldgithub** [olahallengren/sql-server-maintenance-solution#531]
Is the 'Allocated extent page count' calculated correctly for multiple database files?

**SQL Server version and edition**
Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19042: ) (Hypervisor) 

**Version of the script**
----------------------------------------------------------------------------------------------------
  --// Source:  https://ola.hallengren.com                                                        //--
  --// License: https://ola.hallengren.com/license.html                                           //--
  --// GitHub:  https://github.com/olahallengren/sql-server-maintenance-solution                  //--
  --// Version: 2020-12-31 18:58:56                                                               //--
  ----------------------------------------------------------------------------------------------------

**What command are you executing?**
/*
Date and time: 2021-06-02 11:15:22
Database: [StackOverflow]
State: ONLINE
Standby: No
..
Allocated extent page count: 820744 (6412.062500 MB) <----
Modified extent page count:     200    (1.562500 MB)
*/

exec dbo.DatabaseBackup 
  @Databases =  'StackOverflow'
, @Directory = 'D:\backups'
, @BackupType = 'Full'
, @Compress = 'Y'
, @CheckSum = 'Y'
, @NumberOfFiles = 4
-- , @MinBackupSizeForMultipleFiles = 5120    -- Threshold in MB for when multiple files should be created
-- , @MinBackupSizeForMultipleFiles = 10240 -- Threshold in MB for when multiple files should be created
, @MinBackupSizeForMultipleFiles = 51200 -- Threshold in MB (50gb) for when multiple files should be created

**What output are you getting?**
I get one file.

Command: BACKUP DATABASE [StackOverflow] TO DISK = N'D:\backups\WIN10\StackOverflow\Full\WIN10_StackOverflow_Full_20210602_114119.bak' WITH CHECKSUM, COMPRESSION
Processed 12494864 pages for database 'StackOverflow', file 'StackOverflow_1' on file 1.
Processed 12429320 pages for database 'StackOverflow', file 'StackOverflow_2' on file 1.
Processed 12480808 pages for database 'StackOverflow', file 'StackOverflow_3' on file 1.
Processed 12494856 pages for database 'StackOverflow', file 'StackOverflow_4' on file 1.
Processed 1 pages for database 'StackOverflow', file 'StackOverflow_log' on file 1.
BACKUP DATABASE successfully processed 49899849 pages in 833.107 seconds (467.938 MB/sec).

**Comment by ronaldgithub** [comment]
Compare the # of extents

/*
Allocated extent page count: 1168344 (9127.687500 MB) StackOverflow2013 
Allocated extent page count:  820744 (6412.062500 MB) StackOverflow    <<<--- much bigger database
*/

DECLARE @CurrentAllocatedExtentPageCount bigint
DECLARE @CurrentModifiedExtentPageCount bigint
DECLARE @CurrentBackupType nvarchar(max) = 'FULL' 
DECLARE @DatabaseMessage nvarchar(max) = '' 

SELECT @CurrentAllocatedExtentPageCount = SUM(allocated_extent_page_count)
,  @CurrentModifiedExtentPageCount = SUM(modified_extent_page_count) 
FROM sys.dm_db_file_space_usage

select @CurrentAllocatedExtentPageCount
, @CurrentModifiedExtentPageCount

  IF @CurrentBackupType IN('DIFF','FULL') 
  AND EXISTS(SELECT * FROM sys.all_columns 
  WHERE object_id = OBJECT_ID('sys.dm_db_file_space_usage') 
  AND name = 'modified_extent_page_count')
    BEGIN
      SET @DatabaseMessage = 'Allocated extent page count: ' 
		+ ISNULL(CAST(@CurrentAllocatedExtentPageCount AS nvarchar) 
		+ ' (' + CAST(@CurrentAllocatedExtentPageCount * 1. * 8 / 1024 AS nvarchar) + ' MB)','N/A')
      RAISERROR('%s',10,1,@DatabaseMessage) WITH NOWAIT
END

**Comment by olahallengren** [comment]
How many files are you getting with ```@MinBackupSizeForMultipleFiles = 5120```?

**Comment by olahallengren** [comment]
I have tested this and it works for me.

@ronaldgithub do you still have a repro?

**Comment by olahallengren** [comment]
I have been reviewing this again and in my testing it works as it should.

I am closing this issue. Please write back if you have any more information. I will then reopen it.
