### ISSUE TITLE
Running DBCC CHECKDB in the order of the last successful CHECKDB (LastKnownGood)

### ISSUE THREAD

**Issue by OliverUweHahn** [olahallengren/sql-server-maintenance-solution#54]
Hi Ola,
it would be perfect to run DBCC CHECKDB not in alphabetical order.
Maybe we could add an option to run DBCC CHECKDB according to the latest successful CHECKDB (LastKnownGood).
I have a customer with a large instance of 20 databases with each database 2-5 TB in size.
The customer wants that DBCC CHECKDB only runs during the weekend. 
The result is, that only the first 5 databases are being consistency checked.
Attached is my approach to add an option called OrderByLastKnownGood.
Best regards,
Oliver
[MaintenanceSolution_order_by_LastKnownGood.zip](https://github.com/olahallengren/sql-server-maintenance-solution/files/2047579/MaintenanceSolution_order_by_LastKnownGood.zip)

**Comment by olahallengren** [comment]
Thank you. This is very interesting.

It is easy to check LastGoodCheckDbTime now with DATABASEPROPERTYEX.

There is an issue that if you run it on the secondary replica in an availability group, it will show the information from the primary.

**Comment by olahallengren** [comment]
Another option could be to do the ordering based on successful checkdb operations in the dbo.CommandLog table.

That would have the advantage that it would work also in the availability group scenario.

**Comment by OliverUweHahn** [comment]
Hi Ola, yes. This covers many sceanrios. The only caveat I currently see, is that some customers only want to run DBCC CHECKDB on only one replica. For example, one of my customers is running CHECKDB only on the primary replica. This would not be possible when reading the last successful date from the CommandLog table. 
A 90% solution would be to read the database property when DBCC CHECKDB should run from the primary replica, otherwise we can read it from CommandLog.
But there are still two caveats:
- if the CommandLog table is empty or was pruned
- if someone wants to run CHECKDB for example only on one secondary replica (f.e. preferred backup replica)
I see, it is getting complicated. :-)
I know that it is recommended to run CHECKDB on all replicas, but at least my customers only want to run DBCC CHECKDB on only one replica.
Best regards,
Oliver

**Comment by olahallengren** [comment]
Thank you for the feedback.

Just some background in case anyone is not aware:
With availability groups and database mirroring each replica has its own data files and storage subsystem. It is possible to have corruption on the primary replica, and not on the secondary, or the other way around. When you do a checkdb, you are only checking the replica, where you are running the check.

Based on this, I am thinking that, even in a scenario where the customer only wants to perform checkdb on one of the replicas, wouldn't it make sense to do the ordering, based on when that local replica was last checked?

**Comment by olahallengren** [comment]
Or maybe I should support ordering by LastGoodCheckDbTime using DATABASEPROPERTYEX, and dbo.CommandLog, and let the user select the method that he or she prefers? I could introduce a new ordering parameter, and have different values for different ordering options.

**Comment by OliverUweHahn** [comment]
Hi Ola,
the problem with DATABASEPROPERTYEX is that it is currently only available in SQL Server 2016 SP2.
Let's keep it by analyzing the CommandLog table for now. It would be great to have an execution option for running DBCC CHECKDB. If we want to run it only on the primary. or align it to preferred backup replica or just any replica.
For one of my customers that only wants to run it on the primary replica, I just could add a dummy job, that adds a log record to all replicas.
Then there is no difference when the primary replica changes.
I know there is no perfect solution because of the lack of feature, that SQL Server cannot record the last successful execution of CHECKDB somewhere else (f.e. in the master or in msdb) or tracking this flag in teh database properties for all replicas.
Best regards,
Oliver

**Comment by olahallengren** [comment]
I have been implementing this now. It is in the branch [feature_database_order].

There are two different options:

1. Order by LastGoodCheckDbTime in DATABASEPROPERTYEX
If this is an availability group, it will use the time for the last checkdb on the primary replica.
This option is currently only available in SQL Server 2016 SP2.

```
EXECUTE dbo.DatabaseIntegrityCheck
@Databases = 'USER_DATABASES',
@CheckCommands = 'CHECKDB',
@DatabaseOrder = 'DATABASE_LAST_GOOD_CHECK_ASC'
```

2. Order by the time for the last successfull checkdb in the dbo.CommandLog - table
If this is an availability group, it will use the time for the last checkdb on this specific replica.

```
EXECUTE dbo.DatabaseIntegrityCheck
@Databases = 'USER_DATABASES',
@CheckCommands = 'CHECKDB',
@DatabaseOrder = 'REPLICA_LAST_GOOD_CHECK_ASC',
@LogToTable = 'Y'
```

**Comment by OliverUweHahn** [comment]
I have tested and deployed the new version at two of my customers.
And it just works fine! 👍 
Great work! :-)

My customers are not on the latest builds. So I needed to use the 'REPLICA_LAST_GOOD_CHECK_ASC' option.

Best regards,
Oliver

**Comment by olahallengren** [comment]
I have added support for ```@DatabaseOrder = 'DATABASE_LAST_GOOD_CHECK_ASC'``` and ```@DatabaseOrder = 'DATABASE_LAST_GOOD_CHECK_DESC'``` in SQL Server 2014 SP3.
