### ISSUE TITLE
On sql server 2017, backup script claims directory does not exist

### ISSUE THREAD

**Issue by tommls** [olahallengren/sql-server-maintenance-solution#549]
agent jobs for full backup on sql server 2017 all claim the unc path directory does not exist
it is a recent version, this issue occurs only with sql server 2017 standard on win2k19
it does not occur with other sql versions
have tried script with both domain account and gMSA account, same failure
complete r/w access to the network share is enabled
thank you, tom

**Comment by tommls** [comment]
I can make things work by using a local volume for backup, e.g. D:\BACKUP, but this is not ideal for 20+ GB databases...I really need to know how to make this script see the unc path, which has 'everyone' and 'guest' read/write permissions for doing backups etc. Thank you, Tom

**Comment by olahallengren** [comment]
Could you check the check list in the Frequently Asked Questions under "How do I back up to a network share?"?
https://ola.hallengren.com/frequently-asked-questions.html
