### ISSUE TITLE
backups fail for clusterless AG configuration

### ISSUE THREAD

**Issue by sherrerk** [olahallengren/sql-server-maintenance-solution#56]
the script is recognizing databases contained in a clusterless AG, however is not working correctly because there is no cluster name.  i fixed the script locally by checking the clustername for N'' and naming it clusterless which allows backups.

**Comment by olahallengren** [comment]
I have released a fix for this issue.
https://ola.hallengren.com/versions.html

**Comment by sherrerk** [comment]
Thanks Ola... everything works great now!
