### ISSUE TITLE
Option to allow for custom text in the backup file name

### ISSUE THREAD

**Issue by sam-bryant** [olahallengren/sql-server-maintenance-solution#57]
We perform a lot of one off backups of databases, prior to manual database updates, or other random work.  We like to append our names and a description to these backups to help us when it comes time to clean them up (we don’t feel comfortable deleting some of these on a regular schedule).

I'm thinking something along the lines of @CustomText = '_TicketNNNN_BeforeManualUpdate_sbryant', which would create a backup named "ServerName$InstanceName_DatabaseName_FULL_COPY_ONLY_20180531_082341__TicketNNNN_BeforeManualUpdate_sbryant.bak".  The custom text could go anywhere in the name, just wanted to provide an example.

Let me know if I can provide any additional information.
Thanks!
Sam

**Comment by olahallengren** [comment]
How about this?

I have the parameter description.
https://ola.hallengren.com/sql-server-backup.html#Description

Some time ago I added support for configuring the file name.
https://ola.hallengren.com/sql-server-backup.html#FileName

I could add a token for Description.

You could then do like this:

```
@Description = 'BeforeMigration',
@FileName = {ServerName}${InstanceName}_{DaabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Description}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}
```

**Comment by sam-bryant** [comment]
I missed that functionality release.  It looks like I could probably make that work without any change on your end:

```
DECLARE @Description NVARCHAR(MAX) = '_TicketNNNN_BeforeManualUpdate_sbryant'
DECLARE @FileName NVARCHAR(MAX) = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_'+@Description+'_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}'
EXECUTE [dbo].[DatabaseBackup] ... @FileName = @FileName
```

It sounds like I could take this 3 liner down to 1 if you added that token, but I will leave that up to you since it appears I have a workaround.

Thanks for the information.

**Comment by srutzky** [comment]
@olahallengren Thanks for adding this ability. I remember asking for it a couple few years ago (pre-GitHub days) and had not noticed that it had been added.

**Comment by olahallengren** [comment]
I have added the token {Description} now. It can be used in both file names and directories.
https://ola.hallengren.com/versions.html

Any characters that are not allowed in the file system are removed.

**Comment by sam-bryant** [comment]
Wow, super fast turnaround!  Thanks Ola!
