### ISSUE TITLE
DatabaseBackup performance bug on large databases

### ISSUE THREAD

**Issue by jimithing1980** [olahallengren/sql-server-maintenance-solution#571]
**Description of the issue**
This looks to have been resolved on 5/22/2019, but has since been reintroduced.  The original bug was #232  
Since then, the following code black has been moved back out of the IF @CurrentBackupType = @BackupType block:

```
IF @CurrentDatabaseState = 'ONLINE' AND EXISTS(SELECT * FROM sys.all_columns WHERE object_id = OBJECT_ID('sys.dm_db_file_space_usage') AND name = 'modified_extent_page_count') AND (@CurrentAvailabilityGroupRole = 'PRIMARY' OR @CurrentAvailabilityGroupRole IS NULL)
    BEGIN
      SET @CurrentCommand = 'SELECT @ParamAllocatedExtentPageCount = SUM(allocated_extent_page_count), @ParamModifiedExtentPageCount = SUM(modified_extent_page_count) FROM sys.dm_db_file_space_usage'

      EXECUTE @CurrentDatabase_sp_executesql @stmt = @CurrentCommand, @params = N'@ParamAllocatedExtentPageCount bigint OUTPUT, @ParamModifiedExtentPageCount bigint OUTPUT', @ParamAllocatedExtentPageCount = @CurrentAllocatedExtentPageCount OUTPUT, @ParamModifiedExtentPageCount = @CurrentModifiedExtentPageCount OUTPUT
    END
```

This is causing issues with very large databases.  I run 10 minute LOG backups, but this block takes upwards of 30 minutes to run on it's own for two of my databases which are each over 15TB.  

**SQL Server version and edition**
Microsoft SQL Server 2019 (RTM-CU5) (KB4552255) - 15.0.4043.16 (X64)   Jun 10 2020 18:25:25   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

**Version of the script**
Version: 2020-12-31 18:58:56

**What command are you executing?**
DatabaseBackup

**What output are you getting?**

**Comment by olahallengren** [comment]
I have improved this so that sys.dm_db_file_space_usage is only queried when needed.
https://ola.hallengren.com/versions.html

Please try out the new version.
