### ISSUE TITLE
Procedure databaseBackup fails with parameters issue.

### ISSUE THREAD

**Issue by sree464** [olahallengren/sql-server-maintenance-solution#575]
Version: SQL Server 2016(13.0.5888.11)
Edition: Enterprise Edition
The log backup job fails with below error message (only on few Instances)
HResult 0x1FD2, Level 16, State 2 Procedure DatabaseBackup has no parameters and arguments were supplied. Process Exit Code 1. The step failed. 

job Step:
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d dba -Q "EXECUTE [dbo].[DatabaseBackup] @Databases = 'USER_DATABASES',@Directory = N'\\NASShare\Folder', @BackupType = 'LOG', @Verify = 'Y', @CleanupTime = 480, @CheckSum = 'Y', @LogToTable = 'Y'" -b

**Comment by olahallengren** [comment]
Does it happen consistently for the instances with the issue?

Could you try this:
1. Drop the job on an instance with the issue
2. Script out the job on an instance that does not have the issue and create it on the instance where you have the issue

**Comment by olahallengren** [comment]
Could you also try installing the latest Cumulative Update Package.

**Comment by olahallengren** [comment]
I am not able to reproduce this issue.
