### ISSUE TITLE
DatabaseBackup: @MaxFileSize parameter returns incorrect file size number

### ISSUE THREAD

**Issue by FidanAliev** [olahallengren/sql-server-maintenance-solution#585]
I've assigned a predefined file size number to backup the databases. 
Therefore, I set the @MaxFileSize predefined number like the below script.
When we applied to compress the database backup like 914GB data, it couldn't split the files. So we got only 205GB compressed file. 
Frankly, we don't get any incorrect results from other databases.

You can also find my script below.

Version: Microsoft SQL Server 2019 Copyright (C) 2019 Microsoft Corporation  Enterprise

**EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@BackupType = 'FULL',
@MAXTRANSFERSIZE=4194304,
@BLOCKSIZE=65536,
@MaxFileSize =1290000,
@URL = @urldir,
@Verify = 'Y',
@Compress = 'Y',
@ChangeBackupType = 'Y',
@CheckSum = 'Y',
@Updateability = 'ALL',
@LogToTable = 'Y',
@Execute = 'Y';**

**Output
Output only writes for one file instead of splitting different files.
It returns the error message because the file size is oversized.
https:....bak failed. Device has reached its limit of allowed blocks.**

Thank you!

**Comment by olahallengren** [comment]
Could you try setting ```@MaxFileSize``` to a lower value?

**Comment by olahallengren** [comment]
Are you still having this issue? Could you share the complete output from the stored procedure?

**Comment by olahallengren** [comment]
I was looking at this again.

MaxFileSize - "Specify a maximum backup file size in MB. DatabaseBackup will dynamically calculate the number of backup files."
https://ola.hallengren.com/sql-server-backup.html#MaxFileSize

You have set `@MaxFileSize =1290000`. That is 1290 GB.

Your database is only 914 GB.

You will have to set `@MaxFileSize` to a smaller value to get multiple files.

**Comment by olahallengren** [comment]
I am closing this issue. Please write back if you are experiencing that it is not working as it should. I will then reopen the issue.
