### ISSUE TITLE
IndexOptimize: @Databases parameter checking database nonexistence makes job fail

### ISSUE THREAD

**Issue by yazalpizar** [olahallengren/sql-server-maintenance-solution#61]
With latest version on IndexOptimize, a new check on the @Databases parameter was introduced to check if a database exists (lines 908-913) for Availability Groups verification, if not, it raises and error. Yesterday I noticed a new version and, as many times before, modified to put a *N* on the create jobs parameter and ran the script. But tonight one of our defrag index jobs failed with this error:

> There was an issue with defragmenting of these databases
> ALL_DATABASES,-mydatabase,-mynextdatabase,-evenmoredatabases...
> The following databases in the @Databases parameter do not exist: [mydatabase]

On our case, the database name had the hyphen character (-) to exclude this particular database from the index so it would not affect anything else. We also have a AOAG group with 3 servers and several databases and everything works ok. I removed the database from the parameter, but I would suggest adding a check for the hyphen character as that database in particular will not affect the process.

**Comment by olahallengren** [comment]
Thank you for the feedback. There are of course pros and cons of this check. In the current design, the stored procedure will raise an error, but then continue working on the databases.

I got a lot of feedback before from users that had been doing some small typo, and the job just ran successfully. That can be bad even if you exclude a database.

**Comment by yazalpizar** [comment]
Hmmm... not in our case, the job stopped immediately and sent that error. Needed to launch it manually. It will not fail again as I removed that database from @databases parameter.

What about when doing the check, but when the database name has the hyphen, meaning to exclude it, doesn't matter if it exists or not, it will be excluded from the process, so don't rise any error. Maybe log a message on the CommandLog table with something like "database X not found on step/process Y".

**Comment by olahallengren** [comment]
Which version are you on? Could you please do a ```SELECT @@VERSION``` on this server.

How are you executing the stored procedure? SQL Server Agent job? Which job step type?

**Comment by olahallengren** [comment]
Could you also test this in a SSMS query window:
```
EXECUTE dbo.IndexOptimize
@Databases = 'USER_DATABASES, -NonExistingDatabase',
@Execute = 'N'
```

**Comment by yazalpizar** [comment]
Microsoft SQL Server 2014 (SP2-CU5) (KB4013098) - 12.0.5546.0 (X64) 
Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

Result of the EXECUTE, it starts, throws an error and continue running, as you commented before.
> Msg 50000, Level 16, State 1, Procedure IndexOptimize, Line 904
> The following databases in the @Databases parameter do not exist: [NonExistingDatabase].

Running on an Agent job step, type Database Maintenance. And I found why it stops, check the code we use on the job step, is inside a `TRY/CATCH` so we can send a personalized alert email with info for debugging. Will need to rethink it. Thanks for your help @olahallengren 

`BEGIN TRY

EXECUTE IndexOptimize
    @Databases = 'ALL_DATABASES,-NonExistingDatabase',
    @FragmentationLow = NULL,
    @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE',
    @FragmentationHigh = 'INDEX_REBUILD_ONLINE',
    @FragmentationLevel1 = 25,
    @Indexes = 'ALL_INDEXES,-exclude_huge_index',
    @FragmentationLevel2 = 90,
    @UpdateStatistics = 'ALL',
    @OnlyModifiedStatistics = 'Y',
    @FillFactor = null,
    @LogToTable = 'Y';
	
END TRY
BEGIN CATCH

DECLARE @err_msg AS NVARCHAR(MAX),
		@p_body AS NVARCHAR(MAX),
		@p_subject AS NVARCHAR(MAX) =  N'This is a warning about failed defragmentation',
		@p_recipients AS NVARCHAR(MAX) = N'email@email.com',
		@p_profile_name AS NVARCHAR(MAX),
		@instance VARCHAR(30) =  (SELECT  @@SERVERNAME)

SET @err_msg = ERROR_MESSAGE();
SET @p_profile_name = 'DBA Mail ' + @instance + ' profile'
SET @p_body = 'There was an issue defragmenting these databases</br><b>list of databases on @Databases parameter</b>.</br></br>' + @err_msg

EXEC msdb.dbo.sp_send_dbmail
  @profile_name = @p_profile_name,
  @recipients = @p_recipients,
  @body = @p_body,
  @body_format = 'HTML',
  @subject = @p_subject

END CATCH;`

**Comment by olahallengren** [comment]
I would not recommend putting TRY CATCH around the call to the stored procedure.

Could you do something like this?
```
DECLARE @ReturnCode int

EXECUTE @ReturnCode = dbo.IndexOptimize
@Databases = 'USER_DATABASES, -NonExistingDatabase',
@Execute = 'N'

IF @ReturnCode <> 0
BEGIN
  -- Mail sending stuff
END
```

**Comment by yazalpizar** [comment]
Interesting, ran a short test and good to go. Will do some more tests and if our team agrees, will use this option.

**Comment by olahallengren** [comment]
About the question what to do in the stored procedures, if the database that you want to exclude does not exist:

Let's say that a DBA is creating a new maintenance job that should run at 12 AM. For one of the databases, this is the most critical time of the day, so he needs to exclude this database. Unfortunately he is typing in the database name incorrectly. What should happen?

I think that there are three options:

1. Ignore the database that does not exist. This is the old behavior in my stored procedures. It can take a long time until the DBA finds out about the issue as the job completes successfully.

2. Raise an error, but continue execution. This is the new behavior in my stored procedures. The DBA will find out about the issue after the first execution, as the job failed.

3. Raise an error and stop execution. The job will fail instantly.

I changed to the "Raise an error, but continue execution" -  behavior in the 27 Mar 2018 release.

**Comment by olahallengren** [comment]
I have now changed the severity for this check from 16 to 10. You will still get the message in the output file, but the job will not fail.
