### ISSUE TITLE
Ola Hallengren Transaction log backup completion status but no backup created

### ISSUE THREAD

**Issue by mdesphy** [olahallengren/sql-server-maintenance-solution#619]
**Description of the issue**  
The log backup job appears successful but it didn't actually created the backup file.  Tracing from the dbo.databasebackup script, the sys.fn_hadr_backup_is_preferred_replica always returns 0, regardless if its the primary or secondary server.  This may be due to the @@SERVERNAME that does not match SERVERPROPERTY('ServerName').  It only differs in case.  It is the same in both our stage and prod server, but sys.fn_hadr_backup_is_preferred_replica only works fine in stage.

**SQL Server version and edition**
Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64)   Nov  3 2021 19:19:51   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

**Version of the script**
Version: 2022-01-02 13:58:13

**What command are you executing?**
EXECUTE [dbo].[DatabaseBackup] 
@Databases = 'USER_DATABASES', 
@Directory = N'******', 
@BackupType = 'LOG', 
@Verify = 'Y', 
@CleanupTime = 48, 
@CheckSum = 'Y', 
@LogToTable = 'Y'" -b

**What output are you getting?**
The job completed successfully though there's no backup created.  The message "Is preferred backup replica" returns NO for both the primary and secondary server.

**Comment by olahallengren** [comment]
Could you modify the ```@@SERVERNAME```, so that it matches SERVERPROPERTY('ServerName') exactly, also in casing, and then test again?
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/rename-a-computer-that-hosts-a-stand-alone-instance-of-sql-server?view=sql-server-ver15

**Comment by mdesphy** [comment]
There are other instances in that server, so our IT infra preferred not to change the computer name.  I wonder why it is not a problem in older versions of sql maintenance script.

**Comment by olahallengren** [comment]
We need to get sys.fn_hadr_backup_is_preferred_replica return the correct result, as DatabaseBackup is relying on that.

We know that there is an issue with sys.fn_hadr_backup_is_preferred_replica, when the ```@@SERVERNAME``` is not set correctly, so I think that changing that would be the easiest next step. Another option is to open a support case with Microsoft about sys.fn_hadr_backup_is_preferred_replica.
