### ISSUE TITLE
option WITH INIT

### ISSUE THREAD

**Issue by Harald-P** [olahallengren/sql-server-maintenance-solution#63]
Hi Ola,

can you implement please the parameter WITH INIT?

I need it, when i use the parameter:
@FileName = '{DatabaseName}.{FileExtension}'

Thank you
Harald

**Comment by olahallengren** [comment]
I have released a new version with support for INIT.
https://ola.hallengren.com/versions.html

https://ola.hallengren.com/sql-server-backup.html#Init

I realize that it can be useful in your scenario.

**Comment by Harald-P** [comment]
Hi Ola,

Thank you for the change.
I have tested it with this parameters:
 
EXECUTE dbo.DatabaseBackup
@Databases = 'ALL_DATABASES',
@BackupType = 'FULL',
@Directory = 'F:\transfer’,
@CopyOnly = 'Y',
@Compress = 'Y',
@Verify = 'N',
@CheckSum = 'Y',
@init= 'Y',
@LogToTable = 'Y',
@DirectoryStructure = '{ServerName}',
@FileName = '{DatabaseName}.{FileExtension}'
 
And it works perfectly.

Thanks
Harald
