### ISSUE TITLE
Duplicate Backups using parallel backup feature

### ISSUE THREAD

**Issue by sqlshark1** [olahallengren/sql-server-maintenance-solution#636]
I use the utility to backup about 11,000 databases in parallel and we have noticed some duplicate backups. 

Code to perform abckups from the jobs, I use from 4-6 jobs at once. I have the 2020-12-31 bits.

 EXECUTE [DMG_UTILITY].[dbo].[DatabaseBackup] @Databases = @DBName, @Directory = N'\\FileServer\Prod_Backup_\', @BackupType = 'FULL', @CopyOnly='Y',  @Verify = 'Y', @DatabasesInParallel = 'Y', @DatabaseOrder = 'DATABASE_SIZE_DESC', @CleanupTime = 2163, @CheckSum = 'Y',@LogToTable = 'Y'

**Comment by sqlshark1** [comment]
Will you be developing a fix for the dupl;icate issue in the future? Thanks in advance, Ed

**Comment by bwiggins10** [comment]
I use this across various environments with varying SQL Versions, and have not had this occur before and have used every single parameter you've used EXCEPT for @DatabaseOrder = 'DATABASE_SIZE_DESC' leading me to believe it's a bug with this parameter. I would try omitting this and see if it recurs.

**Comment by sqlshark1** [comment]
Thanks for the advise, I will test the theory and let you know.
Ed Pochinski
________________________________

**Comment by sqlshark1** [comment]
We will be testing removal of the @DatabaseOrder parameter this week. Will be a good test, I backup over 11,000 databases across 7 Azure VM's. I will post the findings when testing is completed. The code is awesome, I use a modified backup procedure where it inserts all full backup names to a tracking table and I log ship over 11,000 db's with the code for backing up purposes, we developed some nice restore code on the DR end of things. Aside from the Azure VM disks not being very fast with IO it works well. I dual stream the tran logs each run and the setup streams 6 backups at once.

**Comment by sqlshark1** [comment]
OK you are correct Ben, I removed that parameter [ @DatabaseOrder ] and the duplicate backups have vanished. Thanks very much for your time in testing and posting. Ed Pochinski
