### ISSUE TITLE
ola.hallengren.com results in a timeout

### ISSUE THREAD

**Issue by pregress** [olahallengren/sql-server-maintenance-solution#648]
**Description of the issue**

When browsing to [ola.hallengren.com](https://ola.hallengren.com/) for the documentation I get a timeout. Tried on multiple devices / connections.

**Comment by AJ-Fritz** [comment]
It's not just you.  downforeveryoneorjustme.com says it's down for everyone.

**Comment by bwiggins10** [comment]
Site is back up, can close this issue out :)
