### ISSUE TITLE
Unable to use the restore procedure with the latest commandexecute stored proc by Ola

### ISSUE THREAD

**Issue by sindu1489** [olahallengren/sql-server-maintenance-solution#649]
hi Sir,
I am trying to use this stored procedure for restore for ola backups but it throws the below error
Msg 201, Level 16, State 4, Procedure CommandExecute, Line 0 [Batch Start Line 0]
Procedure or function 'CommandExecute' expects parameter '@DatabaseContext', which was not supplied.

Could you please advise
thanks

**Comment by sindu1489** [comment]
I am using BrentOzar Stored procedure for restore and am unable to proceed as it throws the below error.
Msg 201, Level 16, State 4, Procedure CommandExecute, Line 0 [Batch Start Line 0]
Procedure or function 'CommandExecute' expects parameter '@DatabaseContext', which was not supplied.
Please kindly help sir

**Comment by wendydroid** [comment]
you need to update your version of brent's sp_databaserestore procedure. the older versions didn't supply this parameter. the newest version does.

**Comment by CarlosGzz-SQL** [comment]
> Comman

you can update commandExecute to use @DatabaseContext ='master' as default, that will bypass your issue, had the same few days ago.
