### ISSUE TITLE
@@servername and SERVERPROPERTY('ServerName') are the same, only case is different

### ISSUE THREAD

**Issue by PekeDBA** [olahallengren/sql-server-maintenance-solution#651]
**Description of the issue**
Backup scripts don't start as described on your site :
"Added a check in DatabaseBackup that @@SERVERNAME is the same as SERVERPROPERTY('ServerName'). The check is only performed if Always On is enabled.
The background for this is that sys.fn_hadr_backup_is_preferred_replica is not working correctly if @@SERVERNAME is not correct.
"
Because of the case sensitivety of the sql server instance @@servername and SERVERPROPERTY('ServerName') are different in case and stop starting the backup jobs.

/********* VALUES *******/
select 
	@@servername as [@@servername], --Returns the name of the local server that is running SQL Server.
	SERVERPROPERTY('ServerName') as [ServerProperty_ServerName], --Both the Windows server and instance information associated with a specified instance of SQL Server.
	SERVERPROPERTY('MachineName') as  [ServerProperty_MachineName], -- Windows computer name on which the server instance is running. For a clustered instance, an instance of SQL Server running on a virtual server on Microsoft Cluster Service, it returns the name of the virtual server.
	SERVERPROPERTY('ComputerNamePhysicalNetBIOS') as [ServerProperty_ComputerNamePhysicalNetBIOS], -- NetBIOS name of the local computer on which the instance of SQL Server is currently running.
	@@SERVICENAME as  [@@SERVICENAME],
	name as [sysservers_name], 
	data_source as [sysservers_data_source] 
from sys.servers

/******** Results *******/
@@servername = SERVER06\INST01
ServerProperty_ServerName = server06\INST01
ServerProperty_MachineName =	server06	
ServerProperty_ComputerNamePhysicalNetBIOS	= SERVER06	
@@SERVICENAME	=  INST01	
sysservers_name = 	SERVER06\INST01
sysservers_data_source = SERVER06\INST01

Is this "work as designed" with a special reason or is this a little bug ?	

**SQL Server version and edition**
Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)   Jan 12 2022 22:30:08   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

**Version of the script**
Version: 2020-12-31 18:58:56 

**What command are you executing?**
FULL, DIFF and LOG backups; One example : 
EXECUTE dbo.DatabaseBackup
			@Databases = 'SYSTEM_DATABASES',
			@Directory = N'\\xxxxxxxxx.local\Share\Backups\xxxxxxxx\SQL Backups',
			@BackupType = 'FULL',
			@Verify = 'Y',
			@Compress = 'Y',
			@CheckSum = 'Y',
			@CleanupTime = 360,
			@MaxFileSize=10240,
			@LogToTable = 'Y'
			

**What output are you getting?**
 [SQLSTATE 01000] (Message 50000)  The @@SERVERNAME does not match SERVERPROPERTY('ServerName'). See https://docs.microsoft.com/en-us/sql/database-engine/install-windows/rename-a-computer-that-hosts-a-stand-alone-instance-of-sql-server.

**Comment by PekeDBA** [comment]
I resolved the problem in the availability group by renaming the servernames with the correct CASE : 
sp_dropserver <'old_name\instancename'>
GO
sp_addserver <'new_name\instancename'>, local
GO
The job runs without error BUT.... no transactionlog backups are made...

If I run the command manually I get no errors but I dont see any backups starting:
**_EXECUTE dbo.DatabaseBackup
			@Databases = 'USER_DATABASES',
			@Directory = N'\\xxx.local\Share\Backups\',
			@BackupType = 'LOG',
			@ChangeBackupType = 'Y',
			@Compress = 'Y',
			@CheckSum = 'Y',
			@CleanupTime = 72,
			@LogToTable = 'Y'_**

Output looks normal but no transacyionlog backups or cleans or done (see output below). Any suggestions ?
 

**_Date and time: 2022-07-22 09:11:54
Server: xxx\INST01
Version: 15.0.4236.7
Edition:_ Enterprise Edition: Core-based Licensing (64-bit)
Platform: Windows
Procedure: [master].[dbo].[DatabaseBackup]
Parameters: @Databases = 'USER_DATABASES', @Directory = '\\xxx.local\Share\Backups\', @BackupType = 'LOG', @Verify = 'N', @CleanupTime = 72, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'N', @ChangeBackupType = 'Y', @BackupSoftware = NULL, @CheckSum = 'Y', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @MinBackupSizeForMultipleFiles = NULL, @MaxFileSize = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = NULL, @Credential = NULL, @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @AvailabilityGroupDirectoryStructure = '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @Format = 'N', @ObjectLevelRecoveryMap = 'N', @ExcludeLogShippedFromLogBackup = 'Y', @StringDelimiter = ',', @DatabaseOrde...
Version: 2020-12-31 18:58:56
Source: https://ola.hallengren.com
	
Date and time: 2022-07-22 09:11:54
Database: [schedbe]
State: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Recovery model: FULL
Encrypted: No
Is accessible: Yes
Availability group: xxxag1
Availability group role: PRIMARY
Availability group backup preference: NONE
Is preferred backup replica: No
Differential base LSN: 4701000012685600235
Last log backup LSN: 4706000024956000001
Last log backup: 2022-07-19 15:07:14
Log size since last log backup (MB): 623.051
	
Date and time: 2022-07-22 09:11:54
Database: [test]
State: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Recovery model: FULL
Encrypted: No
Is accessible: Yes
Availability group: xxxag1
Availability group role: PRIMARY
Availability group backup preference: NONE
Is preferred backup replica: No
Differential base LSN: 48000001202400001
Last log backup LSN: 48000000442400001
Last log backup: 2022-05-06 11:00:03
Log size since last log backup (MB): 4.30078
	
Date and time: 2022-07-22 09:11:54
	

Completion time: 2022-07-22T09:11:54.8002394+02:00_**

**Comment by PekeDBA** [comment]
the log backups you see in the output above are done manually...

**Comment by PekeDBA** [comment]
I found a workaround. I put an extra parameter @OverrideBackupPreference='Y' and then it worked. Even when all my Always On nodes are in "Any replica" Backup preference... So I think there will be a little bug in the Backuppreference check (in combination with the Latin1_General_BIN collation), which is overrided by this parameter...

**Comment by cankaya07** [comment]
I hit the same problem when I move the new server.
 Servername named in camelcase standart. e.g MpsServerSql1  Server collation TURKISH_CS_AI
also server joined an AlwaysON.

Cae senstivity is the main prıblem I guess.

`select @@SERVERNAME `
MpsServerSql1

`select  SERVERPROPERTY('ServerName') r`
MPSSERVERSQL1


up-to-date your scripts.
SQL Server Version:

Microsoft SQL Server 2019 (RTM-CU29) (KB5046365) - 15.0.4405.4 (X64)   Oct 23 2024 08:45:19   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

I can handle easily dropserver and addserver. Maybe case sensitive could be forgotten.

**Comment by Stiffboard** [comment]
I always create a database management database with case insensitive collation, problem solved. Master and msdb should be left as is. But there could be a convert to upper or lower case...but SQL variant...

**Comment by cankaya07** [comment]
> I always create a database management database with case insensitive collation, problem solved. Master and msdb should be left as is. But there could be a convert to upper or lower case...but SQL variant...

I thought may be case insensitivy was overlooked. I made my comment thinking that. Otherwise I am totally agree with you.

**Comment by olahallengren** [comment]
I have experienced that users have been running into issues with backups not being performed, because `sys.fn_hadr_backup_is_preferred_replica` was returning 0 on all replicas.

I found out that `sys.fn_hadr_backup_is_preferred_replica` was not working correctly if `@@SERVERNAME` was not returning the same value as `SERVERPROPERTY('ServerName')`. This could happen if the server has been renamed. It could be that it can happen in other scenarios as well.

Therefore I added this check:

```
  IF @@SERVERNAME <> CAST(SERVERPROPERTY('ServerName') AS nvarchar(max)) AND SERVERPROPERTY('IsHadrEnabled') = 1
  BEGIN
    INSERT INTO @Errors ([Message], Severity, [State])
    SELECT 'The @@SERVERNAME does not match SERVERPROPERTY(''ServerName''). See ' + CASE WHEN SERVERPROPERTY('IsClustered') = 0 THEN 'https://docs.microsoft.com/en-us/sql/database-engine/install-windows/rename-a-computer-that-hosts-a-stand-alone-instance-of-sql-server' WHEN SERVERPROPERTY('IsClustered') = 1 THEN 'https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/install/rename-a-sql-server-failover-cluster-instance' END + '.', 16, 1
  END
```

My reasoning so far has been that it is better to have this check, than having users run into issues with backups not being performed.

**Comment by olahallengren** [comment]
There is another similar issue, https://github.com/olahallengren/sql-server-maintenance-solution/issues/692

**Comment by Stiffboard** [comment]
This will perhaps fix it? 

IF UPPER(@@SERVERNAME) <> UPPER(CAST(SERVERPROPERTY('ServerName') AS nvarchar(max))) 
   AND SERVERPROPERTY('IsHadrEnabled') = 1

**Comment by olahallengren** [comment]
The question is how sys.fn_hadr_backup_is_preferred_replica behaves, when there are differences in the casing.

I was searching for it and I found some people reporting issues.

I will review the code in sys.fn_hadr_backup_is_preferred_replica.

**Comment by olahallengren** [comment]
I was checking the code of `sys.fn_hadr_backup_is_preferred_replica` on SQL Server 2022 CU15.

It has this comment:

```
    -- Hotfix for IcM356152806  
    -- Under case sensitive collation, replica_server_name and @@servername   
    -- is not considered the same if the letter case is different
```

I also see UPPER in several places.

I will implement the change in DatabaseBackup that @Stiffboard suggests.
