### ISSUE TITLE
Now includes references to sys.master_files which stops the solution from running in Azure SQL DB

### ISSUE THREAD

**Issue by timjohnstone** [olahallengren/sql-server-maintenance-solution#67]
I have used a previous release in Azure SQL DB by using the FAQ advice to deploy the SPs manually and not through MaintenanceSolution.sql, and obviously schedule using some other technology.
I've just tried to use the latest files in the same way, and executing IndexOptimize results in an error "Invalid object name 'sys.master_files'."
It IS possible to query sys.database_files to get the information in the same format, but it's only for the current database. In Azure, that's a requirement - you can't change database context within a script. To maintain on-premise compatibility without using sys.master_files you'd have to loop over the selected databases for maintenance to query their individual sys.database_files.

For now I've worked round the problem by modifying IndexOptimize.sql locally to use this IF statement:
`  IF ServerProperty('EngineEdition') = 5
  BEGIN
	  INSERT INTO @tmpDatabases (DatabaseName, DatabaseType, AvailabilityGroup, DatabaseSize, [Order], Selected, Completed)
	  SELECT [name] AS DatabaseName,
			  CASE WHEN name IN('master','msdb','model') THEN 'S' ELSE 'U' END AS DatabaseType,
			  NULL AS AvailabilityGroup,
			  (SELECT SUM(size) FROM sys.database_files WHERE [type] = 0 AND database_id = sys.databases.database_id) AS DatabaseSize,
			  0 AS [Order],
			  0 AS Selected,
			  0 AS Completed
	  FROM sys.databases
	  WHERE [name] <> 'tempdb'
	  AND source_database_id IS NULL
	  ORDER BY [name] ASC
  END
  ELSE
  BEGIN
	  INSERT INTO @tmpDatabases (DatabaseName, DatabaseType, AvailabilityGroup, DatabaseSize, [Order], Selected, Completed)
	  SELECT [name] AS DatabaseName,
			  CASE WHEN name IN('master','msdb','model') THEN 'S' ELSE 'U' END AS DatabaseType,
			  NULL AS AvailabilityGroup,
			  (SELECT SUM(size) FROM sys.master_files WHERE [type] = 0 AND database_id = sys.databases.database_id) AS DatabaseSize,
			  0 AS [Order],
			  0 AS Selected,
			  0 AS Completed
	  FROM sys.databases
	  WHERE [name] <> 'tempdb'
	  AND source_database_id IS NULL
	  ORDER BY [name] ASC
  END`

**Comment by olahallengren** [comment]
I am sorry about this bug. It has been fixed now.
