### ISSUE TITLE
Add flag to generate backup filenames in UTC

### ISSUE THREAD

**Issue by StrayCatDBA** [olahallengren/sql-server-maintenance-solution#679]
Filename tokens are currently based on local time.  Add a parameter '@UseUTC bit'  that bases tokens on UTC time.

This would allow easier integration of the Backup Solution into custom Log Shipping setups as sqllogship.exe uses the filename to determine restore latency.

**Comment by olahallengren** [comment]
I am looking at implementing this.

I am thinking about calling the parameter @TimestampTokensInUTC to make it more clear that it will only affect the tokens, not the logging.

**Comment by olahallengren** [comment]
This has been released.

Here is the documentation:
https://ola.hallengren.com/sql-server-backup.html#TokenTimezone
