### ISSUE TITLE
USER_DATABASES - LOG only appears to backup one DB

### ISSUE THREAD

**Issue by luckymike** [olahallengren/sql-server-maintenance-solution#72]
We're using the maintenance solution to perform daily Full backups and periodic Log backups. On a server with 2 databases, the full and Full (and Diff) backups work as expected, producing the following files:
```
C:\Backups\ServerName\DB_A\FULL\ServerName_DB_A_FULL...
C:\Backups\ServerName\DB_B\FULL\ServerName_DB_B_FULL...
```
The Log backups, however, only produce output files for the first database:
```
C:\Backups\ServerName\DB_A\LOG\ServerName_DB_A_LOG...
```

I confirmed that both backups are invoked exactly the same way, other than changing the backup type. 

Is this a bug, or is there something I should check in our configuration?

**Comment by olahallengren** [comment]
Could it be that one of the databases is in Simple recovery model? Log backups can only be performed if the database is in Full or Bulk-Logged recovery model.

**Comment by luckymike** [comment]
That appears to be it. Not sure why one was that way and the other wasn't. 

Thanks!
