### ISSUE TITLE
Can ability to suppress TLOG backup entry in SQL Error Log (no effect to Full backup entries) be added?

### ISSUE THREAD

**Issue by jgreer3395** [olahallengren/sql-server-maintenance-solution#765]
**Description of the feature**
Without implementing the global flag to suppress all backup info from the SQL error log, would it be possible to add capability for Ola script to include something to suppress TLOG backup entries from the SQL error log, keeping the Full backup entries?

**Comment by olahallengren** [comment]
I am not aware of a way to do that in SQL Server.
