### ISSUE TITLE
Exclude BizTalk databases from backups

### ISSUE THREAD

**Issue by whoisbruce** [olahallengren/sql-server-maintenance-solution#78]
Being lazy here... If the backup job could be given the name of the BizTalk management database, it could automatically exclude any databases that BizTalk backups jobs deal with...

**Comment by olahallengren** [comment]
Hugo Kornelis has this code to exclude the BizTalk databases, when executing DatabaseBackup.
https://sqlserverfast.com/blog/hugo/2018/07/t-sql-tuesday-104-make-ola-backup-biztalk/

Would this work for you?
