### ISSUE TITLE
Option to send a backup to a NUL: file

### ISSUE THREAD

**Issue by dlanclos60** [olahallengren/sql-server-maintenance-solution#80]
We have QA servers configured with Availability Groups. AG’s require us to use FULL recovery option and, therefore, we have to backup the transaction logs to prevent them from filling up the drive. But because these are QA servers, there is no need or desire to backup the databases.
 
I used your Maintenance Solution to create the jobs on both of the QA nodes involved (primary and secondary).  I modified the command to backup the transaction logs on all the databases in the AG’s to the default backup directory and then to delete the backup after one hour since we don’t care about maintaining the backup files:
 
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d master -Q "EXECUTE [dbo].[DatabaseBackup] @Databases = 'AVAILABILITY_GROUP_DATABASES', @Directory = NULL, @BackupType = 'LOG', @Verify = 'N', @CleanupTime = 1, @CheckSum = 'N', @LogToTable = 'N'" -b
 
I scheduled the log backup job to run every hour.
 
Today I looked on one of the QA servers and saw all the tlog backup files are there. I then saw the notation on your website:
 
"DatabaseBackup has a check to verify that transaction log backups that are newer than the most recent full or differential backup are not deleted."
 
The most recent backup of the database was when we set up the AG’s, so this is probably why all the tlog backups are still there. 
 
It sounds like I would also need to configure and schedule a job to run a backup on all the databases as well. We would still maintain a days’ worth of tlog backup files as well as the most recent database backup file, which is not desired since we don’t need any backups at all.
 
Is there a better way to do this? There doesn’t seem to be a way to have a backup going to a NUL: file as with this TSQL command:
 
BACKUP LOG Financials_Data TO DISK='NUL:'
GO
 
Something like that would have worked very well. I tried “@Directory = ‘NUL:’ “ as an argument to DatabaseBackup, but it was rejected as invalid.

**Comment by LowlyDBA** [comment]
Agreed - It would be really nice to be able to use this for AG groups on lower environments so we don't ever have to deal with the tlog files. 

We currently have them set to just do an aggressive cleanup schedule, but I'd much rather be able to have the backup jobs across environments only differ in backup location vs having different cleanup schedules.

**Comment by ad-eternum** [comment]
Another vote for this feature. Please add support to backup to NUL device.

**Comment by olahallengren** [comment]
I have implemented this now in the branch [feature_backup_to_nul]. Please try it out.

```
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'NUL',
@BackupType = 'LOG',
@Compress = 'Y',
@CheckSum = 'Y'
```

**Comment by olahallengren** [comment]
This has now been released.
https://ola.hallengren.com/versions.html
