### ISSUE TITLE
Diff backup of new database created fom another database is not being converted to full.  

### ISSUE THREAD

**Issue by DBAFaiz** [olahallengren/sql-server-maintenance-solution#800]
We have a 3rd party app that creates a database from another database backup. 
Even though the @ChangeBackupType = 'Y' , maintenance script is not running a full backup for this database as "differential_base_lsn" is not null for the newly created database.

**Comment by olahallengren** [comment]
This is by design. The database backup that the database was restored from counts as a full backup in this case.

The logic in the script only works if the database was created using CREATE DATABASE.
