### ISSUE TITLE
Support Veeam Databases backups

### ISSUE THREAD

**Issue by KMParks** [olahallengren/sql-server-maintenance-solution#805]
Veeam has a database tool a lot like DDBoost called MSSQLRecoveryManager.exe  It would be nice to have your solution support veeam.  
The documentation for the tool is here  https://helpcenter.veeam.com/docs/backup/plugins/data_backup_mssql_plugin.html?ver=120

**Comment by olahallengren** [comment]
Executing an .exe file would require enabling xp_cmdshell, that is considered a security issue.
