### ISSUE TITLE
7Zip compression

### ISSUE THREAD

**Issue by IngoBleile** [olahallengren/sql-server-maintenance-solution#813]
Dear Ola,

I very much appreciate your work. Our customer's DB backup has around 80 GB and around 18 GB compressed which is just too much to download to our remote development machines. 7Zip compresses down to around 7 GB which is still ok for downloads. I tried to integrate that into your "DatabaseBackup" SP but it's hacky and ugly. Would that be in an interesting option for you to implement? As you know all the variables and temp tables, I think you could get this done in 2 hours. I would even pay for that if you want, just let me know. That would be better invested than my hacking around. :)

Thank you, Ingo

**Comment by olahallengren** [comment]
The challenge is that I would need to use xp_cmdshell that is considered a security issue.
