### ISSUE TITLE
partitioned table with computed column

### ISSUE THREAD

**Issue by clambrechts** [olahallengren/sql-server-maintenance-solution#82]
Hi,
 
I use several partitioned table with computed column, and I have often error :

servername | DatabaseName | Command | CommandType | StartTime | EndTime | ErrorNumber | ErrorMessage | DateInsert
-- | -- | -- | -- | -- | -- | -- | -- | --
FCS1WPDATAMART1\FD105PRD10 | FR_PRICING | ALTER   INDEX [PK_HistoRefPrix_PRID_PartitionColumn] on   [FR_PRICING].[dbo].[tbl_HistoRefPrix] REBUILD partition = 1 with   (SORT_IN_TEMPDB = ON, MAXDOP = 8) | ALTER_INDEX | Dec 14 2017 3:10PM | Dec 14 2017 3:10PM | 1934 | ALTER   INDEX failed because the following SET options have incorrect settings:   'QUOTED_IDENTIFIER'. Verify that SET options are correct for use with indexed   views and/or indexes on computed columns and/or filtered indexes and/or query   notifications and/or XML data type methods and/or spatial index operations. | Dec 15 2017 5:10AM

I think the script don’t manage computed column which force QUOTED_IDENTIFIER.
 
It’s possible to correct this with :
 
select t.name, c.name
from sys.tables t
inner join sys.computed_columns c on c.object_id = t.object_id
where c.is_persisted = 1
 
;-)
 
Regards.

**Comment by olahallengren** [comment]
Could you run this select and let me know what it returns:
```
SELECT sys.objects.name,
       uses_ansi_nulls,
       uses_quoted_identifier
FROM sys.sql_modules
INNER JOIN sys.objects ON sys.sql_modules.object_id = sys.objects.object_id
WHERE sys.objects.name IN('CommandExecute','IndexOptimize')
```

**Comment by ConstantineK** [comment]
I am going to take a crack at reproducing the issue, but if you have a create statement for the table/indexes in question, that might make it simpler to narrow down. 

I believe what Ola may be pointing to is that the MaintenanceSolution.sql file which installs the scripts never sets QUOTED_IDENTIFIER to OFF (at least in the versions I have) so its odd that the code itself would throw an error. I also checked the history of the code on github (going back a year or so) and even the individual items have SET QUOTED_IDENTIFIER ON for all the installing code.

The indexed view documentation says

> SET Option Requirements
> 
> The connection on which the index is created, and all connections trying INSERT, UPDATE, or DELETE statements that will change values in the index, must have six SET options set to ON and one option set to OFF. The optimizer ignores an index on a computed column for any SELECT statement executed by a connection that does not have these same option settings.
> 
> The NUMERIC_ROUNDABORT option must be set to OFF, and the following options must be set to ON:
> ANSI_NULLS
> ANSI_PADDING
> ANSI_WARNINGS
> ARITHABORT
> CONCAT_NULL_YIELDS_NULL
> QUOTED_IDENTIFIER
> 

The SET QUOTED_IDENTIFIER docs say

> For a top-level Ad-Hoc batch parsing begins using the session’s current setting for QUOTED_IDENTIFIER. As the batch is parsed any occurrence of SET QUOTED_IDENTIFIER will change the parsing behavior from that point on, and save that setting for the session. So after the batch is parsed and executed, the session’s QUOTED_IDENTIFER setting will be set according to the last occurrence of SET QUOTED_IDENTIFIER in the batch.
> Static SQL in a stored procedure is parsed using the QUOTED_IDENTIFIER setting in effect for the batch that created or altered the stored procedure. SET QUOTED_IDENTIFIER has no effect when it appears in the body of a stored procedure as static SQL.
> 
> For a nested batch using sp_executesql or exec() the parsing begins using the QUOTED_IDENTIFIER setting of the session. If the nested batch is inside a stored procedure the parsing starts using the QUOTED_IDENTIFIER setting of the stored procedure. As the nested batch is parsed the any occurrence of SET QUOTED_IDENTIFIER will change the parsing behavior from that point on, but the session’s QUOTED_IDENTIFIER setting will not be updated.
> 

So, my read is
* If you are ad hoc querying any QUOTED IDENTIFIER use changes the behavior from that point on. 
* If you use it in a stored procedure, it does nothing. 
* If you use it in dynamic sql, it will start using the stored procedure's created effect, you can change it in your scope, but it wont persist to the parent scope. 

So it might be useful to clarify, are you using the SQL Agent to run the jobs? If you run the alter index statement given does it fail normally?

**Comment by clambrechts** [comment]
Sorry for delay,

The code table 👍 


USE [FR_PRICING]
GO

/****** Object:  Table [dbo].[tbl_HistoRefPrix]    Script Date: 7/7/2018 11:25:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tbl_HistoRefPrix]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[tbl_HistoRefPrix](
	[DateRepli] [int] NULL,
	[ID] [int] NULL,
	[Sku] [varchar](64) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	[EAN] [varchar](21) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	[PRID] [int] NULL,
	[Title] [varchar](530) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	[MinPrix] [numeric](15, 4) NULL,
	[FGHRP_PartitionColumn]  AS (CONVERT([int],substring(CONVERT([varchar](max),[DateRepli],0),(5),(2)),0)) PERSISTED
) ON [partition_scheme_ByMonth]([FGHRP_PartitionColumn])
WITH
(
DATA_COMPRESSION = PAGE
)
END
GO

ALTER AUTHORIZATION ON [dbo].[tbl_HistoRefPrix] TO  SCHEMA OWNER 
GO

/****** Object:  Index [PK_HistoRefPrix_PRID_PartitionColumn]    Script Date: 7/7/2018 11:25:30 AM ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[tbl_HistoRefPrix]') AND name = N'PK_HistoRefPrix_PRID_PartitionColumn')
CREATE CLUSTERED INDEX [PK_HistoRefPrix_PRID_PartitionColumn] ON [dbo].[tbl_HistoRefPrix]
(
	[DateRepli] ASC,
	[PRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, DATA_COMPRESSION = PAGE) ON [partition_scheme_ByMonth]([FGHRP_PartitionColumn])
GO

all other parameter is by default. Yes, I use SQL Agent. Yes instruction failed, when i use directly ALTER INDEX.

**Comment by clambrechts** [comment]
and execute command

name	uses_ansi_nulls	uses_quoted_identifier
Commandexecute	1	0
indexOptimize	1	1

**Comment by olahallengren** [comment]
It looks like CommandExecute has SET QUOTED_IDENTIFIER OFF.

Could you script it out, and change it to SET QUOTED_IDENTIFIER ON.

Then please run this script again:

```
SELECT sys.objects.name,
       uses_ansi_nulls,
       uses_quoted_identifier
FROM sys.sql_modules
INNER JOIN sys.objects ON sys.sql_modules.object_id = sys.objects.object_id
WHERE sys.objects.name IN('CommandExecute','IndexOptimize')
```

**Comment by clambrechts** [comment]
I change this set 

name	uses_ansi_nulls	uses_quoted_identifier
Commandexecute	1	1
indexOptimize	1	1

**Comment by olahallengren** [comment]
This looks good. Could you check, if you are still getting the error, or if it has been resolved.

**Comment by clambrechts** [comment]
I must wait for some days, because this alter don't work every day. I will inform you friday, ok ?

**Comment by olahallengren** [comment]
This is very good. Thank you.

**Comment by clambrechts** [comment]
Hi, It's OK for me. I don't have problem.

**Comment by olahallengren** [comment]
I have added a check in the code, that QUOTED_IDENTIFIER is set to ON.
