### ISSUE TITLE
No way to make @URL the "standard" backup method

### ISSUE THREAD

**Issue by fill-e** [olahallengren/sql-server-maintenance-solution#825]
**Description of the feature**
With the addition of support for S3 it would be nice to add a parameter to make the @URL automatically appear in all the backup jobs.

Adding it to the initial config parameters would seem to be the obvious location 

DECLARE @CreateJobs nvarchar(max)          = 'Y'         
DECLARE @BackupDirectory nvarchar(max)     = NULL      
DECLARE @URL nvarchar(max) = NULL,
DECLARE @CleanupTime int                   = NULL        
DECLARE @OutputFileDirectory nvarchar(max) = NULL        
DECLARE @LogToTable nvarchar(max)          = 'Y'

**Comment by olahallengren** [comment]
@fill-e, I am looking at adding `@URL` to the header of MaintenanceSolution.sql.

It would then work like this that you would get an error, if you try to use both `@BackupDirectory` and `@URL`.

I would also not do anything with the credential in MaintenanceSolution.sql. If you have not created that you will get an error later when you run the job.

**Comment by olahallengren** [comment]
I have released this.
https://ola.hallengren.com/versions.html
