### ISSUE TITLE
Incrementals Statistics (SQL 2014)

### ISSUE THREAD

**Issue by clambrechts** [olahallengren/sql-server-maintenance-solution#83]
Hi,

It's possible to add fonctionnality, like indexes partitionned, to update statistics by partition in Statistics maintenance plan.

Regards

**Comment by olahallengren** [comment]
This is how it works for incremental statistics in the latest version.
https://ola.hallengren.com/versions.html

6 Jun 2018
"Added support for incremental statistics. It will automatically update statistics on the partition level for incremental statistics, if you have @PartitionLevel = 'Y' (which is the default)."

Please also see issue https://github.com/olahallengren/sql-server-maintenance-solution/issues/42.

**Comment by clambrechts** [comment]
Thanks
