### ISSUE TITLE
QAT Assist compression & the algorithm option for database backups 

### ISSUE THREAD

**Issue by StephenWeeksSch** [olahallengren/sql-server-maintenance-solution#830]
SQL Server 2022 brings in the ability to use QAT Assist compression for database backups, and thus the COMPRESSION option can now specify an ALGORITHM setting (either to use native compression or QAT) - can this be added to the backup proc?

**Comment by olahallengren** [comment]
I have been doing some more testing and released it.
https://ola.hallengren.com/versions.html
