### ISSUE TITLE
UTC date/time tokens

### ISSUE THREAD

**Issue by kschwartzatdattodotcom** [olahallengren/sql-server-maintenance-solution#839]
You currently support tokens for datetime parts (eg, year, hour, etc). These are supported in filenames/foldernames/etc.
It would be nice to have the option of specifying UTC values instead of local-time values.

**Comment by kschwartzatdattodotcom** [comment]
Are you suggesting just one token? If so what would the granularity be? Right now you provide granularity, via multiple tokens, down to the microsecond (not that I use it…).

I would think that for file names, YYYYMMDD_HHMMSS would be sufficient.

And thanks very much for the quick response!

Ken Schwartz

**Comment by olahallengren** [comment]
This would be a new parameter that would make all the timestamp tokens UTC tokens.

**Comment by olahallengren** [comment]
There is another similar request, #679

**Comment by kschwartzatdattodotcom** [comment]
Yes, I realized you meant a bit about 1 second after I hit “send”. 😊

And, yes, that would certainly take care of it, at least in terms of the use cases I need (and can think of).

Thanks again.

Ken

**Comment by olahallengren** [comment]
I have a test version.
https://github.com/olahallengren/sql-server-maintenance-solution/pull/840

You pass a parameter like this:
@TokenTimezone = 'UTC'

**Comment by kschwartzatdattodotcom** [comment]
Hi,

I just wanted to thank you for your swift response to this. I have already downloaded the latest version of your code, and tested to see if it met our requirements.
It was perfect.

Ken

**Comment by olahallengren** [comment]
I am happy that the feature worked as you wanted it to.

Here is the documentation:
https://ola.hallengren.com/sql-server-backup.html#TokenTimezone
