### ISSUE TITLE
Allow @AFTER_BACKUP cleanup to run even if backup is not verified

### ISSUE THREAD

**Issue by SQLDataCloud** [olahallengren/sql-server-maintenance-solution#849]
**Description of the issue**

Currently:

**AFTER_BACKUP	Delete old backup files after the backup and verify has been performed. If the backup or verify failed, then no backup files are deleted. This is the default.**

**SQL Server version and edition**
Microsoft SQL Server 2019 (RTM-CU27-GDR)

**Version of the script**
2022-12-03

**What command are you executing?**

DatabaseBackup

**What output are you getting?**
No output as such, however we have a 25TB database that creates a 5TB (compressed) backup over 10 files, it is backed up weekly (with daily differentials and 15mins trans logs).

We are happy to have 1 week this stored locally (gets copied to S3 bucket) however the following week another 5TB is created then on the third week the backup job fails as there is no more space left on disk. The @AFTER_BACKUP / CleanupTime = 168 does not run due to the fact we do not use @Verify = 'Y' as we don't have a large enough maintenance window to backup 25TB and perform a verify (this is done on another DR server).  Can you implement a parameter that states we wish to use @AFTER_BACKUP even if verify isn't used?

**Comment by Stiffboard** [comment]
You should delete before backup then. Or simply add more disk.

**Comment by olahallengren** [comment]
@SQLDataCloud, could you share the exact command with all the parameters, that you are running?

**Comment by olahallengren** [comment]
I just tested this and it works:

```
EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@Directory = 'C:\Backup',
@BackupType = 'FULL',
@Verify = 'N',
@Compress = 'Y',
@CheckSum = 'Y',
@CleanupTime = 24,
@CleanupMode = 'AFTER_BACKUP'
```

**Comment by olahallengren** [comment]
The code looks like this:

```
      -- Delete old backup files, after backup
      IF ((@CurrentBackupOutput = 0 AND @Verify = 'N')
      OR (@CurrentBackupOutput = 0 AND @Verify = 'Y' AND NOT EXISTS (SELECT * FROM @CurrentBackupSet WHERE VerifyOutput <> 0 OR VerifyOutput IS NULL)))
      AND (@BackupSoftware <> 'DATA_DOMAIN_BOOST' OR @BackupSoftware IS NULL)
      AND @CurrentBackupType = @BackupType
```

**Comment by SQLDataCloud** [comment]
Hi Ola, thank you for your reply.

Our code is almost like your example however we are omitting the @Verify parameter.  
I will test it using @verify = 'N'

**Comment by olahallengren** [comment]
This should not make any difference as the default is '

**Comment by SQLDataCloud** [comment]
I will check tomorrow morning after weekly full backup.

**Comment by olahallengren** [comment]
Thank you. Please check that you have an output file configured for the job.

**Comment by olahallengren** [comment]
One thing to consider is the `@CleanupTime` parameter:

It is calculated before the backup starts. However, xp_delete_file is deleting files based on the modified date. This means that if you are running weekly backups, you will have to set the `@CleanupTime`  a bit lower than 168 hours (basically 168 minus the execution time for the backup minus some buffer for variations).

**Comment by SQLDataCloud** [comment]
Ah, that makes sense the backup does take a few hours to complete. We are using @cleanuptime = 168.

**Comment by olahallengren** [comment]
Try setting it to `@CleanupTime = 164` or something (depending on how long time your backup normally takes).

**Comment by SQLDataCloud** [comment]
I will try that and let you know the outcome.

**Comment by olahallengren** [comment]
@SQLDataCloud, how has it been running after this change?

**Comment by SQLDataCloud** [comment]
Will be able to check in the morning.
