### ISSUE TITLE
Mirrored backup to URL

### ISSUE THREAD

**Issue by revanes** [olahallengren/sql-server-maintenance-solution#85]
I want to get standard and mirrored backup to URL (to URL 1, URL 2) with your DatabaseBackup script 
But there is no support for mirrored backup to URL in the script.

**Comment by olahallengren** [comment]
This feature has now been added.
https://ola.hallengren.com/versions.html

https://ola.hallengren.com/sql-server-backup.html#MirrorURL

**Comment by revanes** [comment]
I used this feature in databasebackup script. It works fine, thanks for your solution.
