### ISSUE TITLE
June 2018 Maintenance Update Failure with SQL 2005

### ISSUE THREAD

**Issue by btolfree** [olahallengren/sql-server-maintenance-solution#90]
Attempted to apply the June 2018 update to various SQL Server instances (where the stored procedures and jobs were already in place).  I updated the field "create jobs" to N as they were already present and executed against the Master database.    Upon execution, I received an error:

Msg 102, Level 15, State 1, Procedure DatabaseBackup, Line 1432 [Batch Start Line 318]
Incorrect syntax near '('.

To me, it appears the code is looking for sys.dm_db_log_stats (which is not present in SQL 2005).

As a resolution, it was found that the compatibility level for the system databases was set to '90', except for master which was set to '80'   Upon recommendation, I changed the master compatibility level to '90' and the script executed without issue.

This updated maintenance script works on all of my other servers.  Thank you.

**Comment by reharmsen** [comment]
compatibility 80 is still supported in SQL Server 2008 and SQL Server 2008 R2.
Both are still supported by Microsoft until 9th of July 2019.
So you might still want to support level 80 until the 9th of July 2019

**Comment by olahallengren** [comment]
The question is how much of any issue it would be. It would only be the database, where you are creating the maintenance objects, that would have to be in compatibility level 90 or higher. All other databases could still be in any compatibility level.

The reason for considering this, is that I am not able to find a good workaround in the code.

**Comment by reharmsen** [comment]
Dropping support for 80 or less will probably not have a huge impact.
Also as it is recommended to have database in the same level as the server.
So 90 is fine.

**Comment by olahallengren** [comment]
I have added a check for the compatibility level, and also updated the documentation.

"The database where you are creating the objects, has to be in compatibility level 90 or higher. All other databases can be in any compatibility level."
